### ISSUE TITLE
Support optional 'scrollback' 

### ISSUE THREAD

**Issue by yuvipanda** [42wim/matterircd#1]
So when users disconnect and then reconnect, they can get all the messages in channels since their last connection. This would make it work similar to an IRC Bouncer (like ZNC)

This would require that there be state kept however to mark the 'last read position' via IRC.

**Comment by 42wim** [comment]
I just implemented the basic support for this. Messages not yet read on mattermost will be posted on the IRC channels.
For now only when viewed on mattermost, the 'since' will be reset.

**Comment by 42wim** [comment]
Since is now also getting reset when viewed on IRC.

**Comment by yuvipanda** [comment]
Awesome <3

On Tue, Nov 10, 2015 at 1:37 PM, @42wim <notifications@github.com> wrote:

> Since is now also getting reset when viewed on IRC.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/42wim/matterircd/issues/1#issuecomment-155574812>.
>



-- 
Yuvi Panda T
http://yuvi.in/blog
