### ISSUE TITLE
Latest dockerhub image doesn't work with mattermost 3.10.0

### ISSUE THREAD

**Issue by epatpol** [42wim/matterircd#100]
As 3.10.0 was released some days ago, and that I can see the new release under the appropriate releases section for it, I thought 42wim/matterircd:latest would be up to date but it seems it's not working with 3.10.0 at the moment.

`
mattermost | unsupported mattermost version: 3.10.0.3.10.0.7cba3a4efdae5d0ca100a07c5e0c94b3.false
`

Just wanted to let you know!

Thanks

**Comment by 42wim** [comment]
Thanks for letting me know, docker images are being build
