### ISSUE TITLE
Messages being cropped when they are longer than what IRC allows for

### ISSUE THREAD

**Issue by Ppjet6** [42wim/matterircd#103]
## Steps to reproduce

- Connect to mattermost via matterircd
- Have somebody send a message long enough from the mattermost side, (the RFC states 512 chars including the command etc.)

## What happens

The message is cropped.

## What I expect

The message should appear entirely. I know this is due to IRC limitations, but the gateway could send multiple messages until it is complete.

**Comment by Ppjet6** [comment]
I would argue this is actually a bug and really requires attention. I am not really fond of losing (part of) messages

**Comment by 42wim** [comment]
Fixed in master, release v0.12.1 soon
