### ISSUE TITLE
No mention is made of people posting images

### ISSUE THREAD

**Issue by Ppjet6** [42wim/matterircd#105]
## Steps to reproduce

- Connect to matterircd
- Drop a picture from the mattermost side

## What happens

On the mattermost side, a message appears with a way to display the image.
On the IRC side, nothing.

## What I expect

Have something displayed stating at least that an image has been posted and I can't see it.
Bonus point: display a link to it if possible.
Is this a mattermost limitation as well?

**Comment by 42wim** [comment]
This works, but you'll have to enable public links on your mattermost server.
https://docs.mattermost.com/administration/config-settings.html#public-links

**Comment by Ppjet6** [comment]
You mean the bonus point works, what if it's not enabled? Is there still a way to say "An image has been posted [..] use the web version if you want to see it" or similar ?

**Comment by 42wim** [comment]
For now it isn't possible, but it's a good idea.

**Comment by Ppjet6** [comment]
On 2017/07/12, Wim wrote:
> Closed #105 via 42wim/mm-go-irckit@f37e066b6f1f7e9b5e64fe09c99ab2e0a991717e.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/42wim/matterircd/issues/105#event-1161484518

Thank you very much for closing all these issues so quickly!

-- 
Maxime Buquet
