### ISSUE TITLE
System actions appear as normal messages

### ISSUE THREAD

**Issue by Ppjet6** [42wim/matterircd#107]
## Steps to reproduce

- Connect to matterircd
- Make a system action from the mattermost side, for example changing the channel header

## What happens

`< XXX> XXX updated the channel header from: YYY to ZZZ`
The action is displayed as a message and with the nick of the user themselves.

## What I expect

Some actions can be mapped to IRC actions. Like the a user joining/parting a room, (#104), display name or channel header is likely to appear as topic. For the rest maybe there is a way to make it appear as an action in the IRC client and not a usual message?

**Comment by 42wim** [comment]
Could you make a list about all of those system actions that need to be fixed ?
