### ISSUE TITLE
Sending message to &users channel results in strange error

### ISSUE THREAD

**Issue by ocrete** [42wim/matterircd#108]
Sending a message to the &users channel results in the following error, it should probably be intercepted and made nicer..

<mattermost> msg: what does this do ? could not be send: : Sorry, we could not find the page., There doesn't appear to be an api call for the url='/api/v3/teams/ap3t3epbubbjdk8p6smzrouwxy/channels/&users/posts/create'. Typo? are you missing a team_id or user_id as part of the url?

**Comment by 42wim** [comment]
Fixed in master, release v0.12.1 soon
