### ISSUE TITLE
Always binds to non-tls port

### ISSUE THREAD

**Issue by jmallach** [42wim/matterircd#109]
Hi Wim,

We have very recently started a test of Mattermost 3.10 + mattericd, and things are doing great except for a few glitches some of my coworkers have submitted issues for in the last few hours.

When starting the server, I notice there is no way to avoid mmircd opening a non-tls port. As I am only interested in TLS connections, I don't specify any -bind option, but of course the default interface:port gets open. Can we avoid that via, eg. -bind none?

Thanks for developing matterircd!

**Comment by 42wim** [comment]
Fixed in master, release v0.12.1 soon

**Comment by 42wim** [comment]
You'll have to specify ```-bind ""```
