### ISSUE TITLE
Find a way to make reactions more explicit, or ignore them

### ISSUE THREAD

**Issue by Ppjet6** [42wim/matterircd#111]
## Steps to reproduce

- Connect to matterircd
- Send a message (probably doesn't matter from where)
- Have people react to this message

## What happens

The message gets displayed multiple times (1 + number of reactions)

## What I expect

I had no idea these were reactions. At first I thought they were message corrections but I couldn't find any difference. I would suggest either finding a way to say that people reacted to the message, or completely ignore these reactions.

**Comment by 42wim** [comment]
It does show it's a reaction

```
21:54 < wim> lala
21:54 < wim> test (re @wim: lala)
```

the ```(re @wim: lala)```

Better suggestions are welcome.

**Comment by Ppjet6** [comment]
Sorry I should have specified I was talking specifically about emoji. It needs to be enabled in advanced features, under Pre-releases features / "Enable emoji picker for reactions and message input box".

**Comment by 42wim** [comment]
Ok, the issue here is that I can't make a difference between an edited post that has already reactions (emojis) or a post that has got a reaction added.

They both show up as edited posts.

The only thing I can do here is not relay a post if it's an "edited post" and it has reactions.

**Comment by 42wim** [comment]
Implement the above rules :)
