### ISSUE TITLE
Join/Parts not in sync with mattermost

### ISSUE THREAD

**Issue by Ppjet6** [42wim/matterircd#113]
Every so often I will see people leaving a channel and just after that it will be marked as they joined it again, followed by a message from System saying that person has left the channel. And later when that person actually rejoins the channel I will only get the message from System and no part/join dance again.

```
19:47 -!- XXX [foo@bar] has left #off-topic []
19:47 -!- XXX [foo@bar] has joined #off-topic
19:47 < XXX> XXX has left the channel.
Day changed to [..]
15:34 < XXX> XXX has joined the channel.
```

I am not sure how to debug this, I suppose there is some event sent and I should be able to verify which is which. Please tell me if there is an easy way to debug this on production, without taking down the server or running it in debug mode. If not I'll try to spawn a test environment.

**Comment by 42wim** [comment]
Fixed in master, release v0.12.1 soon

**Comment by Ppjet6** [comment]
Hi! I'm running 9b09123 (master) and I'm still observing similar issues.

The joins are displayed right before a user writes their first message in a channel, and not when they actually join the channel.

**Comment by 42wim** [comment]
What mattermost version ?
What total amount of users on the server ?

**Comment by Ppjet6** [comment]
Mattermost 4.8.1, about 130 users

**Comment by 42wim** [comment]
Ok, 130 users isn't hitting a user limit of 50000 users :)

So happens this:
- when the user is already on the channel and then types a message ?
OR
- when the user joins the channel (not on the channel before) and types a message for the first time ?

**Comment by Ppjet6** [comment]
On 2018/05/01, Wim wrote:
> Ok, 130 users isn't hitting a user limit of 50000 users :)
> 
> So happens this:
> - when the user is already on the channel and then types a message ?
> OR
> - when the user joins the channel (not on the channel before) and types a message for the first time ?

The latter!

A user joins a channel, nothing happens. He then sends a message, and
what is displayed in the bridge is:
> -!- foo [..] has joined #channel
> < foo> message

As a side effect, the user doesn't appear in the userlist of the client
until the join action is sent, which is also annoying.

-- 
Maxime “pep” Buquet

**Comment by 42wim** [comment]
Fixed in master

**Comment by Ppjet6** [comment]
Thanks!
