### ISSUE TITLE
Multi-person direct message creates an unleavable channel

### ISSUE THREAD

**Issue by bahamat** [42wim/matterircd#114]
Using direct message with a single user uses `/msg` with matterircd. But when a direct message is initiated that includes multiple users a new IRC room is created with a random identifier.

Once I'm aded to a multi-user direct message, I'm unable to permanently leave that room. I can `/part` the room, but the next time I connect to matterircd my IRC client automatically joins the direct message chat room.

**Comment by 42wim** [comment]
This should be fixed in master (0.15.0-dev), could you try?
