### ISSUE TITLE
Attachments don't show up in IRC

### ISSUE THREAD

**Issue by bahamat** [42wim/matterircd#115]
When someone attaches a file, with or without text, there is no message sent over IRC. As a matterircd user I never know when attachments are added.

At the very least, there should be some sort of message indicating that a file attachment was added. Ideally, with a permalink to the message/attachment.

**Comment by 42wim** [comment]
There definitely should be a message with a link.
What matterircd and mattermost version ?

**Comment by bahamat** [comment]
mattermost server is 3.9.0.
matterircd is 0.11.6.

I'm using Textual.app on Mac OS X, if it makes a difference.

**Comment by 42wim** [comment]
please upgrade to latest matterircd version 0.13.0

**Comment by bahamat** [comment]
Awesome, thanks!
