### ISSUE TITLE
Passwords with spaces unable to authenticate

### ISSUE THREAD

**Issue by mahlonsmith** [42wim/matterircd#116]
Messaging the bot with the **login** command  -- uses whitespace to separate arguments.

Since the last argument is always the password, would it be possible to concatenate all remaining args into the password?  People with spaces in their passwords are left out in the cold.

**Comment by 42wim** [comment]
thanks to @sarlalian a fix for this has been merged into master now.
You can now put the ```"password with spaces"``` between quotes
