### ISSUE TITLE
MM users don't get privmsgs sent from matterircd

### ISSUE THREAD

**Issue by jmallach** [42wim/matterircd#121]
Hello,

I'm seeing a regression since I upgraded matterircd from the 4.0-compatible version to the latest master (66c28de88561a559377a915505882cc572c24d07).

Our MM users are not getting private messages sent by matterircd users and are lost in the limbo. If they log into MM via web, privmsg messages go through as expected. There are apparently no relevant entries in the log.

Thanks again for your awesome support, Wim!

**Comment by 42wim** [comment]
You're welcome, thanks for reporting. 
Fixed now in master

**Comment by jmallach** [comment]
Wow, that was blazing fast! Thanks a lot!
