### ISSUE TITLE
Spurious topic change messages generated every time selecting a channel

### ISSUE THREAD

**Issue by TC01** [42wim/matterircd#124]
First, thanks a lot for matterircd: it's really great to be able to integrate mattermost into my IRC client (and not need to use the electron desktop app for Mattermost!).

I installed the latest docker image last week, and have connected to it from [Quassel](http://quassel-irc.org/), my IRC client of choice. I've noticed something odd. Every time I select a Mattermost channel in Quassel, a topic change message gets displayed. e.g.:

```
[17:57:38] * brosser has changed topic for #off-topic to: ""
[17:57:51] * brosser has changed topic for #off-topic to: ""
[19:36:32] * brosser has changed topic for #off-topic to: ""
[23:24:56] * brosser has changed topic for #off-topic to: ""
```

I am not trying to change the topic, I'm just selecting the channel (and I checked the Mattermost side to confirm I *don't* change the topic). So it seems to me that this shouldn't happen.

This is only a minor inconvenience, and I can simply tell Quassel to hide the topic change messages for these channels. But it would be nice if I didn't have to do that.

I'm not sure if this is actually an issue with matterircd overzealously trying to set the topic, or an issue with Quassel overzealously displaying topic change messages. I have been meaning to look into this on the Quassel side but haven't gotten around to it, so I figured I might as well file a bug here in the mean time.

EDIT: should it be relevant, this is with quassel running on Fedora (26).

**Comment by 42wim** [comment]
Could you let me know if this still happens with latest matterircd ? 

`42wim/matterircd:latest` if you're using docker or build from master.

If it still happens, could you let me know mattermost version and run `matterircd -debug` so we can see everything that happens.

**Comment by TC01** [comment]
Sorry for the delay in responding. I am still seeing this with the latest matterircd.

The mattermost version is "4.6.0.4.6.0.f21273f6d5461ccef0bf34f75e26e01e.false" according to the log.

Enabling ```matterircd -debug```, it looks like the topic change happens in response to a IRC join action when I select a given channel. Here is an extract from the debug log; this is the same timestamp that I see the topic change message in Quassel.

```
time="2018-02-15T16:28:12Z" level=debug msg="<- JOIN #lunch " module=matterircd 
time="2018-02-15T16:28:12Z" level=debug msg="Not joining 3qgjrknmspyap8ezsberc8ynzo already joined." module=matterclient 
time="2018-02-15T16:28:12Z" level=debug msg="Join channel lunch, id 3qgjrknmspyap8ezsberc8ynzo, err: <nil>" module=matterircd 
time="2018-02-15T16:28:12Z" level=debug msg="-> :TC01!quassel@172.17.0.1 TOPIC #lunch :Mealtime without borders within philly" module=matterircd 
[..."adding users to #lunch" messages trimmed...]
time="2018-02-15T16:28:13Z" level=debug msg="Executed &irc.Message{Prefix:(*irc.Prefix)(nil), Command:"JOIN", Params:[]string{"#lunch", ""}, Trailing:"", EmptyTrailing:false} <nil>" module=matterircd 
```

**Comment by 42wim** [comment]
If you join a new channel this is normal, it sets the topic of the channel you joined.
But this happens on channels you have already joined ?

**Comment by TC01** [comment]
That's correct, yes. (Hence the "Not joining 3qgjrknmspyap8ezsberc8ynzo already joined." message in the debug log). I tried selecting back and forth between two channels I was in and got similar messages for both.

**Comment by 42wim** [comment]
Well, the `already joined` message is from mattermost, not irc.
I'll have to take a look at Quassel, because normal irc clients can't join a channel they are already joined.

**Comment by 42wim** [comment]
This should be fixed in latest release
