### ISSUE TITLE
Release binary version mismatch, incorrect upload?

### ISSUE THREAD

**Issue by faljse** [42wim/matterircd#125]
Release download matterircd-linux64 v15 doesnt work with mattermost 4.2:
`login failedunsupported mattermost version: 4.2.0.4.2.0.832fe82b73beef5acdf851f6373dd9e3.false`

Startup message containst 0.14.0 version string:
`"Running version 0.14.0 87db357"`
md5sum also matches my v14 copy.

Could you re-check if maybe you did upload the old version by accident?

**Comment by 42wim** [comment]
@faljse you're right, filenames were changed and old version was uploaded.
It's fixed now, thanks for reporting

**Comment by faljse** [comment]
Thx!
