### ISSUE TITLE
/me sent from gateway not correctly displayed on mattermost

### ISSUE THREAD

**Issue by Ppjet6** [42wim/matterircd#127]
## Steps to reproduce

- Send a /me message

## What is expected

Message is displayed as sent, i.e., "&lt;nick&gt; &lt;message&gt;"

## What happens

As IRC sends messages with `\r\n`, a small square is displayed at the end of the message on the web interface.

**Comment by 42wim** [comment]
Fixed in master, thanks to @evelikov
