### ISSUE TITLE
Already read messages are replayed again and again

### ISSUE THREAD

**Issue by evelikov** [42wim/matterircd#130]
My wording might be funky, so please bare with me. Example scenario:

- User X writes something in channel A
- Connect to mattericd, the whole thing is replayed and should be considered as read
- Upon later reconnects you see _part_ of the conversation replayed, again
Obviously since it was read/replayed once it shouldn't show again.

Any tips and suggestions how to track/resolve this will be appreciated

**Comment by 42wim** [comment]
Yes, I've noticed this happening also, will take a look at it

**Comment by evelikov** [comment]
Recently we've switched to 0.17.2 and the bug (or one very much like it) seems to be present.
A message of mine (from a couple of days ago) is being replayed, every time I connect.

Any suggestions how to debug/address this?

**Comment by 42wim** [comment]
For now you'll have to run matterircd with `-debug`.

Could it be that this message was a deleted or edited message  ? or a normal message ?
Was it a public message or a DM ?

**Comment by evelikov** [comment]
Last time it happened, very last message was replayed. All my messages are sent via the bridge, although I may have had the webui opened during that time. Need to check if the latter plays any role.

I've seen the issue happen in both channels and DM. I don't recall any deleted/edited messages being replayed. Will double-check next time it happens.

**Comment by evelikov** [comment]
Right, so I've been hitting this again the last few days. To answer my previous comments:
- does having the webui opened (while sending via the bridge) affect this - doesn't seem to
- are the (replayed again and again) messages deleted/edited - no

To find the bug quicker, I'm thinking about adding a _ton_ of verbose debugging in the replay codebase.
@42wim can you share some pointers where to start, or about the more subtle parts of the process?

**Comment by 42wim** [comment]
@evelikov 
The code can be found here: 
https://github.com/42wim/matterircd/blob/dfb97b952477ecbe07c3ac6ed99f7118d59ddddd/vendor/github.com/42wim/mm-go-irckit/mmuser.go#L220-L241

Interesting would be dumping the `p` variable here 
https://github.com/42wim/matterircd/blob/dfb97b952477ecbe07c3ac6ed99f7118d59ddddd/vendor/github.com/42wim/mm-go-irckit/mmuser.go#L222

using something like: `logger.Debugf("full post %#v",p)`

`

**Comment by evelikov** [comment]
I have no plan to look at this, since I'm no longer using matterircd, Feel free to leave open or close.

**Comment by 42wim** [comment]
Did you find a better tool which hasn't got the issue? If so which one?

**Comment by evelikov** [comment]
Got tired of people calling out matterircd as buggy/etc when the issues were in MM itself.
Thus I'm using the lovely webapp these days - even sent [unrelated] fix or two MM way :-)

**Comment by 42wim** [comment]
oh okay, they were probably right sometimes too :)
Thanks for the feedback
