### ISSUE TITLE
": Invalid or expired session, please login again., " message every time I try to login

### ISSUE THREAD

**Issue by epatpol** [42wim/matterircd#135]
I now have this problem whenever I try to login (note that both the mattermost server and matterircd instances are the latest versions). We did change something in our server config though, before we could access our mattermost instance with www.host.org:8065 (8065 was our port) and we recently added a reverse proxy so that we could access it with www.chat.host.org (and this works fine when using a browser). However accessing the instance with matterircd with `login chat.host.org user password` results in the error in the title of this post. 

Here's the log if that can be of any help:

```
time="2017-11-27T15:20:47Z" level=debug msg="<- PRIVMSG mattermost :login chat.HOST.org TEAM USER PASSWORD module=matterircd 
time="2017-11-27T15:20:47Z" level=debug msg="Executed &irc.Message{Prefix:(*irc.Prefix)(nil), Command:"PRIVMSG", Params:[]string{"mattermost"}, Trailing:"login chat.HOST.org TEAM USER PASSWORD EmptyTrailing:false} <nil>" module=matterircd 
time="2017-11-27T15:20:47Z" level=info msg="login as USER (team: TEAM) on chat.HOST.org" module=matterircd 
time="2017-11-27T15:20:47Z" level=error msg="login failed": Invalid or expired session, please login again., "" module=matterircd 
time="2017-11-27T15:20:47Z" level=debug msg="-> :mattermost!mattermost@service PRIVMSG epatpol :": Invalid or expired session, please login again., "" module=matterircd 

```

Thanks!

**Comment by epatpol** [comment]
We ended up fixing it by using localhost as the host  and the old port as the two docker images run on the same machine, and we do not have to expose the port publicly, but I don't know how we could have done it if the instances were on two separate hosts. Feel free to close it if you wish.

**Comment by 42wim** [comment]
hm, if you'd run matterircd on your local (desktop/laptop) machine it should work though. And connect with your irc-client to localhost

**Comment by epatpol** [comment]
That also worked, thanks @42wim !
