### ISSUE TITLE
multiline message split into multiple messages

### ISSUE THREAD

**Issue by shK3Bq4d** [42wim/matterircd#138]
Hello

I can't manage to send multiline strings in one chunk.

My message gets split into multiples messages.

No content is lost but this removes quite a bit of mattermost formatting abilities.

Is the same behavior shared by other or is it my IRC client wrongly configured?

**Comment by Niols** [comment]
Hello,

This is just they way IRC handle messages: they are single-line only.

One could imagine a convention for them ("\n" for instance) and a good configuration of both the IRC client and the matterircd instance to pass multiline strings, but I don't think that matterircd supports that or that it is even planned.

**Comment by 42wim** [comment]
@niols is correct. 
If you really want to do multiline markdown it's better to just use the webinterface.
I'm not planning of adding support for this (PR's are welcome though)
