### ISSUE TITLE
Matterircd segfaults irregularly every few weeks

### ISSUE THREAD

**Issue by TC01** [42wim/matterircd#139]
I'm running matterircd out of the latest docker container (on a Fedora 26 base system, if it's relevant), and every few weeks it crashes and needs to be restarted. The latest traceback I got was:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x5593cf28339c]

goroutine 13 [running]:
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).handleWsActionPost(0xc420170000, 0xc4201ca0c0)
        /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:342 +0x86c
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).handleWsMessage(0xc420170000)
        /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:234 +0x2b5
created by github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).loginToMattermost
        /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:73 +0x3cb
```

This was against mattermost version "4.6.0.4.6.0.f21273f6d5461ccef0bf34f75e26e01e.false".

**Comment by 42wim** [comment]
Hm, I forgot to update 42wim/matterircd:latest on dockerhub
You are better to run the latest stable, could you try 42wim/matterircd:0.16.2 ?
At the moment it seems stable, your crash shouldn't happen there anymore.

I'm going to close the ticket for now, please reopen it if it happens again on 0.16.2 (with a traceback)

Thanks!
