### ISSUE TITLE
Mesages from some channels go to '&messages' channel

### ISSUE THREAD

**Issue by dmrlawson** [42wim/matterircd#140]
matterircd version: 0.16.2 21dd4d1
Client: hexchat 2.12.4

Recently we updated to the latest version of matterircd. Upon reconnecting, my client connected to a channel called '&messages' and some messages from some channels now appear in this new channel and not in the channel they're supposed to be in. 

I've tried reconnecting and leaving and joining affected channels but the issue still occurs.

Is this a known issue? Is there anything I can do to debug it?

**Comment by 42wim** [comment]
Hm that shouldn't happen.

Are you using a matterircd.toml file ?
Are those maybe new created channels (after you logged in) ?

**Comment by dmrlawson** [comment]
I don't think we're using a matterircd.toml file.
The channels definitely existed beforehand.

Messages in '&messages' appear to come from 'user/#channel' if that helps.

**Comment by 42wim** [comment]
Yes, they are supposed to do that if specified in the toml file (the &messages channel exist so that channels you don't want to join on irc get grouped together there)

But if you don't use a config file, it should work like before.

* What mattermost version are you using ?
* Anything special to those user/#channel ? 
* Is your irc client also joined to those #channel you see in &messages ? (so do you see those messages in &messages and in #channel ?)
* Are you a user of multiple teams ?

**Comment by dmrlawson** [comment]
- What mattermost version are you using ?
fmattermost-4.4.3
- Anything special to those user/#channel ?
Not as far as I can tell. When matterircd was first restarted, messages from three different channels appeared in there, but now it's just one.
- Is your irc client also joined to those #channel you see in &messages ? (so do you see those messages in &messages and in #channel ?)
It is joined, but I only see the messages in &messages. Sending a message myself to the channel either via Mattermost or irc results in the messages appearing in the correct #channel
- Are you a user of multiple teams ?
No

**Comment by jemershaw** [comment]
I am having this same issue but it is when messages have attachments with the "fallback" key it sends it into the &messages channel. 
```
curl -d 'payload={"channel": "#test", "username": "bottest", "attachments": [{ "fallback":"test", "text":"blah" }], "icon_emoji": ":ghost:", "icon_url": "" }' $URL
```

Mattermost version: 4.2.0
Matterircd version: 0.16.3

**Comment by 42wim** [comment]
@jemershaw  thanks for the extra hint
I think it's fixed now.

@dmrlawson  or @jemershaw 
Can you rebuild from master to confirm this ? (or do you need binaries)

**Comment by jemershaw** [comment]
@42wim It seemed to fix the fallback issue, need to wait to see if any other messages send into the &message channel.

**Comment by jemershaw** [comment]
I haven't noticed anything going into &messages, so I think you should be able to resolve this.

**Comment by dmrlawson** [comment]
I think we'll need binaries. Sounds like it might be resolved though, thanks for looking into it.

**Comment by 42wim** [comment]
version 0.16.4 is released
