### ISSUE TITLE
crash using slack

### ISSUE THREAD

**Issue by Peter4825** [42wim/matterircd#143]
I'm not sure what the crash caused, but I've only idled on a slack instance, matterircd crashed and gave the following crash message on console:

panic: runtime error: invalid memory address or nil pointer dereference                                                           
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7e36a2]                                                            

goroutine 22 [running]:
github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge/matterclient.(*MMClient).GetChannelId(0x0, 0xc420319ba5, 0x6, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge/matterclient/matterclient.go:417 +0x42
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.CmdJoin(0x9c03e0, 0xc420077520, 0xc420178000, 0xc42032a370, 0xc4200e3df8, 0x411901)
        /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/server_commands.go:118 +0x141
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.commands.Run(0xc420163320, 0x9c03e0, 0xc420077520, 0xc420178000, 0xc42032a370, 0x8, 0xc42005b040)
        /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/commands.go:51 +0x1d3
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*server).handle.func1(0xc420077520, 0xc420178000, 0xc42032a370, 0xc420011c50)
        /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/server.go:368 +0x7a
created by github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*server).handle
        /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/server.go:367 +0x107

**Comment by 42wim** [comment]
This is triggered by a /join command btw, I'll look into it
