### ISSUE TITLE
[slack] Use display_name instead of name, bidirectional

### ISSUE THREAD

**Issue by mlsimpson** [42wim/matterircd#150]
Presently, matterircd displays the users's name instead of display name in the name list, as well as in "@" mentions
`name = myname`, should use `display_name = mycoolnickname`
e.g. on an '@' mention from matterircd to slack:
`@myname`, should use `@mycoolnickname`

When a user on the Slack interface (web and app) "@" mentions another user, matterircd displays the user's id, e.g. `<@W012A3CDE> message`

Reference: https://api.slack.com/methods/users.list

**Comment by mlsimpson** [comment]
@christian-blades-cb

**Comment by mlsimpson** [comment]
FWIW, it seems like the issue lies in `mm-go-irckit/slackuser.go`
I can file the issue there.

**Comment by 42wim** [comment]
closed in mm-go-irckit
