### ISSUE TITLE
Crash: repeated read on failed websocket

### ISSUE THREAD

**Issue by Peter4825** [42wim/matterircd#155]
Using the officially released 0.16.6 binary, I've gotten the following crash:

panic: repeated read on failed websocket connection

goroutine 31 [running]:
github.com/42wim/matterircd/vendor/github.com/gorilla/websocket.(*Conn).NextReader(0xc4204a4f00, 0xffffffffffffffff, 0x0, 0xc420042ec0, 0xc420042ec0, 0x412228)
        /go/src/github.com/42wim/matterircd/vendor/github.com/gorilla/websocket/conn.go:958 +0x35d
github.com/42wim/matterircd/vendor/github.com/gorilla/websocket.(*Conn).ReadJSON(0xc4204a4f00, 0x8daa60, 0xc420407ae0, 0x1, 0x1)                                                                           /go/src/github.com/42wim/matterircd/vendor/github.com/gorilla/websocket/json.go:45 +0x2f
github.com/42wim/matterircd/vendor/github.com/nlopes/slack.(*RTM).receiveIncomingEvent(0xc4200bd900)
        /go/src/github.com/42wim/matterircd/vendor/github.com/nlopes/slack/websocket_managed_conn.go:292 +0xa1
github.com/42wim/matterircd/vendor/github.com/nlopes/slack.(*RTM).handleIncomingEvents(0xc4200bd900, 0xc42047c660)
        /go/src/github.com/42wim/matterircd/vendor/github.com/nlopes/slack/websocket_managed_conn.go:227 +0x2d
created by github.com/42wim/matterircd/vendor/github.com/nlopes/slack.(*RTM).ManageConnection
        /go/src/github.com/42wim/matterircd/vendor/github.com/nlopes/slack/websocket_managed_conn.go:54 +0x24d

I was connected to both a slack and an mattermost instance, so I'm not sure which connection triggered the issue

**Comment by 42wim** [comment]
If you can reproduce this in latest release, please reopen
