### ISSUE TITLE
part leaves channel twice

### ISSUE THREAD

**Issue by Peter4825** [42wim/matterircd#156]
(using v0.16.7-dev, on a slack connection)

If I look at the raw irc log:

```
<< PING matterircd
>> :matterircd PONG matterircd :matterircd
--> lag pong
<< PART #_users
>> :peter!peter@localhost PART #_users
>> :peter!peter@localhost PART #_users
<< PING matterircd
>> :matterircd PONG matterircd :matterircd

```

I've issued a part command to leave a channel.  As the state of channels is managed by the ircd, the ircd is the only one who can say wether I left a channel or not.  Therefore it is normal that the ircd replies with the message that I left  the channel.

The issue here is that matterircd - for some reason - sends this message twice, which is incorrect.

**Comment by 42wim** [comment]
Can not reproduce this myself. Can you repeat this multiple times ?

**Comment by Peter4825** [comment]
Yes, it does this every time.  Did you try to reproduce on a slack connection?
