### ISSUE TITLE
[slack] Spacing between sentences is greater when sending messages from IRC

### ISSUE THREAD

**Issue by mlsimpson** [42wim/matterircd#158]
Hard to describe, so here's a screenshot:

![image](https://user-images.githubusercontent.com/668862/37560787-4d16f2ee-2a15-11e8-8187-a17d5cbd2657.png)

**Comment by 42wim** [comment]
Yes, that's a slack bug, can't fix this. (shows empty attachments as an extra line)
Probably related to https://github.com/42wim/matterbridge/issues/264 where they seem to have fixed it for the android app.

Please open the issue with slack.

**Comment by mlsimpson** [comment]
@42wim No problem, thank you very much! Genuinely appreciate you working so hard on matterircd and mm-go-irckit! I owe you a beer or 8 👍

**Comment by 42wim** [comment]
Feel free to keep opening issues, I can't test everything so your reports help a lot to make this better :)
