### ISSUE TITLE
/whois output wrong

### ISSUE THREAD

**Issue by yuvipanda** [42wim/matterircd#16]
`yuvipanda signed on at December 31, 1969 at 5:00:00 PM MST and has been idle for 8 minutes, 14 seconds` 

Seems the time value is the 0 value with TZ offset, and idle time is also wonky.

**Comment by 42wim** [comment]
The idle time is fixed on master. 
But the sign-on time is set to 0, because I don't have a sign-on time.

**Comment by yuvipanda** [comment]
Is 'sign on time' something we can get the mattermost API to provide?

On Sat, Nov 28, 2015 at 2:35 PM, @42wim <notifications@github.com> wrote:

> The idle time is fixed on master.
> But the sign-on time is set to 0, because I don't have a sign-on time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/42wim/matterircd/issues/16#issuecomment-160342944>.
>



-- 
Yuvi Panda T
http://yuvi.in/blog

**Comment by 42wim** [comment]
You can find all the user fields on https://github.com/mattermost/platform/blob/master/model/user.go#L29-L54

LastActivityAt is used for the idle time, but there is no sign on time, the closest is the creation time, but that's not exposed in the API

**Comment by 42wim** [comment]
closing for now, partly fixed, no solution for the sign-on time
