### ISSUE TITLE
allow restriction of matterircd to specific slack servers

### ISSUE THREAD

**Issue by danhimalplanet** [42wim/matterircd#161]
Please allow the ability, in the matterircd.toml file, to restrict matterircd to a list of slack servers, when interacting with slack

I suggest something like

RestrictSlack = "chat.slack.com foo.slack.com"

**Comment by 42wim** [comment]
This is now available in master. Soon to be release 0.17.0
There is now a separate setting for slack using `[slack]`

```
[slack]
#only allow connection to specific slack sites. (eg for myslack.slack.com just specify myslack)
#As we only connect using tokens, this will first do a ccnnection to see what team the token is from. If this
#team isn't in the Restrict list, the user will be disconnected.
#Array, default empty 
Restrict = ["myslack"]
```
See https://github.com/42wim/matterircd/blob/master/matterircd.toml.example for more info
