### ISSUE TITLE
Add ability to set away status for mattermost

### ISSUE THREAD

**Issue by CountMurphy** [42wim/matterircd#165]
Not sure if this is possible or not. I'm hoping to get the ability to set my status as away over irc. The problem we discovered is that mattermost will not send alerts over the mobile app if your status is online. When logged in over irc, the status is always online (far as I know).  

If I type /away test in irc, I still show as online in mattermost

 If this is already possible, or cant be done, feel free to close out the ticket.

**Comment by 42wim** [comment]
As you can see it was fixed and closed in a commit (https://github.com/42wim/mm-go-irckit/commit/6077adc1514369735c9ab57bb8db89df56d27fda)

The latest release 0.16.9 has the fix and makes /away work

**Comment by CountMurphy** [comment]
I must be blind as I didn't see that. Thank you adding this!

**Comment by 42wim** [comment]
feel free to reopen/comment if it still doesn't work :)

**Comment by furai** [comment]
Hey, I'm experiencing issues with setting my away status from IRC. It doesn't seem to work. Could you have a look into it? I'm on mattericd v19.2
