### ISSUE TITLE
Add suffix `[<nick>]` to messages containing configured highlight words

### ISSUE THREAD

**Issue by repomaa** [42wim/matterircd#168]
I'd like to only configure highlight words/phrases once so relaying them to my irc client by adding my nickname to the message would be an easy way to have the same highlights in every client.

**Comment by 42wim** [comment]
I'm not sure if that's something a server should do, seems more client-side configuration.
An example for irssi - https://quadpoint.org/articles/irssi/#hilight-window

**Comment by keeperofdakeys** [comment]
This feature would be good for @channel and @all mentions, where you don't have your username in the message already.

**Comment by 42wim** [comment]
Implemented in master, it'll show `(mention: yournick)` on messages containing your highlight words
