### ISSUE TITLE
Connection lost to matterircd

### ISSUE THREAD

**Issue by zetaab** [42wim/matterircd#169]
We are all the time seeing messages like this:

15:26:53 -!- Irssi: Connection lost to irc.mattermost.xx.com

I have tried to debug this and it seems that matterircd does not have PING implemented? Or if it is, where I can configure interval between PING messages?

https://tools.ietf.org/html/rfc2812#section-3.7.2

> Servers send a PING
   message at regular intervals if no other activity detected coming
   from a connection.  If a connection fails to respond to a PING
   message within a set amount of time, that connection is closed.  A
   PING message MAY be sent even if the connection is active.

**Comment by zetaab** [comment]
maybe related to https://github.com/42wim/matterircd/issues/40 if these ping messages are not sent tcp connections are closed after x seconds

**Comment by 42wim** [comment]
Server doesn't send a ping, but response on client pings.

irssi sends PINGs by it self, use `/SET lag_check_time <time>` to set the interval between ping messages

**Comment by zetaab** [comment]
`/SET lag_check_time 20s` seems working. Thanks!
