### ISSUE TITLE
[RFC] How to handle messages from system 

### ISSUE THREAD

**Issue by evelikov** [42wim/matterircd#175]
Say `John` adds `Jane` to channel `random`.

Currently, this becomes a message like:
`John: Jane added to the channel by John.`

As it seems a bit odd, here are some alternatives:
 - Add "system" user, and 
`System: Jane added to the channel by John.`
 - Tweak the whole thing to an action
`John added Jane to the channel.`

Disclaimer:
I haven't looked if it's possible to implement either suggestion.

**Comment by Ppjet6** [comment]
I did remember something similar for IRC, and indeed it seems that inspircd has an operator module for this: https://wiki.inspircd.org/Modules/sajoin

And apparently this translates to a normal join from the user.

**Comment by 42wim** [comment]
@evelikov This is on slack ? or on mattermost ?

**Comment by Ppjet6** [comment]
On 2018/05/02, Wim wrote:
> @evelikov This is on slack ? or on mattermost ?

This is on mattermost! (replying for him)

-- 
Maxime “pep” Buquet

**Comment by Ppjet6** [comment]
On 2018/05/02, Wim wrote:
> Fixed in master (and 0.17.3 release)

Thanks a lot!

-- 
Maxime “pep” Buquet
