### ISSUE TITLE
replace the content of private messages with "[REDACTED]" in logs when in debug mode

### ISSUE THREAD

**Issue by danhimalplanet** [42wim/matterircd#177]
please replace the content of private messages with "[REDACTED]" in logs when in debug mode

**Comment by 42wim** [comment]
Well, not so sure about that.
`-debug` should only be run when necessary, and the private messages could contain the issue you're trying to debug

**Comment by 42wim** [comment]
I've added a  debugmode field in the ircd banner, so that users know the server is running in debugmode
`-!- matterircd 0.17.4-dev o o debugmode true`
