### ISSUE TITLE
matterircd run time error

### ISSUE THREAD

**Issue by danhimalplanet** [42wim/matterircd#179]
matterircd crashed

Running version 0.17.4-dev 7f9e17e

stack trace attached

[matterircd_error Running version 0.17.4-dev 7f9e17e.txt](https://github.com/42wim/matterircd/files/2002731/matterircd_error.Running.version.0.17.4-dev.7f9e17e.txt)

**Comment by 42wim** [comment]
Hi thanks for reporting.
I've upgraded the websocket library in master, it contains a lot of bugfixes and hopefully also fixes your issue.

If this is not the case, feel free to reopen.
