### ISSUE TITLE
[RFC] Alternative handling of MM threads

### ISSUE THREAD

**Issue by evelikov** [42wim/matterircd#180]
Here are some ideas that came to mind, while looking at the current MM threads:

- a new channel is created for each thread - naming scheme can be based on original channel name, the date or other
- any participants of the discussion are 'automatically' added (alike the "system added foo in bar")
- manually joining (or joining at a later stage) replays the whole log
- the "(re:....)" in the original channel is replaced with the unique channel name for the thread

Disclaimer: I haven't checked if all of the above is possible to implement.

**Comment by Ppjet6** [comment]
That actually sounds nice, and would allow us IRC users to participate in threads, that we weren't able to do until now. That would also help for clarity, I'm not really fond of the "(re: ...") construct tbh.

OTOH, that would also make the number of joined channel increase considerably though, and then getting rid of these would be quite a daunting task.

**Comment by evelikov** [comment]
@Ppjet6 I do agree that managing the multiple channels (threads really) will be annoying. It seems better than the current situation though. Now we have:
- partial discussion, or
- really long and often off topic "(re: original message it thread)" message

@42wim are you in favour or against the idea? Worst case scenario we can revert to the original behaviour. Or perhaps keep both and let the user decide with a config toggle?

**Comment by 42wim** [comment]
@evelikov I'm not against it, but I fear like @Ppjet6 mentions that you'll be joining a lot of channels.
And a config toggle would definitely be necessary, by default disabled.

If you're planning to do a PR and need any assistance, feel free to ask for help.

**Comment by evelikov** [comment]
I have no plan to look at this, since I'm no longer using matterircd, Feel free to leave open or close.
