### ISSUE TITLE
Feature request: do not have one team as main team

### ISSUE THREAD

**Issue by Peter4825** [42wim/matterircd#182]
At this moment, when logging in to matterircd on a mattermost server, you need to provide your username/password and your teamname

The channels for that team become #channelname while the channels of other teams become  #teamname/channelname.

I'd like to request to (optionally) drop the teamname, and have all channels named #teamname/channelname, so you are very clear on which team you are talking.

**Comment by 42wim** [comment]
Fixed in master, set `PrefixMainTeam = true` in matterircd.toml under `[mattermost]` settings
