### ISSUE TITLE
/me incorrectly reported as ACTION on 1:1 discussions

### ISSUE THREAD

**Issue by Ppjet6** [42wim/matterircd#185]
matterircd: around 9b09123 I think
mattermost: 4.8, a bit old sorry

## Steps to reproduce

- Start a direct message with a webui user
- Send `/me foo`

## What happens

It is displayed as `ACTION foo` on the mattermost side.

## What is expected

It appears just like `/me` actions in other channels, i.e., bold (yay Mattermost..).

I assume in groupchat it's translated by mattermost? So maybe this is mattermost failing to translate it here? I haven't got time to debug atm sorry, I might have a look later.

**Comment by 42wim** [comment]
Fixed by PR from @evelikov
