### ISSUE TITLE
incorrect routing of self-messages in slack direct chats

### ISSUE THREAD

**Issue by oliverralbertini** [42wim/matterircd#190]
The following happens when connecting to slack with my irc client (weechat) via the matterircd gateway, which is owned by someone else.

In a direct chat with another person, self-messages (messages I send from the slack app or browser clients, not irc client) are routed to a direct chat with myself. This breaks the continuity of the conversation view in the irc client, as the messages I send from slack clients don't appear in the direct chat with the other person.

Also, the name of the direct chat with myself does not correspond with my slack handle, but rather another string that I am guessing comes from the part of my email address before '@'. Apparently, other users of the direct gateway always see my handle as this other string (not my slack handle). I have tried setting Full Name and Display Name as my desired slack handle in slack preferences, but without any success.

**Comment by ossih** [comment]
There is #203 to fix problem where messages go to yourself.

To fix you handle, you should set your username.
Go to **Profile & account** -> **Account settings** (click gear) -> **Username** is at bottom. Click expand, change your username and save.

**Comment by 42wim** [comment]
If still an issue in current release (v0.19.0) please reopen.
