### ISSUE TITLE
Incompatible with Mattermost 5.0 Stable

### ISSUE THREAD

**Issue by miukumac** [42wim/matterircd#191]
Using the master branch docker trying to login to our recently updated server results in:
unsupported mattermost version: 5.0.0.5.0.0.84a4335b929723971799748773d1ca8f.false

Unfortunately it's not possible for us to rollback to previous version so this prevents using the gateway currently.

**Comment by 42wim** [comment]
I've done a quick test with mattermost 5.x and everything seems to work.
Could you test from master ?

**Comment by 42wim** [comment]
Got feedback from other people that it works.
Released v0.18.1
If you still have issues feel free to reopen
