### ISSUE TITLE
Direct group messages aren't correctly handled

### ISSUE THREAD

**Issue by Ppjet6** [42wim/matterircd#193]
Running matterircd 9b09123 and mattermost 4.8

There seems to be lots of issues with this kind of direct messages, I wonder if there is support even for them. I'll try to outline a few issues. I can split this if required.

## Steps to reproduce

- Via the webui, Direct Messages (+) > Select at least 2 users > Go
- Send a message, via the webui
- Get a participant to send a message to that group
- Send a message via the bridge to the group

## What happens

First issue, when I create the direct message tab, nothing happens on my IRC client.

Second, when I send the message to that tab via the webui, I get two windows created on my IRC client, one channel with all participants, and one private conversation with the channelid. Every subsequent messages sent by participants will appear as private conversations between me and that participant.
EDIT: when __I__ send a message via the webui to that group, on the IRC side it appears in the channel under my nick, which is expected.

Third, from the IRC client, when I send a message in the newly created channel, it appears as:
```
16:27 < pep:7ntbwhjycjffmypj1jjreidpbe> foo
```

## What I expect

I would expect these "direct group messages" to behave like normal channels, seen from the IRC side. I have no knowledge of the MM protocol and how that's handled though.

**Comment by 42wim** [comment]
Please update to the latest matterircd release, I think the issue you mention should be fixed in 0.18.1
See eg #178 
If you still have this or other issues on 0.18.1 (or .2 release very soon), please reopen or create another issue

**Comment by Ppjet6** [comment]
I checked and we are running 0.18.2-dev, so I believe this fix is in.
