### ISSUE TITLE
Own messages not reflected on the bridge when sent from mattermost

### ISSUE THREAD

**Issue by Ppjet6** [42wim/matterircd#195]
## Steps to reproduce

- Start a Direct Message with somebody, or continue a previously started DM
- Send a message to that DM from the webui

## What happens

My own messages are not reflected on the bridge. I only get the other participant's messages.

## What I expect

See all messages that are sent in the discussion.

**Comment by 42wim** [comment]
That's not possible afaik, you can't spoof a private message from yourself in a query with another user.
Also annotated in the code: https://github.com/42wim/mm-go-irckit/blob/master/mmuser.go#L334

**Comment by Ppjet6** [comment]
On 2018/06/27, Wim wrote:
> That's not possible afaik, you can't spoof a private message from yourself in a query with another user.
> Also annotated in the code: https://github.com/42wim/mm-go-irckit/blob/master/mmuser.go#L334

I am not sure I understand what spoof means in this context, nor the
comment in the code. I'm probably missing a bit of context.

-- 
Maxime “pep” Buquet

**Comment by 42wim** [comment]
See https://tools.ietf.org/html/rfc1459#section-4.4.1 for more information about how private messages to users work.

The only possible workaround for this is using a separate IRC channel for a private message instead of using IRC queries

**Comment by 42wim** [comment]
@Ppjet6 
Apparently newer clients do support this kind of spoofing and I've added support for this in master.
You need a recent irssi to see it working (I've tested with irssi 1.1.1)
