### ISSUE TITLE
panic: repeated read on failed websocket connection

### ISSUE THREAD

**Issue by Peter4825** [42wim/matterircd#196]
After running 0.18.1 (official release) for 6 days without any issues, I've had 3 crashes today.  I'm connected to several slack instances, and one mattermost, I think the issues are related to the mattermost instance tough...

time="2018-06-27T09:14:24+02:00" level=debug msg="Executed &irc.Message{Prefix:(*irc.Prefix)(nil), Command:\"WHO\", Params:[]string{\"#mm/off-topic\"}, Trailing:\"\", EmptyTrailing:false} <nil>" module=matterircd
panic: repeated read on failed websocket connection

goroutine 542683 [running]:
github.com/42wim/matterircd/vendor/github.com/gorilla/websocket.(*Conn).NextReader(0xc420544c80, 0xffffffffffffffff, 0x0, 0xc42012fec0, 0xc42012fec0, 0x410468)
        /go/src/github.com/42wim/matterircd/vendor/github.com/gorilla/websocket/conn.go:959 +0x35d
github.com/42wim/matterircd/vendor/github.com/gorilla/websocket.(*Conn).ReadJSON(0xc420544c80, 0x8ddc60, 0xc4203b9140, 0x1, 0x1)
        /go/src/github.com/42wim/matterircd/vendor/github.com/gorilla/websocket/json.go:50 +0x2f
github.com/42wim/matterircd/vendor/github.com/nlopes/slack.(*RTM).receiveIncomingEvent(0xc4200a8c60)
        /go/src/github.com/42wim/matterircd/vendor/github.com/nlopes/slack/websocket_managed_conn.go:292 +0xa1
github.com/42wim/matterircd/vendor/github.com/nlopes/slack.(*RTM).handleIncomingEvents(0xc4200a8c60, 0xc420687ce0)
        /go/src/github.com/42wim/matterircd/vendor/github.com/nlopes/slack/websocket_managed_conn.go:227 +0x2d
created by github.com/42wim/matterircd/vendor/github.com/nlopes/slack.(*RTM).ManageConnection
        /go/src/github.com/42wim/matterircd/vendor/github.com/nlopes/slack/websocket_managed_conn.go:54 +0x24d

time="2018-06-27T11:21:09+02:00" level=debug msg="<- PING matterircd" module=matterircd
time="2018-06-27T11:21:09+02:00" level=debug msg="-> :matterircd PONG matterircd :matterircd" module=matterircd
time="2018-06-27T11:21:09+02:00" level=debug msg="Executed &irc.Message{Prefix:(*irc.Prefix)(nil), Command:\"PING\", Params:[]string{\"matterircd\"}, Trailing:\"matterircd\", EmptyTrailing:false} <nil>" module=matterircd
panic: repeated read on failed websocket connection

goroutine 462 [running]:
github.com/42wim/matterircd/vendor/github.com/gorilla/websocket.(*Conn).NextReader(0xc4206a88c0, 0xffffffffffffffff, 0x0, 0xc420442ec0, 0xc420442ec0, 0x410468)
        /go/src/github.com/42wim/matterircd/vendor/github.com/gorilla/websocket/conn.go:959 +0x35d
github.com/42wim/matterircd/vendor/github.com/gorilla/websocket.(*Conn).ReadJSON(0xc4206a88c0, 0x8ddc60, 0xc4203c4a40, 0x1, 0x1)
        /go/src/github.com/42wim/matterircd/vendor/github.com/gorilla/websocket/json.go:50 +0x2f
github.com/42wim/matterircd/vendor/github.com/nlopes/slack.(*RTM).receiveIncomingEvent(0xc4200b0160)
        /go/src/github.com/42wim/matterircd/vendor/github.com/nlopes/slack/websocket_managed_conn.go:292 +0xa1
github.com/42wim/matterircd/vendor/github.com/nlopes/slack.(*RTM).handleIncomingEvents(0xc4200b0160, 0xc4201d2840)
        /go/src/github.com/42wim/matterircd/vendor/github.com/nlopes/slack/websocket_managed_conn.go:227 +0x2d
created by github.com/42wim/matterircd/vendor/github.com/nlopes/slack.(*RTM).ManageConnection
        /go/src/github.com/42wim/matterircd/vendor/github.com/nlopes/slack/websocket_managed_conn.go:54 +0x24d

time="2018-06-27T14:05:09+02:00" level=debug msg="Executed &irc.Message{Prefix:(*irc.Prefix)(nil), Command:\"WHO\", Params:[]string{\"&users\"}, Trailing:\"\", EmptyTrailing:false} <nil>" module=matterircd
panic: repeated read on failed websocket connection

goroutine 120 [running]:
github.com/42wim/matterircd/vendor/github.com/gorilla/websocket.(*Conn).NextReader(0xc420491cc0, 0xffffffffffffffff, 0x0, 0xc4201c5ec0, 0xc4201c5ec0, 0x410468)
        /go/src/github.com/42wim/matterircd/vendor/github.com/gorilla/websocket/conn.go:959 +0x35d
github.com/42wim/matterircd/vendor/github.com/gorilla/websocket.(*Conn).ReadJSON(0xc420491cc0, 0x8ddc60, 0xc4203873c0, 0x1, 0x1)
        /go/src/github.com/42wim/matterircd/vendor/github.com/gorilla/websocket/json.go:50 +0x2f
github.com/42wim/matterircd/vendor/github.com/nlopes/slack.(*RTM).receiveIncomingEvent(0xc420398000)
        /go/src/github.com/42wim/matterircd/vendor/github.com/nlopes/slack/websocket_managed_conn.go:292 +0xa1
github.com/42wim/matterircd/vendor/github.com/nlopes/slack.(*RTM).handleIncomingEvents(0xc420398000, 0xc42005e300)
        /go/src/github.com/42wim/matterircd/vendor/github.com/nlopes/slack/websocket_managed_conn.go:227 +0x2d
created by github.com/42wim/matterircd/vendor/github.com/nlopes/slack.(*RTM).ManageConnection
        /go/src/github.com/42wim/matterircd/vendor/github.com/nlopes/slack/websocket_managed_conn.go:54 +0x24d

**Comment by 42wim** [comment]
related to https://github.com/42wim/matterircd/issues/189 which is seemingly fixed in master by updated slack libs.

Please try master and if still an issue, reopen.
