### ISSUE TITLE
Extra newline at the end of sent Slack messages

### ISSUE THREAD

**Issue by uchwings** [42wim/matterircd#197]
When I send a Slack message using matterircd, other users see an extra newline at its end.

On the web client, this shows up as a bit of extra space between lines compared to other users. In clients like the weechat slack plugin, it shows up as an extra newline proper at the end of each message.

**Comment by dm8tbr** [comment]
Last time I briefly took a look at this it seemed to be an empty "attachment" payload for every message.
I guess the Slack side of things isn't getting that much use, except for us few who found this and use it as a replacement for the gone gateway.

**Comment by 42wim** [comment]
Yes, this is "almost" empty attachment is necessary so that messages don't get looped.
This is used to detect the messages we've sent ourselves.

See #158

**Comment by uchwings** [comment]
Thanks for the explanation, but I don't understand entirely.

Could you explain why it's necessary to determine "if the message originated from matterbridge, or from another bot" (42wim/matterbridge/#262#issuecomment-330369260), and how empty attachments are used to achieve that?

**Comment by 42wim** [comment]
It's an "almost" empty attachment. See also https://github.com/42wim/matterbridge/issues/219 and https://github.com/42wim/matterbridge/commit/dc8743e0c0f40d6f260c346025af29523087a9b5#diff-9cf086abe9322e8e54948ce48e302166R162

I'm adding a callback-id `matterbridge` to every message.  (this has more recently changed to a more unique callback-id though to support multiple matterircd users)

**Comment by 42wim** [comment]
Going to close this as, it's not something I can fix.

**Comment by uchwings** [comment]
Could you explain why it's necessary to add this callback-id attachment to every message? What makes it impossible to recognize bridge-sent messages being echoed based on content?

**Comment by 42wim** [comment]
Without callback: You on matterircd send a message. Message gets to slack. Slack echos message back to every client. You see the message double on matterircd.
With callback: You on matterircd send a message. Message gets to slack. Slack echos message back to every client. Matterircd sees callback message and doesn't show it again
