### ISSUE TITLE
allow connecting to a mattermost instance without tls and specify a port

### ISSUE THREAD

**Issue by danhimalplanet** [42wim/matterircd#199]
in matterbridge you can hook up to mattermost 

- without tls with "NoTLS"

- to a different port other than 443 by specifying the port in the name of the mattermost server, for instance "Server=mattermost:8000"

please allow this in matterircd

**Comment by 42wim** [comment]
It already does, use `matterircd -mminsecure -mmserver mattermost:8000`
```
 -mminsecure
        use http connection to mattermost
  -mmserver string
        specify default mattermost server/instance
```

or in the matterircd.toml

```
[mattermost]
#specify default mattermost server/instance (default "")
DefaultServer = "chat.mycompany.com:1234"

#use http connection to mattermost (default false)
Insecure = true
```

**Comment by danhimalplanet** [comment]
I would like to be able to do it while authenticating when messaging "slack"... but your solution works too.

thanks.
