### ISSUE TITLE
-mminsecure flag is always overridden

### ISSUE THREAD

**Issue by rmzg** [42wim/matterircd#200]
Line 60 from vendor/github.com/42wim/mm-go-irckit/mmuser.go:
```
 u.MmInfo.Cfg.Insecure = cfg.MattermostSettings.Insecure
```

Doesn't that always override the Insecure setting configured by the command line flag?

**Comment by dromer** [comment]
Didn't look at the code, but with latest release using ```-mminsecure``` the login with the bot still tries to connect over https

**Comment by 42wim** [comment]
Fixed in master
