### ISSUE TITLE
Messages to private chats from other applications go to wrong user

### ISSUE THREAD

**Issue by Aketzu** [42wim/matterircd#203]
If I use some other Slack client to post text/images to a private chat the resulting message will be sent "to me" "by myself" whereas it should go to same private chat as spoken by myself.

For example if I speak to slackbot with web-Slack I get
```
DEBU[2018-07-25T23:16:52+03:00] -> :Aketzu!Aketzu@Aketzu PRIVMSG Aketzu :test  module=matterircd
DEBU[2018-07-25T23:16:53+03:00] -> :slackbot!slackbot@slackbot PRIVMSG Aketzu :I searched for that on our Help Center. Perhaps these articles will help:   module=matterircd
```

whereas it should produce
```
DEBU[2018-07-25T23:16:52+03:00] -> :Aketzu!akolehma@localhost PRIVMSG slackbot :test  module=matterircd
DEBU[2018-07-25T23:16:53+03:00] -> :slackbot!slackbot@slackbot PRIVMSG Aketzu :I searched for that on our Help Center. Perhaps these articles will help:   module=matterircd
```

**Comment by ossih** [comment]
I have been testing these changes and can confirm they work as intended. My own messages appear to same chat and not from myself to myself.

**Comment by Aketzu** [comment]
Seems to be fixed by 3b3a7f580fa6dd7a81f3c05c6c223ff2f156174c with different implementation

**Comment by Aketzu** [comment]
Now it seems to send
```
:Aketzu!Aketzu@localhost PRIVMSG Aketzu
```
so halfway there :)

**Comment by Aketzu** [comment]
Current master seems to work when username == nick. In my case I use username akolehma and nick Aketzu so it fails.

For me relevant fix is to change `u.sinfo.User.ID == ghost.User` comparison to `u.Nick == ghost.Nick`

**Comment by 42wim** [comment]
Hey @Aketzu, thanks for the report and fix! 👍 
Feel free to open PR's in the future :)
