### ISSUE TITLE
image upload links from slack to irc not working

### ISSUE THREAD

**Issue by danhimalplanet** [42wim/matterircd#204]
When uploading an image into web ui or Slack desktop client, I don't see a link for the image in IRC.

I see the same problem with logging into matterircd with a username/password, a xoxs- token, and a xoxp- token

matterircd version 0.18.2-dev 
[matterircd-0.18.2-dev.log](https://github.com/42wim/matterircd/files/2239052/matterircd-0.18.2-dev.log)

**Comment by 42wim** [comment]
Thanks for reporting.
This has been fixed in master.
