### ISSUE TITLE
Slack image attachments ignored

### ISSUE THREAD

**Issue by liskin** [42wim/matterircd#206]
Whenever someone sends a message with image attachment, only the text is delivered to IRC. I'd expect a link to the image as well (that's what slack's gateway did before they shut it down).

Compare: 
![2018-08-28-091439_1920x1080_scrot](https://user-images.githubusercontent.com/300342/44706791-12680c00-aaa3-11e8-8351-686a35e1dc22.png)
![2018-08-28-091447_1920x1080_scrot](https://user-images.githubusercontent.com/300342/44706795-16942980-aaa3-11e8-88a4-97e174f93ec6.png)

**Comment by 42wim** [comment]
Slack API has been changed.
This has been resolved in master for a while and seems stable, so I've just released a v0.18.3 and the binaries that fixes your issue.

**Comment by liskin** [comment]
Oh, right, sorry for not trying master. :-(

**Comment by liskin** [comment]
And thanks. :-)
