### ISSUE TITLE
Invalid or expired session, please login again

### ISSUE THREAD

**Issue by runfalk** [42wim/matterircd#208]
I use a personal access token with matterircd. I have configured my bouncer (ZNC) to send it automatically when connecting:

`PRIVMSG mattermost :login <team> runfalk MMAUTHTOKEN=<token>`

This works great. It reconnects properly and everything. But today I got the message `msg: <redacted> could not be send: : Invalid or expired session, please login again.,` from the mattermost user. Reconnecting to the server (to trigger a new login) fixed the issue.

I have also seen this in the log file:

```
matterircd[13020]: time="2018-10-03T07:39:39+02:00" level=error msg="ChannelView update for bctpaanrrtyy7c7pgda1nom4fh failed: : Invalid or expired session, please login again., " prefix=matterclient
matterircd[13020]: time="2018-10-03T07:39:39+02:00" level=error msg="ChannelView update for w9psunnfrpg63gifu1pcqxc31h failed: : Invalid or expired session, please login again., " prefix=matterclient
matterircd[13020]: time="2018-10-03T07:40:39+02:00" level=error msg="ChannelView update for w9psunnfrpg63gifu1pcqxc31h failed: : Invalid or expired session, please login again., " prefix=matterclient
matterircd[13020]: time="2018-10-03T07:40:39+02:00" level=error msg="ChannelView update for bctpaanrrtyy7c7pgda1nom4fh failed: : Invalid or expired session, please login again., " prefix=matterclient
matterircd[13020]: time="2018-10-03T07:41:39+02:00" level=error msg="ChannelView update for bctpaanrrtyy7c7pgda1nom4fh failed: : Invalid or expired session, please login again., " prefix=matterclient
matterircd[13020]: time="2018-10-03T07:41:39+02:00" level=error msg="ChannelView update for w9psunnfrpg63gifu1pcqxc31h failed: : Invalid or expired session, please login again., " prefix=matterclient
```

I am using `Mattermost Version: 5.2.1` with GitLab authentication only.

**Comment by 42wim** [comment]
That's strange, looks like a mattermost issue because personal tokens aren't supposed to expire.
Can you have a look into the mattermost console logs if it show some errors on the mattermost side ?

**Comment by runfalk** [comment]
It seems like mattermost clears most logs when restarting, and I haven't seen the issue since. This is the only message that's nearby in time (there seems to be a separate log file for errors):

```javascript
{
    "level":"error",
    "ts":1538545432.6637204,  // 2018-10-03T07:43:52+02:00
    "caller":"web/context.go:60",
    "msg":"Invalid or missing channel_id parameter in request URL",
    "path":"/api/v4/channels/members",
    "request_id":"5ramcqo6ifdwfkpmuqz13uccgy",
    "ip_addr":"158.174.127.100",
    "user_id":"3k3uko3sc78ebgajmofkitdjbh",
    "method":"GET",
    "err_where":"Context",
    "http_code":400,
    "err_details":""
}
```

I'll keep

**Comment by strigazi** [comment]
I get the same message but "Invalid or expired session, please login again." on the server side, our mattermost admin told me that matterircd sends the token  as a cookie and not as a header.
`model.NewAppError("ServeHTTP", "api.context.session_expired.app_error", nil, "token="+token+" Appears to be a CSRF attempt", http.StatusUnauthorized)`

**Comment by 42wim** [comment]
This just got fixed in matterbridge and I've updated matterircd with the new code. (and updated dockerhub image)

If you recompile matterircd you can use the personal tokens, you'll have to use `token=yourtoken` instead of `MMAUTHTOKEN=yourtoken` as the `password` when logging in.

Feel free to reopen if this is still an issue

**Comment by strigazi** [comment]
worked for me! thanks
