### ISSUE TITLE
Indirect dependency to "code.google.com/p/log4go"

### ISSUE THREAD

**Issue by wingrime** [42wim/matterircd#21]
1) Thats mercurial repo (I need to install it)
2)  code.google will be shut down soon

Consider this facts, please remove such dependency. I not sure witch package need it but I sure there must be right fork on github.

**Comment by 42wim** [comment]
Hi, that dependency is because mattermost imports it. 
This is not something I can fix, could you open this issue there? 
Thanks!

**Comment by wingrime** [comment]
OK I will try If I get some free time
