### ISSUE TITLE
support slack two-factor authentication

### ISSUE THREAD

**Issue by paretje** [42wim/matterircd#212]
I'm a member of a Slack workspace requiring two-factor authentication. When I send `login <team> <login> <pass>` to slack, I get the reply `missing_pin_sms`. I do get the PIN code at the same time.

**Comment by 42wim** [comment]
Google gives me no hits for `missing_pin_sms` except for this issue :(
You could try the work around here to get a token: https://twitter.com/42wim/status/1005200618808586240

**Comment by paretje** [comment]
I just tried again using the token to login, and it does work. It failed because I was using the same IRC user as I use for mattermost.

**Comment by 42wim** [comment]
oh great, so we can close this :)
