### ISSUE TITLE
\t+number gets lost (tab, tabulator)

### ISSUE THREAD

**Issue by faljse** [42wim/matterircd#222]
If an irc users posts a message containing tabulator followed by a number, the number gets lost
e.g.:
`\t1.2` web users receive `.2`
`\t10.2` web users receive `.2`
Doesnt work wit characters:
`\tA.2` web users receive `A.2`

matterircd 0.18.4
mattermost 5.5

**Comment by leecher1337** [comment]
May be related to this improper fix: 
https://github.com/42wim/matterircd/issues/149

**Comment by 42wim** [comment]
This got fixed a while ago in master in https://github.com/42wim/matterircd/commit/7322ae987a3431f2cc76c669f3d5a1f7d7cc923b#diff-dbb395560be9f414d23d9a6290d11eaaR432

Can you try master?

**Comment by 42wim** [comment]
Also just release a v0.19.0 which you can use, if still an issue, please reopen.
