### ISSUE TITLE
matterircd goes into zombie mode

### ISSUE THREAD

**Issue by Peter4825** [42wim/matterircd#224]
this is quite an old issue which I've alread mentioned on irc, but to make sure it is tracked, here is the github issue:

Sometimes, the connection between slack (and perhaps mattermost) and matterircd breaks.   As the connection between the irc client and matterircd are not influenced by this, you are not getting any feedback that something is wrong as an enduser, it's just that if you talk to people, they don't see it, and if they talk to you, you don't see it.

This on it's own is rather severe, you'd rather have something that clearly breaks so you can do something about it instead of things going wrong silently as you end up not knowing if people were talking to you for perhaps days.

Would it be possible to make matterircd do some kind of ping to the server, in an unrelated control thread, and boot the irc user if the connection is not there and cannot be re-established? At least I'd start to trust matterircd more in this case - I'd still get disconnected but at least I'd know that something went wrong.

Regardless, I have logs of the last time it went wrong, contact me on irc if you need any info. (tested on latest 0.19.0)

**Comment by 42wim** [comment]
A lot of changes have happened, slack libraries updated and refactors.
If this still happens on current master, please reopen
