### ISSUE TITLE
Cannot join channels

### ISSUE THREAD

**Issue by jreinert** [42wim/matterircd#227]
I'm trying to set up matterircd in a way that it doesn't autojoin any channels so i set `JoinInclude = ["&messages"]`. It works in a way: no channels except for `&messages` and `&users` are created... I can't join any channels after that though. I want to be able to use my irc client's autojoin mechanics and get the rest of the messages to `&messages`. I just get the invite-only response from the server "Cannot join channel (+i)".

Version: 0.18.4

**Comment by Necrathex** [comment]
Also after closing the channel in the irc client it's not possible to rejoin it (even though the user is in the mattermost channel).

**Comment by setpill** [comment]
Also having this problem, and after shuffling around [this debug statement](https://github.com/42wim/matterircd/blob/8a6752884b6a02df4e40ed510c34e446078ffd3c/mm-go-irckit/server_commands.go#L167) (it didn't do any good being called AFTER the error check broke the code flow), I got the following information:

`Join channel off-topic, id , err: : Invalid or missing channel_id parameter in request URL,   module=matterircd`

So the channel isn't actually `+i`.

**Comment by setpill** [comment]
The issue turned out to be a missing teamId; ie. trying to `/join #off-topic` rather than `/join #teamname/off-topic`. The bug (in our case) seems to be that `CmdJoin` does not respect the `DefaultTeam` setting.

**Comment by setpill** [comment]
@jreinert can you confirm whether adding the team name and a slash before the channel in your join command fixes the problem for you? If so, the above PR should properly resolve this issue.

**Comment by setpill** [comment]
Recent commits to master have fixed this issue for us.

**Comment by 42wim** [comment]
Should be fixed in master, reopen if still an issue.
