### ISSUE TITLE
Query window, img paste, wrong author

### ISSUE THREAD

**Issue by faljse** [42wim/matterircd#228]
When pasting an image in a query window in mattermost web, 
the resulting message/link originates from the wrong user.
Also the link is never echoed back.

.) User A(web) pastes image in mattermost web query window
.) User B(irc) receives link from user B
.) User A(irc) doesnt receive the link at all

Matterircd 0.19.0
Mattermost 5.7.1

**Comment by 42wim** [comment]
Thanks for reporting, fixed in master now. Soon in 0.19.2
