### ISSUE TITLE
Login to a local instance of mattermost  fails 

### ISSUE THREAD

**Issue by wingrime** [42wim/matterircd#23]
In my configuration I use mattermost on custom port and seems it runs without https
```
/msg mattermost login 192.168.59.103:8065 testing <login> <pass>
We encountered an error while connecting to the server
````

Also, log lack any messages according to login attempts

**Comment by 42wim** [comment]
I added support for this in master.
Could you do a ```go get -u``` and try running matterircd with the ```-mminsecure``` flag.
This allows http connections and should work with your setup

**Comment by wingrime** [comment]
Yes, I try

**Comment by wingrime** [comment]
Works
