### ISSUE TITLE
Direct messages from groups are not correctly handled

### ISSUE THREAD

**Issue by flexd** [42wim/matterircd#232]
Related to #193 and others.

I'm in a direct chat group with several others. When I was invited to the group chat I got a private message from that person directly, even if they wrote the message in the channel, and matterircd joined a channel named by the id mattermost uses for that channel. Any message to that channel gets sent to me as a direct message from that user, 

If I write a message in the channel via matterircd it shows up as a normal message in the mattermost web interface.

If I write a message via the web interface it shows up in the channel as intended.

If anyone else in the channel writes a message I get a direct message from them in matterircd. Nothing shows up in the channel.

I'm on 0.19.1-dev, Mattermost Version: 5.5.1

**Comment by 42wim** [comment]
Could you try again on current master?
I've tested this with 3 users and I can't reproduce this at the moment.

**Comment by dgruss** [comment]
also working fine for me since months
