### ISSUE TITLE
Can send to channel after leaving in mattermost

### ISSUE THREAD

**Issue by setpill** [42wim/matterircd#233]
Steps to reproduce:

1. Be in mattermost channel.
2. Connect to matterircd, autojoin mattermost channel.
3. In mattermost UI, leave channel.

Expected behaviour:

* IRC client no longer receives messages from channel.
* Sending to channel from IRC is not possible.
* IRC client leaves channel.

Observed behaviour:

* :heavy_check_mark: IRC client no longer receives messages from channel.
* :x: Sending to channel from IRC is *still* possible (mattermost-server issue)
* :x: IRC client *does not* leave channel.

**Comment by setpill** [comment]
NB: **After** rejoining the channel in mattermost, the IRC client is forced to quit, and receives an error that the (public) channel cannot be joined because it is +i.

**Comment by setpill** [comment]
NB: this also works for secret channels, and also works after getting kicked.

**Comment by setpill** [comment]
NB: when being readded to a secret channel in IRC after being kicked, IRC client does not leave the channel.

**Comment by setpill** [comment]
Note that disallowing users from sending to a channel they are not in should be fixed in mattermost-server (see linked issue); but fixing IRC join/leave behaviour should be fixed here.

**Comment by 42wim** [comment]
Fixed in master, thanks for reporting.
