### ISSUE TITLE
Non readable symbols at end of message.

### ISSUE THREAD

**Issue by wingrime** [42wim/matterircd#24]
Messages are being sent form IRSSI results some strange non-readable symbols
![](https://www.dropbox.com/s/ieowri8yip5fctc/matter-most-irc.tiff?raw=1)

**Comment by tamentis** [comment]
Same here, we've seen "Unicode Character 'MONGOLIAN VOWEL SEPARATOR' (U+180E)" inserted at the end of some messages coming from irssi.

**Comment by 42wim** [comment]
Is by "design", see https://github.com/42wim/matterircd/issues/14 and https://github.com/42wim/matterircd/issues/14#issuecomment-160757922

Ideas for other (more elegant) solutions are welcome. 

Normally you shouldn't see the unicode character though.
