### ISSUE TITLE
All messages from channels go into &messages

### ISSUE THREAD

**Issue by lazyusername** [42wim/matterircd#242]
After update 0.18.4-dev => 0.19.[12], all mesages from my channels are going into &messages instead in correct channel of origin. It looks like this:

`[user_nickname/#channel]: text`

It's this way even if I post message in my channel myself using the website. In my irc client I see it in &messages instead in my channel.

Mattermost version: 5.9.0
Matterircd version: 0.19.2

**Comment by lazyusername** [comment]
A little update on this one.

When i spawn the process, at first almost all of the channel messages goes into &messages in the format I've posted above.
After some time it somehow starts work properly and the messages go directly into the correct channel of origin.

**Comment by 42wim** [comment]
Could you run with `-debug`?

It's a lot of output, but I'm wondering if you see messages like this:
`channel %s is in JoinExclude, send to &messages`
or 
`channel %s is not in JoinInclude, send to &messages`

**Comment by lazyusername** [comment]
I am luckily already running the instance with -debug for sometime. I've just grep the logs and I see:

> channel %s is not in JoinInclude, send to &messages

I didn't set `JoinInclude` in my conf because I am already on these channels joined on mattermost (according to the web client of mattermost).

**Comment by lazyusername** [comment]
Just to be more specific about this. I'm joined on these channels (both - matterircd and mattermost) but still, for some time the messages don't appear in channel(s) of origin in my irc client but go directly into &messages.
I see the users in these channels of origin and joins/parts of these users. Just the messages from them for some time (hours) go into &messages.

**Comment by 42wim** [comment]
Could you paste your matterircd.toml conf? DefaultTeam/DefaultServer info isn't needed

**Comment by lazyusername** [comment]
cat matterircd.toml | grep -v "^#"

> Bind = "127.0.0.1:6667"
> Debug = true
> 
> [mattermost]
> DefaultServer = "mm.example.com"
> DefaultTeam = ""
> Insecure = false
> PartFake = true
> Restrict = ["mm.example.com"]
> SkipTLSVerify = false
> PrefixMainTeam = false

Another new observation. I wrote with one user via private messages (query) and the user sent me message that went directly into query. But then the user edited the message and the edited message went into &messages:

Query:
>[15:14:31] [user_nickname]: message_text

Edited message in &messages
>[15:15:58] [user_nickname/#4o16swojntfx8j413hshf9nwdo__hnr4xw8tnfy4xe4zppsp]: message_text (edited)

Debug log the edited message event:
>time="2019-04-24T15:15:58+02:00" level=debug msg="WsReceiver event: model.WebSocketEvent{Event:"post_edited", Data:map[string]interface {}{"post":"{\"id\":\"gywgpktkob8w78imrcxswm3y5r\",\"create_at\":1556111671274,\"update_at\":1556111758222,\"edit_at\":1556111758222,\"delete_at\":0,\"is_pinned\":false,\"user_id\":\"hnr4xw8tnfy4xe4zppspoe1g8h\",\"channel_id\":\"13z7o88htif6mftn3ejohzfc4o\",\"root_id\":\"\",\"parent_id\":\"\",\"original_id\":\"\",\"message\":\"message_text\",\"type\":\"\",\"props\":{},\"hashtags\":\"\",\"pending_post_id\":\"\",\"metadata\":{}}"}, Broadcast:(*model.WebsocketBroadcast)(0xc42084e540), Sequence:204, precomputedJSON:(*model.precomputedWebSocketEventJSON)(nil)}" prefix=matterclient
>time="2019-04-24T15:15:58+02:00" level=debug msg="MMUser WsReceiver: &model.WebSocketEvent{Event:\"post_edited\", Data:map[string]interface {}{\"post\":\"{\\\"id\\\":\\\"gywgpktkob8w78imrcxswm3y5r\\\",\\\"create_at\\\":1556111671274,\\\"update_at\\\":1556111758222,\\\"edit_at\\\":1556111758222,\\\"delete_at\\\":0,\\\"is_pinned\\\":false,\\\"user_id\\\":\\\"hnr4xw8tnfy4xe4zppspoe1g8h\\\",\\\"channel_id\\\":\\\"13z7o88htif6mftn3ejohzfc4o\\\",\\\"root_id\\\":\\\"\\\",\\\"parent_id\\\":\\\"\\\",\\\"original_id\\\":\\\"\\\",\\\"message\\\":\\\"message_text\\\",\\\"type\\\":\\\"\\\",\\\"props\\\":{},\\\"hashtags\\\":\\\"\\\",\\\"pending_post_id\\\":\\\"\\\",\\\"metadata\\\":{}}\", \"team_id\":\"\"}, Broadcast:(*model.WebsocketBroadcast)(0xc42084e540), Sequence:204, precomputedJSON:(*model.precomputedWebSocketEventJSON)(nil)}" module=matterircd
>time="2019-04-24T15:15:58+02:00" level=debug msg="handleWsActionPost() receiving userid hnr4xw8tnfy4xe4zppspoe1g8h" module=matterircd
>time="2019-04-24T15:15:58+02:00" level=debug msg="User user_nickname is not in channel #4o16swojntfx8j413hshf9nwdo__hnr4xw8tnfy4xe4zppspoe1g8h. Joining now" module=matterircd
>time="2019-04-24T15:15:58+02:00" level=debug msg="channel #4o16swojntfx8j413hshf9nwdo__hnr4xw8tnfy4xe4zppspoe1g8h is not in JoinInclude, send to &messages" module=matterircd
>time="2019-04-24T15:15:58+02:00" level=debug msg="-> :user_nickname/#4o16swojntfx8j413hshf9nwdo__hnr4xw8tnfy4xe4zppspoe1g8h!user_nickname/#4o16swojntfx8j413hshf9nwdo__hnr4xw8tnfy4xe4zppspoe1g8h@user_nickname/#4o16swojntfx8j413hshf9nwdo__hnr4xw8tnfy4xe4zppspoe1g8h PRIVMSG &messages :message_text (edited)" module=matterircd
>time="2019-04-24T15:15:58+02:00" level=debug msg="handleWsActionPost() user user_nickname sent message_text" module=matterircd
>time="2019-04-24T15:15:58+02:00" level=debug msg="&model.Post{Id:\"gywgpktkob8w78imrcxswm3y5r\", CreateAt:1556111671274, UpdateAt:1556111758222, EditAt:1556111758222, DeleteAt:0, IsPinned:false, UserId:\"hnr4xw8tnfy4xe4zppspoe1g8h\", ChannelId:\"13z7o88htif6mftn3ejohzfc4o\", RootId:\"\", ParentId:\"\", OriginalId:\"\", Message:\"message_text\", MessageSource:\"\", Type:\"\", Props:model.StringInterface{}, Hashtags:\"\", Filenames:model.StringArray(nil), FileIds:model.StringArray(nil), PendingPostId:\"\", HasReactions:false, Metadata:(*model.PostMetadata)(0xc4201e3420)}" module=matterircd
time="2019-04-24T15:15:58+02:00" level=debug msg="posting lastview "13z7o88htif6mftn3ejohzfc4o"" prefix=matterclient
>time="2019-04-24T15:15:58+02:00" level=debug msg="WsReceiver event: model.WebSocketEvent{Event:"channel_viewed", Data:map[string]interface {}{"channel_id":"13z7o88htif6mftn3ejohzfc4o"}, Broadcast:(*model.WebsocketBroadcast)(0xc4204a8400), Sequence:205, precomputedJSON:(*model.precomputedWebSocketEventJSON)(nil)}" prefix=matterclient
>time="2019-04-24T15:15:58+02:00" level=debug msg="in handleWsMessage0" module=matterircd

**Comment by 42wim** [comment]
You're running this on master commit?

**Comment by lazyusername** [comment]
> You're running this on master commit?

Yes.

**Comment by dansimau** [comment]
Just a note, I am seeing this as well, periodically. In my case, I've noticed it happening after I get logged out and then I log back in. When I restart matterircd it starts working again. I think some state is getting messed up somewhere. I'm also using ZNC.

I've just enabled debug mode so I can start investigating this next time it happens.

**Comment by 42wim** [comment]
Could you both try master again?

**Comment by lazyusername** [comment]
I am running on the master last 20 hours and it seems to be fixed.

thx a lot!
