### ISSUE TITLE
Can't reach some mattermost users

### ISSUE THREAD

**Issue by lazyusername** [42wim/matterircd#243]
I can't reach some mattermost users. What I actually do in my irc client is:

`/query user_nickname`

The query is opened, but I can see in my client that this user doesn't exist on irc server. The way I notice it is that when is everything ok I see the user as:

`some_hash@https://mattermost_server`

But when I have this problem, I am tying to describe in this issue, the "address" of user is blank and I can't reach the user. The interesting part is, that when I do `/whois user_nickname` the reponse from matterircd has the correct "address" of user, but the channels part is missing.

Mattermost version: 5.9.0
users using mattermost instance: >1000
Matterircd version: 0.19.2 (but I had this problem before too)

**Comment by 42wim** [comment]
This is probably related to the #244 issue, which is now fixed in master.
Could you please test if it's still an issue?

**Comment by lazyusername** [comment]
I've tested it with version from master and it seems to be working.

thx!
