### ISSUE TITLE
Low count of users in &users 

### ISSUE THREAD

**Issue by lazyusername** [42wim/matterircd#244]
I can't see all users in &users. Our mattermost instance has multiple teams and these I am in, have above 1k users. Anyway in `&users` I see the user list ending with users starting with letter `j` and that's it.

I see the note here:

`&users channel that contains members of all teams (if mattermost is so configured) for easy messaging`

But I am not sure, what does it actually mean. Can someone be more descriptive on this one, please?

Mattermost version: 5.9.0
Matterircd version: 0.19.2 (but I had this problem before too)

**Comment by 42wim** [comment]
It contains all the users of the teams you are a member of.
Could be a paging issue, seems they changed the limit to 200 users, could it be that that's the amount of users you're seeing? (I don't have access to a mattermost large enough to test)

**Comment by 42wim** [comment]
Was a paging issue, this is fixed now in master, could you verify?
Please reopen if still an issue.

**Comment by lazyusername** [comment]
I can confirm that it's fixed in master branch. I can see 1K+ users in &users now . The related issue  (#243) needs some time to review.

Thx a lot!
