### ISSUE TITLE
I am constantly recieving old backlog

### ISSUE THREAD

**Issue by lazyusername** [42wim/matterircd#245]
Since update of mattermost to last version (5.9.0) I am recieving old backlog in my irc client.  Even when I stop running of matterircd and spawn the process again and then connect with my irc client to matterircd I am recieving backlog in channels that I have already read multiple times.

Example:

> [05:09:49] [matterircd]: Replaying since 2019-04-12
> [05:09:49] [A]: [12:40] A_text
> [05:09:49] [B]: [12:45] B_text
> [05:09:49] [C]: [14:38] C_text
> [06:47:15] [matterircd]: Replaying since 2019-04-12
> [06:47:15] [A]: [12:40] A_text
> [06:47:15] [B]: [12:45] B_text
> [06:47:15] [C]: [14:38] C_text

Matterircd version: 0.19.2

**Comment by 42wim** [comment]
If you didn't enable `DisableAutoView = true` in your `matterircd.toml` then this is most likely a bug in mattermost.
We ask mattermost about when you lastviewed a channel, could be something wrong in the database.

**Comment by lazyusername** [comment]
I didn't set `DisableAutoView` at my config at all.

**Comment by muesli** [comment]
I can reproduce this here, as well. I've now enabled DisableAutoView and will see how that behaves / feels like.

**Comment by 42wim** [comment]
I've also got bitten by this and did some further debugging. This is definitely a mattermost issue, they don't update the channel even though we send this event (and we don't receive an error).

To fix this you can just drop a message in the channel that's replaying it and delete the message again.
The issue should be solved.
