### ISSUE TITLE
ZNC stopped logging the private messages

### ISSUE THREAD

**Issue by lazyusername** [42wim/matterircd#253]
I am using the matterircd behind the ZNC proxy and since version `0.18.4-dev` I've noticed the ZNC doesn't log the query with users and doesn't put it in backlog for me.
I mean I see the logs, but there are only messages I've sent, not the user I am having query with.

Since I am debug logging matterircd due to other problems (unrelated to this issue) I have verbose logs and I can see that the PRIVMSG matterircd is sending has changed and I believe the missing logs on my ZNC is related to this.

user_nick => user is writting to me
my_nick = > my matterircd user
server_url => mattermost url

The old `0.18.4-dev` that is working correctly:
```
level=debug msg="-> :user_nick!user_nick@user_nick PRIVMSG my_nick :message_text" module=matterircd
```
The new `0.19.3-dev` (master commit) - I don't see these replies in my ZNC logs (and backlog):
```
level=debug msg="-> :user_nick!user_nick@server_url PRIVMSG user_nick :message_text" module=matterircd
```
As you can notice the PRIVMSG changed from `PRIVMSG my_nick` => `PRIVMSG user_nick`.

In my client I recieve the messages correctly (I see them in query) but clearly ZNC doesn't handle the messages as sent to me (I don't see them in log, I don't see them in backlog).

**Comment by lazyusername** [comment]
I suppose this could be related to https://github.com/42wim/matterircd/issues/203 juding by @Aketzu description of issue.

**Comment by 42wim** [comment]
Try again using master, if still and issue reopen
