### ISSUE TITLE
issue with new mattermost channels

### ISSUE THREAD

**Issue by Peter4825** [42wim/matterircd#262]
Tested with mattermost 5.15.0 and matterircd 0.19.2:

When someone else creates a channel on mattermost and joins me into this channel, I do not join the proper channel name, but I've joined the ID (Without a hash to indicate the channel)
Messages sent to this channel also do not go to the correct window.   When I /reconnect to the matterircd, the problems are solved.

**Comment by efenex** [comment]
Same issue here, messages I send myself (via the web-interface) or receive go to the generic &messages channel (with <user>/<channel> nickname)

**Comment by efenex** [comment]
When I join the channel manually in the IRC client, both sent and received messages end up in the right place: seems like it's primarily the joining of the channel which doesn't happen automatically (when creating a channel through web-if or when invited).

**Comment by Peter4825** [comment]
With the new release of matterircd 0.19.3 this issue has been resolved.  Thanks!
