### ISSUE TITLE
On some slacks I only see reactions with matterircd 1.9.3 release

### ISSUE THREAD

**Issue by abramhindle** [42wim/matterircd#264]
Hi, I'm having problems with 1 slack instance where I only see reactions, I can't join in irssi the channels that I am in the slack. And I typically only see reactions, no messages. I've tried 2 different IRC clients so the problem is clearly matterircd. I am using 1.9.3 . It seems weird that I only see reactions.

I don't seem to suffer the same problems with 1.9.2.

In the freenode channel another user said they suffered from the same problem with 1.9.3 and downgraded accordingly.

Other observations:
I would be joined to the &users channel. it would list more than 100 users. I could not join channels I was already in on slack, it said I'd have to be invited. If someone reacted in the channels I'd see the reaction.

**Comment by 42wim** [comment]
Thanks for reporting, seems to be a bug in the upstream slack library.
I've fixed this in master and will be releasing a 1.9.4 soon
