### ISSUE TITLE
Edited messages in private chats show up in channel_name, not in irc private chats

### ISSUE THREAD

**Issue by bucko909** [42wim/matterircd#265]
Inspecting the payload of messages from Mattermost, it looks like the `"posted"` WS event has `"channel_type": "D"` as well as the important `"post"` and other information, but the `"post_edited"` event's payload contains only `"post"`.

The post *does* contain a `"channel_id"`, which is, I'm guessing, used in a lookup of the target username. I get a debug message of `"User <me> is not in channel #<myid>_<theirid>. Joining now"`, and on my IRC client I'm forced into `#<myid>_<theirid>`.

I don't know enough about the data model to really work out how to fix this. I think ideally the channel lookup in `handleWsActionPost` would realise it'd found a direct message chat and canonicalise it back down to the other participant.

**Comment by 42wim** [comment]
This has been fixed in master
