### ISSUE TITLE
Private message backlog shows as coming from myself

### ISSUE THREAD

**Issue by kkofler** [42wim/matterircd#267]
I am using `matterircd` v0.19.4 with Mattermost 5.17.3. I have received a private message from another user while I was offline. Upon connecting, `matterircd` replays the message, but makes it look as if I had sent it myself. (It shows up as coming from my own username and the actual author is not shown anywhere.)

**Comment by guilhermepiccoli** [comment]
I've noticed a similar behavior: if I'm on matterircd and open a web tab with mattermost, if I send a private message to any user, it shows in IRC as coming from me, no reference to the user targeted.

**Comment by kkofler** [comment]
That's not exactly the same bug though. In my case, the messages have actually been sent by user X to me and show up as messages from me to me. That is clearly wrong and should be relatively easy to fix.

In your case, the messages have been sent by you to user X, which cannot really be mapped correctly. (I would expect those messages to not be replayed at all.) The only way to get the messages appear in the dialog with user X in your IRC client would be to make them look like messages **from** user X, which would also be incorrect.

**Comment by guilhermepiccoli** [comment]
Thanks Kevin, I agree with you. My issue is a bit different and much less important, I just commented here in order to have the clarification, thanks for commenting!
BTW, congrats for matterircd! Great piece of software, life saver in a world of RAM eater clients heheh

Cheers,


Guilherme

**Comment by 42wim** [comment]
This should be fixed in master
