### ISSUE TITLE
Reactions, Edited and Deleted messages

### ISSUE THREAD

**Issue by guilhermepiccoli** [42wim/matterircd#269]
Hi folks, this is not an issue per se, it's more a enhancement possibility that I'd like to get feedback.

So, is there a way to indicate in IRC when a message is reacted to? Or edited/deleted? I thought in something like: "new message after edit (edited -> was: old msg before editing)". For reactions, something like ":emoji: (Reaction to: <original msg>)", and the same template for deleted messages. I think deleted messages are the least important, since the user want it deleted heheh

I found this patch (as a Github suggestion on similar issues): https://github.com/42wim/mm-go-irckit/commit/2cda758f3cb90de936203ea4ce92b95105b176a2
So, is matterircd ignoring emoji reactions ? Also, found issue #192 about edited messages, but seems I'm not seeing them in my IRC client.

Thanks,

Guilherme

**Comment by guilhermepiccoli** [comment]
OK, I've re-tested and seems it shows the edited message, but in a odd way. I've edited my own message in a private chat with a friend, it came to the IRC as a new private message from..a token! And it shows: "new msg (edited)", but it doesn't refer to the original message that was edited.

**Comment by 42wim** [comment]
What bridge are you talking about, slack or mattermost ?
If mattermost what mattermost version?

**Comment by guilhermepiccoli** [comment]
I'm talking about Mattermost, version 5.21.0 (Enterprise Edition is seems).
Thanks =)

**Comment by jdstrand** [comment]
FYI, I confirmed that I cannot see reactions with mattericd 0.19.4, irssi 1.2.2 and Mattermost Version: 5.23.1 Enterprise Edition.

**Comment by guilhermepiccoli** [comment]
@42wim , do you think that'd be difficult to add in the refactor? I'm not sure if it's something I should pursue myself..maybe too complex?

**Comment by jdstrand** [comment]
For completeness, I also tested this against 0.20 master (as of now, a1ab35cf14ae08a15ad34f2daf0ee1cb2d862d7d) and the problem persists.

**Comment by 42wim** [comment]
I'm currently focused on bugfixing, this feature will probably be added later (as slack in matterircd already has this)

**Comment by 42wim** [comment]
Supported now on master, you need to set the option  `prefixContext=true` under the `[mattermost]` section.

The prefixcontext is an experiment, not sure about the UX yet (but there isn't really a better option that I can think off, repeating the whole message constantly isn't a good idea either).

The slack version uses timestamping, but this isn't clear for multiple messages/reactions within a minute.

**Comment by guilhermepiccoli** [comment]
Thanks a lot @42wim, gonna test soon!
