### ISSUE TITLE
matterircd with Google Authenticator

### ISSUE THREAD

**Issue by SpliNTSweden** [42wim/matterircd#272]
Hello,

I'm trying login to a mattermost server that needs username & password + a token generated by Google Authenticator.

`15:41 <User1> login <server> <username> <pass> 15:41 <mattermost> Invalid MFA token.`

Is there any support for this?

I've tried experimenting with MMAUTHTOKEN and TOKEN without any luck, probably since this token doesn't replace the password.

Cheers

**Comment by 42wim** [comment]
I suggest creating a personal token

**Comment by 42wim** [comment]
Thanks to @eyenx this now works with `/msg mattermost login <server> <team> <username/email> <password> MFAToken=<mfatoken>`
