### ISSUE TITLE
/away in irc doesn't update status on mattermost

### ISSUE THREAD

**Issue by jdstrand** [42wim/matterircd#277]
Thank you for mattericd: it is really nice to be able to connect to mattermost with my irc client!

With mattericd 0.19.4, irssi 1.2.2 and Mattermost Version: 5.23.1 Enterprise Edition, when I use `/away` in my irc client, it shows me as away but my status is not updated in mattermost. https://github.com/42wim/matterircd/issues/165 may be this issue, but it is closed so I filed a new bug.

**Comment by guilhermepiccoli** [comment]
Hi Jamie! I reported this issue recently, it's issue #275

**Comment by 42wim** [comment]
Closing in favor of #275

**Comment by jdstrand** [comment]
Thanks! I can confirm that 0.20-dev fixes the issue for me.
