### ISSUE TITLE
Add option to disable showing parent posts in replies

### ISSUE THREAD

**Issue by hloeung** [42wim/matterircd#278]
Hi,

When someone replies to a post, matterircd shows this in https://github.com/42wim/matterircd/blob/master/mm-go-irckit/mmuser.go#L303

On IRC, it looks something like this:

|15:46 <jane_user1> Thanks @bob_user2 !
|15:47 <bob_user2> no worries :) (re @jane_user1: Thanks @bob_user2 !)

With extra/duplication. Can we have the option to disable this? Perhaps via the config file so it's not the default behaviour.

**Comment by hloeung** [comment]
https://github.com/42wim/matterircd/pull/283

**Comment by 42wim** [comment]
Closed by yourself :)
