### ISSUE TITLE
Compilation error because of update in mattermost platform

### ISSUE THREAD

**Issue by Grokzen** [42wim/matterircd#28]
When we tried to compile this code with go, we found out that it was broken because of a dependency have changed a signature in one method.

The following line was changed in `mattermost/platform` not long ago https://github.com/mattermost/platform/blame/master/model/client.go#L594 and with this commit https://github.com/mattermost/platform/commit/0e7a149982f73919badd9d366d06fa699925c89f

The signature of this method was changed to `GetChannelExtraInfo(id string, memberLimit int, etag string)` and adds one new argument `memberLimit`. You need to update all calls to this method within your code and deps to support this new signature.

**Comment by 42wim** [comment]
Thanks for the detailed bug report!
