### ISSUE TITLE
Ignore user join messages

### ISSUE THREAD

**Issue by hloeung** [42wim/matterircd#280]
Hi,

IRC clients already show user joins. Perhaps matterircd can ignore the user join messages?

`14:29 -!- jane_user1 [doo2Evooc7oociesahn9uekaix@https://chat.mycompany.local] has joined #town-square`
`14:29 <jane_user1> jane_user1 joined the team.`
`15:29 -!- bob_user2 [eeyiezas9eimahXieBie3iesh2@https://chat.mycompany.local] has joined #town-square`
`15:29 <bob_user2> bob_user2 joined the team.`

From the example above, that would be the two '$user jointed the team.' messages.

**Comment by 42wim** [comment]
fixed in master
