### ISSUE TITLE
Using matterircd with Gitlab authentication

### ISSUE THREAD

**Issue by chhitz** [42wim/matterircd#29]
I have enabled Mattermost (v1.3) that was installed with my Gitlab instance. It is set-up to use Gitlab for login. From matterircd (v0.2) I get the following error:

```
2016-01-27 09:48:22.590 DEBUG -> :mattermost!mattermost@service PRIVMSG chitz :Please sign in using gitlab
```

How can I get matterircd to work in this setup?

**Comment by hallabro** [comment]
I'm also interested in this, but I doubt that it is possible at the moment without any modifications. My first guess is that it would require modification of `mattermost` itself, and not `matterircd`.

**Comment by 42wim** [comment]
Not possible for now, I think mattermost only allows 1 oauth sign-in (gitlab or github) (and I guess this patch needs to be merged also https://github.com/mattermost/platform/pull/1938 before matterircd can use oauth)

My knowledge about oauth is _very_ limited though. Smarter people are always welcome to help out :)

**Comment by nnewman** [comment]
I've been playing around with both mattermost and matterircd for a few weeks now and i'm just getting around to OAuth. It's something that I'm interested in trying to implement for matterircd, but my knowledge of Go up to this point is limited. I'm wondering, if you were to go about implementing support for OAuth, if you had any suggestions as to how you would approach it? 

Thanks! And also thank you for making matterircd, its been very useful in convincing my colleagues to give mattermost a try, as a platform.

**Comment by dwest-galois** [comment]
I would also like to add make a feature request for this.  The Omnibus version of Mattermost only supports Gitlab SSO via Oauth, which is not usable by IRC clients such as irssi.  One alternative I have found is to allow users to convert their account authentication from Gitlab SSO to Email/Password.  Then they are able to use standard usernames and passwords to authenticate with their IRC clients.  That is not a viable large scale solution since it fragments the authentication for users and makes administration more difficult.  If matterircd could support Oauth, then that would be the preferable solution.  Otherwise, Mattermost Omnibus would need to either support a separate LDAP authentication or maybe even reuse the Gitlab LDAP configuration since it is already present in the gitlab.rb file.

**Comment by Feandil** [comment]
Could you support at least setting the auth token manually? (e.g. using https://github.com/mattermost/platform/blob/master/model/client.go#L1282)

(It's rather easy to obtain one, e.g. from the cookie in your web-browser and should work)

**Comment by 42wim** [comment]
@feandil great idea, I got it working. Commit coming up soon.

**Comment by 42wim** [comment]
@feandil Ok, rebuild from master, and you should be able to login by 
```/msg mattermost LOGIN <server> <team> <login> MMAUTHTOKEN=yourtoken```
Let me know if it works, thanks.

**Comment by Feandil** [comment]
Thanks, seems to work like a charm here :)

**Comment by 42wim** [comment]
I've updated master to show a bit more debug information, can you reproduce ?
And can you also paste the full trace after panic ? thanks

**Comment by trou** [comment]
`MMAUTHTOKEN=yourtoken` would be very nice to have in 0.5. Would you consider it backporting it ?

**Comment by 42wim** [comment]
@trou no sorry, older versions of mattermost have security problems. You should upgrade to mattermost 3.x (https://about.mattermost.com/security-updates/)

**Comment by Feandil** [comment]
Sorry, I have not been able to reproduce the bug so far. Please ignore my previous comment and sorry for the noise

**Comment by clark42** [comment]
Hi @42wim 

Happy new year and thanks a lot again for all your works!

I've just try with the v011-dev (master branch)
```
$ ./matterircd --version
Version: 0.11.1-dev
```
to join the a channel, and I still have the segfault issue :

Auth part :
```
DEBU[2017-01-02T12:12:22Z] <- PRIVMSG mattermost :login nbs-staff clark MMAUTHTOKEN=**************************  module=matterircd
INFO[2017-01-02T12:12:22Z] login as clark (team: nbs-staff) on mattermost.nbs-system.com  module=matterircd
DEBU[2017-01-02T12:12:22Z] trying login nbs-staff clark mattermost.nbs-system.com  module=matterclient
DEBU[2017-01-02T12:12:22Z] trying login with MMAUTHTOKEN                 module=matterclient
DEBU[2017-01-02T12:12:22Z] initUser(): found our team nbs-staff (id: fazbb347sigpfbxum5qm4zcygo)  module=matterclient
DEBU[2017-01-02T12:12:22Z] WsClient: making connection                   module=matterclient
INFO[2017-01-02T12:12:22Z] login succeeded                               module=matterircd
DEBU[2017-01-02T12:12:22Z] in addUsersToChannels()                       module=matterircd
```

Join part :
```
DEBU[2017-01-02T12:12:50Z] <- JOIN #alerts                               module=matterircd
DEBU[2017-01-02T12:12:50Z] Joining igp5apyqu7g9mddic7usjujzmo            module=matterclient
DEBU[2017-01-02T12:12:50Z] WsReceiver: model.WebSocketEvent{Event:"user_added", Data:map[string]interface {}{"team_id":"fazbb347sigpfbxum5qm4zcygo", "user_id":"t9a9dorw37frfjby5j84f7xopo"}, Broadcast:(*model.WebsocketBroadcast)(0xc42030f880), PreComputeJson:[]uint8(nil)}  module=matterclient
DEBU[2017-01-02T12:12:50Z] WsReceiver: &model.WebSocketEvent{Event:"user_added", Data:map[string]interface {}{"team_id":"fazbb347sigpfbxum5qm4zcygo", "user_id":"t9a9dorw37frfjby5j84f7xopo"}, Broadcast:(*model.WebsocketBroadcast)(0xc42030f880), PreComputeJson:[]uint8(nil)}  module=matterircd
DEBU[2017-01-02T12:12:50Z] WsReceiver: model.WebSocketEvent{Event:"posted", Data:map[string]interface {}{"sender_name":"System", "team_id":"fazbb347sigpfbxum5qm4zcygo", "channel_display_name":"alerts", "channel_type":"O", "post":"{\"id\":\"z7d6sreqhbfizc86n513b4rjtc\",\"create_at\":1483359170954,\"update_at\":1483359170954,\"delete_at\":0,\"user_id\":\"t9a9dorw37frfjby5j84f7xopo\",\"channel_id\":\"igp5apyqu7g9mddic7usjujzmo\",\"root_id\":\"\",\"parent_id\":\"\",\"original_id\":\"\",\"message\":\"jey has joined the channel.\",\"type\":\"system_join_leave\",\"props\":{},\"hashtags\":\"\",\"pending_post_id\":\"\"}"}, Broadcast:(*model.WebsocketBroadcast)(0xc42026c440), PreComputeJson:[]uint8(nil)}  module=matterclient
DEBU[2017-01-02T12:12:50Z] adding admin to #alerts                       module=matterircd
DEBU[2017-01-02T12:12:50Z] syncMMChannel adding myself to alerts (id: igp5apyqu7g9mddic7usjujzmo)  module=matterircd
DEBU[2017-01-02T12:12:50Z] -> :clark!clark@192.168.135.50 JOIN #alerts   module=matterircd
DEBU[2017-01-02T12:12:50Z] -> :matterircd 353 clark = #alerts :@admin clark   module=matterircd
DEBU[2017-01-02T12:12:50Z] -> :matterircd 366 clark #alerts :End of /NAMES list.  module=matterircd
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x4a15cd]

goroutine 44 [running]:
panic(0x7f6560, 0xc420010070)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).createMMUser(0xc4200b4420, 0x0, 0xc4204b7e70)
	/data/go/work/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:81 +0x3d
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).addUserToChannel(0xc4200b4420, 0x0, 0xc4203450b0, 0x7, 0xc420331f40, 0x1a)
	/data/go/work/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:99 +0x3c
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).handleWsActionUserAdded(0xc4200b4420, 0xc42030f840)
	/data/go/work/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:278 +0x14f
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).handleWsMessage(0xc4200b4420)
	/data/go/work/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:169 +0x29a
created by github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).loginToMattermost
	/data/go/work/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:65 +0x42e
```

I've just try with another user (not a gitlab user but a standard one).. and I have the same issue :(

Auth part :
```
DEBU[2017-01-02T12:19:54Z] <- PRIVMSG mattermost :login nbs-staff inglip 3dTi8uwPhQMNXFcRsKtH  module=matterircd
INFO[2017-01-02T12:19:54Z] login as inglip (team: nbs-staff) on mattermost.nbs-system.com  module=matterircd
DEBU[2017-01-02T12:19:54Z] trying login nbs-staff inglip mattermost.nbs-system.com  module=matterclient
DEBU[2017-01-02T12:19:55Z] <- PING 10.1.170.1                            module=matterircd
DEBU[2017-01-02T12:19:55Z] -> :matterircd PONG matterircd :10.1.170.1    module=matterircd
DEBU[2017-01-02T12:19:55Z] initUser(): found our team nbs-staff (id: fazbb347sigpfbxum5qm4zcygo)  module=matterclient
DEBU[2017-01-02T12:19:55Z] WsClient: making connection                   module=matterclient
INFO[2017-01-02T12:19:55Z] login succeeded                               module=matterircd
DEBU[2017-01-02T12:19:55Z] in addUsersToChannels()                       module=matterircd
```

Join part :
```
DEBU[2017-01-02T12:20:02Z] -> :matterircd 324 inglip #inglip :           module=matterircd
DEBU[2017-01-02T12:20:14Z] <- JOIN #com                                  module=matterircd
DEBU[2017-01-02T12:20:14Z] Joining f6gya59d938cxn4wertbc6nyze            module=matterclient
DEBU[2017-01-02T12:20:14Z] WsReceiver: model.WebSocketEvent{Event:"user_added", Data:map[string]interface {}{"user_id":"a3mo7pzi4tgi5g87xnea8i39sw", "team_id":"fazbb347sigpfbxum5qm4zcygo"}, Broadcast:(*model.WebsocketBroadcast)(0xc420247500), PreComputeJson:[]uint8(nil)}  module=matterclient
DEBU[2017-01-02T12:20:14Z] WsReceiver: &model.WebSocketEvent{Event:"user_added", Data:map[string]interface {}{"team_id":"fazbb347sigpfbxum5qm4zcygo", "user_id":"a3mo7pzi4tgi5g87xnea8i39sw"}, Broadcast:(*model.WebsocketBroadcast)(0xc420247500), PreComputeJson:[]uint8(nil)}  module=matterircd
DEBU[2017-01-02T12:20:14Z] adding admin to #com                          module=matterircd
DEBU[2017-01-02T12:20:14Z] adding jey to #com                            module=matterircd
DEBU[2017-01-02T12:20:14Z] syncMMChannel adding myself to com (id: f6gya59d938cxn4wertbc6nyze)  module=matterircd
DEBU[2017-01-02T12:20:14Z] -> :inglip!inglip@192.168.135.50 JOIN #com    module=matterircd
DEBU[2017-01-02T12:20:14Z] -> :matterircd 353 inglip = #com :@admin inglip jey   module=matterircd
DEBU[2017-01-02T12:20:14Z] -> :matterircd 366 inglip #com :End of /NAMES list.  module=matterircd
DEBU[2017-01-02T12:20:14Z] WsReceiver: model.WebSocketEvent{Event:"posted", Data:map[string]interface {}{"channel_display_name":"com", "channel_type":"O", "post":"{\"id\":\"6aui48y1n3bcifzrc5ft7imgzo\",\"create_at\":1483359614888,\"update_at\":1483359614888,\"delete_at\":0,\"user_id\":\"a3mo7pzi4tgi5g87xnea8i39sw\",\"channel_id\":\"f6gya59d938cxn4wertbc6nyze\",\"root_id\":\"\",\"parent_id\":\"\",\"original_id\":\"\",\"message\":\"inglip has joined the channel.\",\"type\":\"system_join_leave\",\"props\":{},\"hashtags\":\"\",\"pending_post_id\":\"\"}", "sender_name":"System", "team_id":"fazbb347sigpfbxum5qm4zcygo"}, Broadcast:(*model.WebsocketBroadcast)(0xc42040a680), PreComputeJson:[]uint8(nil)}  module=matterclient
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x4a15cd]

goroutine 42 [running]:
panic(0x7f6560, 0xc420010070)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).createMMUser(0xc4200b4420, 0x0, 0xc420185e70)
	/data/go/work/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:81 +0x3d
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).addUserToChannel(0xc4200b4420, 0x0, 0xc42032abb0, 0x4, 0xc4202e4ac0, 0x1a)
	/data/go/work/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:99 +0x3c
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).handleWsActionUserAdded(0xc4200b4420, 0xc4202474c0)
	/data/go/work/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:278 +0x14f
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).handleWsMessage(0xc4200b4420)
	/data/go/work/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:169 +0x29a
created by github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).loginToMattermost
	/data/go/work/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:65 +0x42e
```

It seems it's not a problem with the MMAUTHTOKEN (because I've the same segfault issue with a standard user).

Do you want I open another issue ?

Best regards

Clark

**Comment by kerhac** [comment]
It is also possible to use the mattermost [Personal Access Token](https://docs.mattermost.com/developer/personal-access-tokens.html) instead of the session token. The Personal Access Token does not expire.

**Comment by eniac111** [comment]
@kerhac is is compatible with the session token? I'm getting "Invalid or expired session"

**Comment by TC01** [comment]
> It is also possible to use the mattermost Personal Access Token instead of the session token. The Personal Access Token does not expire.

If I am reading the documentation correctly, though, only mattermost admins get those by default and they have to explicitly enable them for non-admin users. I don't think this is really a workable replacement for the gitlab tokens.

It is not clear to me *why* this is an admin-only feature that is off by default though.

**Comment by ltning** [comment]
If the reasoning here is that it's not enabled by default, then I think personal access tokens should still be the value to use. I don't know if there is a technical reason not to use them. Determining the MMAUTHTOKEN is not entirely trivial, and it's surely not something you can expect most people to figure out.

A big reason to use the PATs is that they can be revoked or disabled if lost or compromised.

If either approach can be used, then I'd like to see both. My 2 cents :)

**Comment by TC01** [comment]
Sure, I agree it would definitely be nice to support both. My point was just that switching to *only* use the personal access tokens would be bad-- since not all users can necessarily create them.

**Comment by tobast** [comment]
Hello,
Is there any progress on integrating personal access tokens? I'm interested in using this, and I might consider implementing it if the maintainer is fine with it and if no one is working on it yet.

**Comment by kerhac** [comment]
@tobast It is already possible to use the personal access token instead of the mmauthtoken. 

`/msg mattermost LOGIN <server> <team> <login> MMAUTHTOKEN=<personal access token>`

**Comment by tobast** [comment]
@kerhac Awesome, thank you! One fewer thing to hack before having a working Mattermost setup :)

**Comment by strigazi** [comment]
@kerhac With the actual MMAUTHTOKEN I can connect, but with a personal gitlab access token I can't. Any advice?

**Comment by jasonblais** [comment]
Hey @42wim and others.

Reading through this thread, it sounds like the current workarounds for GitLab login on matterircd include:

1. Copying the `MMTOKEN` cookie from the webapp, which is not trivial to do.
2. Creating a personal access token, which is only enabled for admins by default.

The reason we enabled personal access tokens for admins only is that these tokens were primarily intended to be used for integrations. We have bot accounts in the near term roadmap which would largely overtake the use case for personal access tokens for integrations.

That said, this second use case I'm reading about is interesting and not something we had in mind.

Are there other approaches or capabilities that Mattermost could better support GitLab (and other non-email logins) on matterircd? Or are personal access tokens the only way to go?

**Comment by 42wim** [comment]
Closing this, added to the FAQ in the readme
