### ISSUE TITLE
No rooms are shown

### ISSUE THREAD

**Issue by codygman** [42wim/matterircd#291]
I've successfully setup matterbridge to bridge irc<>Discord and then connected to the bridged matterircd irc server with my client. I see this message in matterircd:

```
DEBU[2020-08-05T18:08:21-05:00] <- JOIN #general                              module=matterircd
DEBU[2020-08-05T18:08:21-05:00] Executed &irc.Message{Prefix:(*irc.Prefix)(nil), Command:"JOIN", Params:[]string{"#general"}, Trailing:"", EmptyTrailing:false} <nil>  module=matterircd
DEBU[2020-08-05T18:08:23-05:00] <- PRIVMSG #general :[discord] <NAME> test  module=matterircd
DEBU[2020-08-05T18:08:23-05:00] -> :matterircd 401 #general :No such nick/channel  module=matterircd
DEBU[2020-08-05T18:08:23-05:00] Executed &irc.Message{Prefix:(*irc.Prefix)(nil), Command:"PRIVMSG", Params:[]string{"#general"}, Trailing:"[discord] <NAME> test", EmptyTrailing:false} <nil>  module=matterircd
```

But I cannot join #general.

I saw "PRIVMSG" so I thought maybe if I change my name to #general I'll get private messages.

Is there a way to create channels? Do I need to configure matterircd to do that?

That didn't seem to be the case either.

**Comment by 42wim** [comment]
wait, so you use matterbridge as a client to matterircd ?

**Comment by codygman** [comment]
> wait, so you use matterbridge as a client to matterircd ?

Yes. I want my discord and teams messages to be redirected to the matterircd server that I connect to from my IRC client.

**Comment by 42wim** [comment]
That's not supported, matterircd isn't made for that use-case. 
Every user that connects to matterircd is in its own special instance, multiple users on the same matterircd don't see each other.
So matterbridge and your own irc user will not see each other.

With the refactor I did, it's easier to plug another bridge into matterircd though, so mabye discord will be an option in the future.

**Comment by codygman** [comment]
I think I might have a misunderstanding here about the use-case matterircd is for. Perhaps just answering that question could clear up my misunderstanding, but if not then maybe explaining how I thought it worked will help.

I thought that when you setup matterbridge to copy messages to irc (matterircd) you can see messages typed by yourself in matterbridge as well as others enabling you to use any irc client to effectively use matterbridge.

It was my understanding then, that any service that matterbridge supports (Teams  for instance) will also get messages delivered to the configured irc server which for me was matterircd.
