### ISSUE TITLE
New users on channels don't "appear" until matterircd connection restarts or they speak

### ISSUE THREAD

**Issue by guilhermepiccoli** [42wim/matterircd#295]
If an user joins a channel in which the IRC user (running matterircd) is hanging, the channel list on IRC is not updated until the IRC user reconnects to to matterircd or until this new user that just joined talks in the channel, which forces a channel list update.

I suppose it's feasible to update channel's list of users/status whenever an user joins a channel the IRC user is present.

Also, taking the opporetunity: would be a bad idea @42wim to run through the matterircd user's channel list and update all channels periodically (like 10 times an hour), as an "anti-idle" thing? That would have the benefit of keeping the status of all users updated.

Thanks in advance!

**Comment by 42wim** [comment]
is this happening with master? 
Please always try to specify the git commit when opening an issue :)

**Comment by guilhermepiccoli** [comment]
Heheh - you are right, after your latest update/refactor, a lot of stuff got fixed, this one included!
So, guess we can close this one. Thanks
