### ISSUE TITLE
Interesting and mysterious issue with messages not being relayed to IRC client

### ISSUE THREAD

**Issue by guilhermepiccoli** [42wim/matterircd#296]
I'm running matterircd behind an IRC bouncer (ZNC), so basically ZNC is connected to matterircd 24x7, and my IRC client connects to znc whenever I'm online. Hence, ZNC is handling the "replay" functionality - I believe from matterircd's perspective, this topology works as if I'm 100% of time online.

But..there's an odd, pretty weird behavior. Whenever my client is not connected to znc, I don't receive private messages. I can check them on web client, but I cannot see them either on ZNC logs or matterircd. I can however see them on matterircd debug logs.

I'm not sure if this issue happens on ZNC or matterircd...in case anybody has a clue to debug this or have experienced similar behavior, let us know.

Thanks in advance!

**Comment by guilhermepiccoli** [comment]
Reproduced on master, at 6715b16d62 (2020-08-11).
I found this |ZNC issue that seems to be a match: https://github.com/znc/znc/issues/1638

**Comment by 42wim** [comment]
I'm going to close this as this seems a ZNC issue
