### ISSUE TITLE
matterircd from today's master is not reading the conf file?

### ISSUE THREAD

**Issue by guilhermepiccoli** [42wim/matterircd#297]
@42wim , I just tried the new matterircd from master - I've noticed the cmdline arguments parser changed so we need to use now "--conf" correct? But it didn't fly here:

./matterircd --debug --conf my.toml
INFO[2020-08-11T22:22:04+02:00] enabling debug                                module=matterircd
INFO[2020-08-11T22:22:04+02:00] Running version 0.20.0-dev                    module=matterircd
INFO[2020-08-11T22:22:04+02:00] WARNING: THIS IS A DEVELOPMENT VERSION. Things may break.  module=matterircd
INFO[2020-08-11T22:22:04+02:00] Listening on 127.0.0.1:6667 

In my toml I have a different port, so it didn't read. If I skip my.toml and the "--conf" parameter, the output is the same, so it seems it's ignoring the conf file.
Maybe it's something silly from me...but seems weird.

Thanks in advance!

**Comment by 42wim** [comment]
seems a bug, rename it to `matterircd.toml`  and it should work

**Comment by 42wim** [comment]
issue fixed in master now

**Comment by guilhermepiccoli** [comment]
Thank you for the promptness, indeed it's fixed now !
