### ISSUE TITLE
Previous direct messages (DMs)/group messages are always auto-joined on connect

### ISSUE THREAD

**Issue by jdstrand** [42wim/matterircd#299]
Direct messages (DMs)/group messages are auto-joined even though the web ui has hidden them. JoinExclude does not exclude them. You can /leave, /wc and /part on them, but they come back on the next reconnect. Not sure if I'm doing something wrong....

AIUI, the web ui keeps track of these itself by 'hiding' them because the server keeps them around for future use. I'm not sure what to suggest for matterircd but can say that these collect after some time (perhaps a /hide command?).

Btw, thank you for this very nice tool! :)

**Comment by 42wim** [comment]
This is option was already available for slack, now also for mattermost in master.
By default DM/group messages are not joined.
Set `JoinDM=true` to enable the joining

**Comment by jdstrand** [comment]
This is working great. Thanks!
