### ISSUE TITLE
'didn't find channel' and lots of 'p'

### ISSUE THREAD

**Issue by hloeung** [42wim/matterircd#301]
Hi,

Latest matterircd built from commit a1ab35cf14ae08a15ad34f2daf0ee1cb2d862d7d logs this:

```
INFO[0061] login succeeded
ERRO[2020-08-18T12:33:30Z] didn't find channel &users: channel not found  module=matterircd
ERRO[2020-08-18T12:33:30Z] didn't find channel &messages: channel not found  module=matterircd
XXX XXX
p
p
p
p
p
p
p
p
p
p
p
p
p
```

The `p`'s just keep repeating.

**Comment by 42wim** [comment]
This isn't something that I can reproduce, what mattermost version are you using?

(the errors are "normal", i'll remove those, but the 'p' is not)

Please add  debug and trace to your matterircd.toml, retry and put the log here (or on pastebin)

```
debug=true
trace=true
```

**Comment by hloeung** [comment]
I think it's this:

DEBU[2020-08-18T21:54:36Z] -> :matterircd 324 hloeung #haw-test : p      module=matterircd
DEBU[2020-08-18T21:54:36Z] Executed &irc.Message{Prefix:(*irc.Prefix)(nil), Command:"MODE", Params:[]string{"#haw-test"}, Trailing:"", EmptyTrailing:false} <nil>  module=matterircd
DEBU[2020-08-18T21:54:38Z] <- MODE #is-network                           module=matterircd

**Comment by hloeung** [comment]
Sorry, output earlier with Trace enabled, it was too noisy and I didn't spot it first hand, but here it is to confirm:

```
DEBU[2020-08-18T21:02:19Z] Executed &irc.Message{Prefix:(*irc.Prefix)(nil), Command:"MODE", Params:[]string{"#australia"}, Trailing:"", EmptyTrailing:false} <nil>  module=matterircd
DEBU[2020-08-18T21:02:22Z] <- MODE #haw-test                             module=matterircd
p
DEBU[2020-08-18T21:02:22Z] -> :matterircd 324 hloeung #haw-test : p      module=matterircd
DEBU[2020-08-18T21:02:22Z] Executed &irc.Message{Prefix:(*irc.Prefix)(nil), Command:"MODE", Params:[]string{"#haw-test"}, Trailing:"", EmptyTrailing:false} <nil>  module=matterircd
DEBU[2020-08-18T21:02:24Z] <- MODE #is-dce                               module=matterircd
p
```

It definitely is where the `p`'s are being added.

**Comment by alexmurray** [comment]
Is the P related to the recent support for private mode channels?

**Comment by hloeung** [comment]
Ah yes, it looks like it was added in https://github.com/42wim/matterircd/commit/e72a41996f4628f7e140a902f616c168885847fa

```
	if s.Channel(channel).IsPrivate() {
		mode = "p"
		fmt.Println(mode)
	}
```

**Comment by 42wim** [comment]
The 'p' thing you fixed yourself and the other error messages are fixed in a previous commit
