### ISSUE TITLE
Support replying to threads

### ISSUE THREAD

**Issue by hloeung** [42wim/matterircd#306]
Any chance of adding support for replying to threads?

An idea would be to include the thread ID or ParentId if one exists in a message . Then support something like @@ParentId, @#ParentId, or something along those lines. It'll then m.mc.Client.GetPost(data.ParentId, "") and if one exists, set the posts' ParentId to that.

**Comment by 42wim** [comment]
Thread reply now is implemented (also using the prefixcontext option)

You can reply on threads by using `@@number`

See example, `@@001 xyz` will create a response on abc

```
21:55 <wim> [001] abc
21:56 <wim> [002] def
21:56 <wim> [003->002] lala
21:56 <wimtest> @@001 xyz
```
