### ISSUE TITLE
slack uses wrong people when being notified

### ISSUE THREAD

**Issue by Peter4825** [42wim/matterircd#310]
- this is new since the refactor/0.20-dev
- This seems to be limited to slack only
- tested with code built from master on 2020-08-26

When someone else uses the @name system to notify someone: for example if user says Hey @peter,  we see on irc <user> hey @wrongusername

The username seems to be a random user from the server, including people who haven't spoken for ages or even disabled users...

**Comment by 42wim** [comment]
fixed in master
