### ISSUE TITLE
No scrollback is sent on private message

### ISSUE THREAD

**Issue by didrocks** [42wim/matterircd#312]
matterircd works very well here (using actually matterircd-jdstrand snap 0.20-dev+a1ab35c).
However, scrollback (messages sent when there was no active connection to mattermost) is only sent on channels, not on private message (even if it was already opened). How could I help debugging this?

Using weechat as IRC client.

**Comment by guilhermepiccoli** [comment]
Very good idea , seems replay in direct messages is a must! hehe

**Comment by 42wim** [comment]
private messages are also working.
Make sure you  have `joindm=true` otherwise it won't.

**Comment by didrocks** [comment]
Thanks a lot, indeed, `joindm=true` was needed. Thanks!

**Comment by keenmaster486** [comment]
I know this issue is closed, but I cannot figure out how to scrollback a DM. There's no channel name to pass to the scrollback command. What am I doing wrong?

**Comment by 42wim** [comment]
you can not force scrollbacks a DM at the moment, this issue is talking about missed messages appearing in your DM's when you reconnect
