### ISSUE TITLE
First message of a private chat is always lost

### ISSUE THREAD

**Issue by sergiodj** [42wim/matterircd#336]
Hi!  Thanks a lot for matterircd :-).

I'm using matterircd v0.20.1 directly from github, running on a Debian 10 container.

I am experiencing a scenario where I am always losing the first message of a private chat that I open with someone.  This situation only occurs if it is the first time I am opening a private chat with the person; in subsequent attempts, everything works fine.

I haven't investigated the issue further, but I looked at the logs I have on my server, and I could not find anything wrong being reported there.

@guilhermepiccoli was also able to reproduce the issue when testing with me.

**Comment by guilhermepiccoli** [comment]
Thanks a lot for the report Sergio! Indeed, I could reproduce that in our testing plus other day with a different colleague- it only seems to happen if it's the first time you have a private chat with a particular individual; after that, everything works normally.
I'll try to collect debug logs in an alternative mmost network I'm part of.

**Comment by guilhermepiccoli** [comment]
Below is the debug collection during a reproduction. I've message the user 3 times in a row: "test msg 1", "test msg 2" and then I asked sorry for annoying this user heh
Only "test msg 2" and the apology were received by this user, I was able to check that in the web interface, hope it helps to debug this issue! Notice I've never communicate with this user before.

[msg_test.txt](https://github.com/42wim/matterircd/files/5418264/msg_test.txt)
