### ISSUE TITLE
Odd issue related to /topic in a private message window

### ISSUE THREAD

**Issue by guilhermepiccoli** [42wim/matterircd#338]
Hey @42wim , today (with the "help" of a colleague) I found a very strange issue in matterircd. This colleague (johndoe) and I were talking in a private window/direct message. Then, johndoe (which uses the mattermost client) set a topic/header in such direct message window - apparently we can't see that in IRC (expected behavior).

I tried /topic in such private window, the command returned "empty", no topic detected. But then I couldn't send any other message to johndoe, everything I wrote in the private/direct message window gets refused to send, no "permissions" for that. It is as if /topic broke everything. By restarting matterircd and my IRC client, things got back to normal - we even test setting a topic in direct message window again and I could communicate with him, the problem was really my /topic command.

Collected some logs, not sure how helpful they are, but it's easy to reproduce I guess.
Thanks in advance!

**Comment by guilhermepiccoli** [comment]
[bug_msgs_topic.txt](https://github.com/42wim/matterircd/files/5424775/bug_msgs_topic.txt)

**Comment by 42wim** [comment]
@guilhermepiccoli I could not reproduce this.. but disabled any empty channel/topic for non-channels interactions. So hopefully also fixes your issue.

**Comment by guilhermepiccoli** [comment]
Thanks a bunch =)
