### ISSUE TITLE
Having JSON auth issues

### ISSUE THREAD

**Issue by jdatcmd** [42wim/matterircd#34]
When trying to login (I can connect):

2016-02-23 19:40:43.894 INFO LOGIN: AppErrorFromJson: , invalid character '<' looking for beginning of value, reconnecting in 5m0s

I am running 2.x of mattermost and 0.3 of matterircd. I am use pidgin as my irc client.

I also verified the problem with circ.

**Comment by 42wim** [comment]
Is your server running on https ?
Could you run with -debug and paste full logs?

**Comment by commandprompt** [comment]
I apologize, I did not see your feedback. Yes, it is https. I can't run with -debug right now but I will try this weekend.
