### ISSUE TITLE
Please restore command line options

### ISSUE THREAD

**Issue by bahamat** [42wim/matterircd#345]
I run matterircd on illumos, which produces the following error:

    2020/11/11 00:18:01 FEN based watcher not yet supported for fsnotify

Previously I used all command line options, but they are now missing, with the only option being the config file which doesn't work for me.

**Comment by 42wim** [comment]
Can you comment this line and recompile? It'll probably fix your issue as fsnotify will not be used
https://github.com/42wim/matterircd/blob/b7155f0e448d9f25add9bb24788e607ea6be64e5/config/config.go#L27

**Comment by bahamat** [comment]
I’ll give that a try and let you know.

**Comment by bahamat** [comment]
That works for me.
