### ISSUE TITLE
Crash on writing to channel with duplicate name

### ISSUE THREAD

**Issue by disassembler** [42wim/matterircd#35]
I made two teams and they both had the same private group in them. From IRC, I logged in to my first team, then when I switched my login to the second team and tried writing to the channel with that private group name, it crashed with this:

2016-02-23 23:32:19.467 CRITICAL websocket: continuation after final message frame
2016-02-23 23:32:19.467 CRITICAL websocket: continuation after final message frame
2016-02-23 23:35:02.277 CRITICAL websocket: unexpected reserved bits 7
2016-02-23 23:35:05.391 CRITICAL websocket: unexpected reserved bits 7
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x481770]
goroutine 41 [running]:
github.com/42wim/mm-go-irckit.(User).createMMUser(0xc820114000, 0x0, 0xc82038ece0)
        /home/sam/work/src/github.com/42wim/mm-go-irckit/mmuser.go:113 +0x2e0
github.com/42wim/mm-go-irckit.(User).handleWsActionPost(0xc820114000, 0xc820477950)
        /home/sam/work/src/github.com/42wim/mm-go-irckit/mmuser.go:280 +0x55d
github.com/42wim/mm-go-irckit.(User).WsReceiver(0xc820114000)
        /home/sam/work/src/github.com/42wim/mm-go-irckit/mmuser.go:257 +0x449
created by github.com/42wim/mm-go-irckit.(User).handleMMServiceBot
        /home/sam/work/src/github.com/42wim/mm-go-irckit/mmuser.go:532 +0xe97
...

**Comment by 42wim** [comment]
Not fixable at the moment. 

You should use an extra connection from your irc-client and do LOGIN again. 
Never do multiple LOGIN's from the same irc-connection, this gives issues even when you don't have the same channel.

**Comment by disassembler** [comment]
I figured that one out last night. I think the bigger issue is that anyone that can connect to the server can cause it to crash by doing this. Would be better to catch the exception and prevent it, or force a logout when a 2nd login is done.

**Comment by 42wim** [comment]
Indeed, working on it as we speak.

**Comment by 42wim** [comment]
Fixed in master now, care to try and see if it fixed your problem ?
