### ISSUE TITLE
Support SIGHUP to re-read and update running config

### ISSUE THREAD

**Issue by hloeung** [42wim/matterircd#356]
Hi,

This is more of a feature request, any chance of supporting SIGHUP to trigger re-reading the matterircd.toml and apply any config changes?

Would be nice to allow enabling or disabling configs without having to do a full restart (plus mattermost login and then wait for sync).

Per https://github.com/42wim/matterircd/commit/0a871bd7055ee8dd808d3e4371fff5ea0cfc604e, it already supports SIGHUP for reloading certs. So maybe another signal.Notify() to call config.LoadConfig()?

Thanks!

**Comment by 42wim** [comment]
This shouldn't be necessary? 
We already do a automatic reload on config changes (except when your on illumos)
What changes are you not picking up?

**Comment by hloeung** [comment]
Ah yes, confirmed. I've been spawning new matterircd instances to test between matterircd generated and mattermost message IDs.
