### ISSUE TITLE
Can't log in with ldap

### ISSUE THREAD

**Issue by bahamat** [42wim/matterircd#36]
We've set up mattermost with the enterprise LDAP plug in. After configuring LDAP authentication, when I try to log in with my ldap account it replies:

```
Please sign in using ldap
```

When using the web interface it presents two login forms, one for regular log in and one for LDAP.

**Comment by crspeller** [comment]
@42wim It should be available in the Mattermost API now. Our login routes have combined into one so it should be easy to implement.

**Comment by 42wim** [comment]
It's available in matterircd 'develop' branch (untested because I don't have an LDAP account yet), and you'll also need mattermost 'master' or wait until 3.0 release on 16 May :-)

**Comment by 42wim** [comment]
And just tested it, it works.
