### ISSUE TITLE
Nicknames with spaces

### ISSUE THREAD

**Issue by Peter4825** [42wim/matterircd#372]
I just upgraded to 0.22 (coming from 0.20.2) and new in this version is that one of my slack bots now uses a different name, probably the visible name or so.

This name contains a space, therefore the PRIVMSG command now is as follows:

Activity Feed!Program Activity Feed@Program Activity Feed PRIVMSG #ourchannel :Text

This is ofcourse no longer valid IRC so my irssi is failing on this.  As per usual, detailled logs are available on irc, /query me

**Comment by 42wim** [comment]
mattermost? slack?

**Comment by 42wim** [comment]
hm strange, slack wasn't touched between 0.20.2 and 0.22 so if you go back to 0.20.2 it still works?

**Comment by 42wim** [comment]
should be fixed by #374
