### ISSUE TITLE
Message may be droped silently

### ISSUE THREAD

**Issue by Zauberfisch** [42wim/matterircd#379]
I've had at least 2 cases where I sent multiple messages and one of them was dropped (= not delivered to mattermost) but no indication was given that the message was not delivered.

(My IRC client obviously shows all messages, but when I use the mattermost web-client, I see that one message did not get to mattermost)

There should be some way that a user is notified that matterircd failed to deliver a message.
A possible solution would be that the "user" mattermost sends a msq or query to the user saying "<....> failed to send" or something

**Comment by 42wim** [comment]
That is actually implemented, if there's an error you get that error back on irc

**Comment by Zauberfisch** [comment]
after a chat in IRC I'm closing this as a no-fix for now because I have yet to reliably reproduce this bug.

I will reopen if I am able reproduce it
