### ISSUE TITLE
Setting JoinDM = true joins all private groups on connect, but not single DMs.

### ISSUE THREAD

**Issue by keenmaster486** [42wim/matterircd#381]
I'm not sure if this is a bug or if I'm doing something wrong. When I set `JoinDM = true` in matterircd.toml, the server auto-joins me to any private DM groups I have active with three or more participants, but DMs to a single person are not joined. Any way to make this work? Also any plans to have the DMs act like a channel, with scrollback support? Thanks!

**Comment by 42wim** [comment]
"single" DM's can not be set as they are a client-side setting (eg /QUERY or /MSG user text) instead of a channel.
You can modify your client config to create /query windows with specific users though.

**Comment by keenmaster486** [comment]
That makes sense, thanks!

**Comment by 42wim** [comment]
scrollback DM isn't implemented yet, this can be done though, could you please open a new issue for this?
