### ISSUE TITLE
fd leak in 0.22

### ISSUE THREAD

**Issue by yitzhaq** [42wim/matterircd#390]
There seems to be an(other) fd leak in 0.22.

I have a monitoring check (using [monit](https://mmonit.com/monit/)) which does a simple TCP connect to matterircd's listening port every minute to see that it responds. These connections do not seem to be released, causing matterircd to run out of fd and stop working within a day.

After running for 1.5 hrs:

```
lsof -p `pidof matterircd` | grep -ic sock
90
```

These entries all look like:

`matterirc 16707 yitzhaq  101u     sock                0,8      0t0 668469870 protocol: TCP`

There's only one user and one session, and upstream Mattermost server is Enterprise Edition 5.31.0.

**Comment by 42wim** [comment]
Thanks for reporting, should be fixed in master now

**Comment by yitzhaq** [comment]
Many thanks for the quick fix!
