### ISSUE TITLE
Scrollback appears in chat with mattermost user, not in actual channels or DMs

### ISSUE THREAD

**Issue by keenmaster486** [42wim/matterircd#391]
Is this an "issue", or is this just the way that the system works and it can't be changed? Could an option be included to send the scrollback in the respective channels or user chats rather than dumping it all in the chat with the mattermost user? Thanks!

**Comment by hloeung** [comment]
@keenmaster486 https://github.com/42wim/matterircd/pull/393, feel free to further test and provide feedback.

Thanks!
