### ISSUE TITLE
Disconnected from matterircd

### ISSUE THREAD

**Issue by garethgreenaway** [42wim/matterircd#40]
Using irssi I'm able to connect to matterircd through an Amazon ELB, I'm also able to login in using my credentials and then interact with mattermost.  If I leave the connection idle for a few minutes then eventually it will disconnect from the matterircd server with the following error in the logs:

2016-03-20 23:44:59.531 ERROR handle decode error for gareth: EOF

**Comment by garethgreenaway** [comment]
fyi, seems to only happen when using the irssi client.

**Comment by 42wim** [comment]
Can you give me the versions you're using of mattermost, matterircd and irssi ?

**Comment by garethgreenaway** [comment]
irssi version 0.8.18 and using the latest Docker image for matterircd from https://hub.docker.com/r/xyproto/matterircd/.

Another piece of information, connecting to the service directly without having the ELB in place works fine and there are no timeouts.

**Comment by 42wim** [comment]
I'm afraid this is a bit hard to debug, I don't have access or experience with ELB
Do you maybe get ping timeouts on irssi before the disconnect ?
Try /set lag_check_time 0 to see if it makes a difference

**Comment by garethgreenaway** [comment]
I tried setting the lag_check_time to zero and it didn't make a different.  I don't see anything that indicates a ping timeout but I might need to increase debug level or verbosity, will see if that's possible and report back.

**Comment by garethgreenaway** [comment]
While I'm looking into this, an additional question that I haven't been able to find the answer to that could eliminate my need for an ELB.  Does MatterIRCD support SSL?

**Comment by 42wim** [comment]
It does now :)

**Comment by garethgreenaway** [comment]
:+1:

**Comment by 42wim** [comment]
fixed by using TLS
