### ISSUE TITLE
Direct Messaging to slack is broken

### ISSUE THREAD

**Issue by Peter4825** [42wim/matterircd#400]
After working reliably for a long time, all of a sudden, messaging people in slack is broken.

Only the messages I sent to slack via matterircd server are broken - I don't see the messages showing up in the webinterface of slack.  This is probably due to a change at the slack side, as I did not change anything.  I've confirmed with another user - this does not seem to be a local problem.

So to clarify:
I send a message on irc -> matterircd -> slack server: broken
I send a message on the slack interface: the self-message on irc still appears and works fine
Other people message messaging me: still works

This is only for one-2-one private messaging.  Messages to channels still work fine

Using the latest matterircd 0.23.0

**Comment by Peter4825** [comment]
As a followup: if I search around a bit I find the following things on the interwebs: https://github.com/slack-go/slack/issues/748

Basically a chunk of API's are deprecated and disabled serverside since yesterday:
https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api

**Comment by hloeung** [comment]
A good start would be to try update the slack-go version to the latest, v0.8.1 - the currently vendored version is v0.6.6. I don't have access to Slack to try it out and test.

**Comment by hloeung** [comment]
https://github.com/42wim/matterircd/pull/401

I just signed up with a test account, even with slack-go v0.6.6, it seems to work for me. So I'm not sure what it is.


![2jz8OyURns](https://user-images.githubusercontent.com/95021/109376310-bacae580-7917-11eb-8bb4-91a418a12c6a.png)
![s3OeniH6CJ](https://user-images.githubusercontent.com/95021/109376311-bbfc1280-7917-11eb-8728-d2e16b99cbb2.png)

**Comment by 42wim** [comment]
> I just signed up with a test account, even with slack-go v0.6.6, it seems to work for me. So I'm not sure what it is.

That's because we are already using the new api everywhere, except for a direct message to a user.
