### ISSUE TITLE
@here messages and threads are NOTICEs and not PRIVMSGs

### ISSUE THREAD

**Issue by axinojolais** [42wim/matterircd#416]
Hi,

It would appear that whenever someone uses `@here`, the message and every message in the same thread are sent as NOTICEs and not PRIVMSGs. Any reason for that ? Can we make them PRIVMSGs ? I see no reason to send them as NOTICEs but I may be missing something.

Thanks !

**Comment by hloeung** [comment]
IMO, it should remain as NOTICEs. It's sort of like any other Mattermost client where @here, @channel, and @all are like broadcasts causing highlighting for those users online at the time.

**Comment by 42wim** [comment]
I agree with @hloeung

**Comment by axinojolais** [comment]
Do other mattermost clients highlight everyone for all messages in a thread where `@here` was used ?
Also, my IRC client (irssi), neither `@here` nor NOTICEs highlight by default, which seems reasonable.

If you look at RFC1459, NOTICEs are used to avoid automatic replies, not to highlight people. And I don't think whole threads should highlight everyone or appear differently in my client because someone used `@here`.

**Comment by hloeung** [comment]
> Do other mattermost clients highlight everyone for all messages in a thread where `@here` was used ?
> Also, my IRC client (irssi), neither `@here` nor NOTICEs highlight by default, which seems reasonable.

Yeah, from https://docs.mattermost.com/help/settings/channel-settings.html#ignore-mentions-for-channel-here-and-all

    By default, you will recieve mention notifications for any uses of @channel, @all or @here in a channel...

How about an option to disable this behavior? https://github.com/42wim/matterircd/pull/418

**Comment by axinojolais** [comment]
> > Do other mattermost clients highlight everyone for all messages in a thread where `@here` was used ?
> > Also, my IRC client (irssi), neither `@here` nor NOTICEs highlight by default, which seems reasonable.
> 
> Yeah, from https://docs.mattermost.com/help/settings/channel-settings.html#ignore-mentions-for-channel-here-and-all
> 
> ```
> By default, you will recieve mention notifications for any uses of @channel, @all or @here in a channel...
> ```

This only talks about messages with `@here`, not all messages in a thread where a single message has `@here`.

> 
> How about an option to disable this behavior? #418

That would make indeed resolve this bug for me :)

**Comment by hloeung** [comment]
> This only talks about messages with `@here`, not all messages in a thread where a single message has `@here`.

Oh! Understand now. So it's actually because the parent message has the channel wide mentions @{here,channel,all) and that gets included in the bit that checks if it should be a NOTICE or not. https://github.com/hloeung/matterircd/commit/a75d1b6599c93df1409c6afcd1c9e5fb442b877f specifically fixes this so it's only whichever message that has @{here,channel,all}.

e.g.

    |21:37 -hloeung:#haw-test- @here Testing again [@@4f7tqoranpgd9bb98itfxt87qw]
    |21:37 <hloeung> This time replying, which shouldn't be an IRC NOTICE message but rather PRIVMSG (re @hloeung: @here Testing again) [↪@@4f7tqoranpgd9bb98itfxt87qw]
