### ISSUE TITLE
Expose port/volume in docker?

### ISSUE THREAD

**Issue by patoupatou** [42wim/matterircd#42]
I'm not very familiar with docker, but shouldn't the dockerfile expose the port for external connections? I'm trying to run matterircd on the same remote host that also runs mattermost with docker.

Best regards

**Comment by 42wim** [comment]
It's not really necessary. If we use expose, the matterircd is accessible from other containers by default. But this doesn't really help you, unless you also run irssi in a container :-)

I should update the documentation though.
To run matterircd just run

```docker run -ti -p 6667:6667 github.com/42wim/matterircd -debug -interface 0.0.0.0```

**Comment by patoupatou** [comment]
Hi 42wim

Thanks for the reply.

Unfortunately I can't connect to the server on port 6667 after running the container. If I run inspircd on port 6667, I can access it, so port is correctly forwarded, but using matterircd, I can't connect to it. That's the latest line that is shown in the console :

`2016-04-07 19:30:57.594 INFO Listening on 127.0.0.1:6667`

Note that I'm connecting to the host remotely, not using localhost, but even using my ip/hostname/6667 it should work right?

BR

**Comment by 42wim** [comment]
Made a mistake in my answer, the correct way to run is
```docker run -ti -p 6667:6667 42wim/matterircd -debug -bind 0.0.0.0:6667```

**Comment by patoupatou** [comment]
Thanks @42wim that worked for running the container. I can then connect to the mini-server remotely. 

However, using weechat as a client, when I try to connect using the LOGIN command, nothing happens (but here's the log on the server) :+1: 

```
2016-04-07 20:40:37.286 DEBUG <- PRIVMSG mattermost :login hostname:8065 teamname username password
DEBU[2016-04-07T20:40:37Z] trying login teamname username hostname:8065 module=matterclient
DEBU[2016-04-07T20:40:37Z] Post https://hostname:8065/api/v1/users/login: http: server gave HTTP response to HTTPS client  module=matterclient
2016-04-07 20:40:37.298 DEBUG -> :mattermost!mattermost@service PRIVMSG irc_nick :Post https://hostname:8065/api/v1/users/login: http: server gave HTTP response to HTTPS client

```

with hostname being the hostname of my server, teamname being the mattermost team name etc.

I can see that the server successfully replies to the ping command to keep the connection alive.

Maybe it's because we're using Mattermost 1.4.x?

BR

**Comment by 42wim** [comment]
You're using an insecure connection (http)
So add -mminsecure
```docker run -ti -p 6667:6667 42wim/matterircd -debug -mminsecure -bind 0.0.0.0:6667```

So documentation or run ```docker run -ti -p 6667:6667 42wim/matterircd -h``` for more info

**Comment by patoupatou** [comment]
Thanks for the help 42wim, it now works correctly!
