### ISSUE TITLE
Support for other client commands?

### ISSUE THREAD

**Issue by patoupatou** [42wim/matterircd#43]
Hi!

I don't know if the API supports it, but changing the username/nickname with /nick would be great. I think most client have that command built-in, along with /part, /topic etc. Coming from irc, I was happy to see that "/topic" is working, it's much faster than doing it the current way in mattermost. 

I'd try to do it myself, but I'm not familiar with Go at all... Anyway, unless it's my client (weechat) that's not supported, here's a list of commands that are not working with weechat atm:

/part (I can't leave the channel with /close or /part in weechat, I have to use the web client for this).
/nick

Maybe there are others, I haven't tested them all...

Thanks for the project, some of us older folks don't want to use the web interface while new users like it, this allows everybody to use their client of choice.

**Comment by 42wim** [comment]
Hi, /part had a bug. Has been fixed in the latest 0.5 release (just released). 
So do a ```docker pull 42wim/matterircd:0.5``` and try ```docker run``` with the 0.5 docker tag 

About the nick changes, mattermost isn't like IRC where you can and will change your nick numerous time. My personal opinion is that if you want to change your nick you should do it in the mattermost interface.

So I'm not going to add support for it myself, but I do accept PR's

**Comment by patoupatou** [comment]
Hi, thank you for the fix, I'll update when possible.

I understand about the nick changes, I guess that's why most other chat web apps don't allow it too.

Also, is it a bug that I don't get private messages as new windows when connecting to matterircd? Channels work well, but if someone sends me a pm, I can't see it unless I use the web app.

Again, thank you for your work, I wish I could help with PR but I'm not familiar with Go at all.

**Comment by patoupatou** [comment]
Oh, I just updated and restarted and private messages now work perfectly... So that is not an issue at the moment!

Best regards,
