### ISSUE TITLE
Enable arm64v8 (and maybe other archs) in Docker Hub

### ISSUE THREAD

**Issue by pfsmorigo** [42wim/matterircd#448]
Hello. The docker images in Docker Hub are only enabled for amd64:
https://hub.docker.com/r/42wim/matterircd/tags?page=1&ordering=last_updated

Can you add support for arm64v8? I did the test locally and it runs fine for that architecture.

**Comment by 42wim** [comment]
Added, not going to add them retro-actively, but master and new releases will have them.
Also available on github container repo: https://github.com/42wim/matterircd/pkgs/container/matterircd
