### ISSUE TITLE
Login fails after upgrading to Mattermost 3.0

### ISSUE THREAD

**Issue by fcremo** [42wim/matterircd#45]
After upgrading Mattermost Platform to version 3.0 matterircd can't login.
The only error message matterircd gives is ```We couldn't find an existing account matching your credentials. This team may require an invite from the team owner to join```
I'm sure I'm using the right team name, login and password.
I couldn't find anything really useful in the logs of both matterircd and Mattermost, let me know what I can do to help troubleshoot this issue.

**Comment by 42wim** [comment]
But you can login on mattermost via web?
Are you using matterircd v0.6?

**Comment by fcremo** [comment]
Yes I can login via the web interface.
I'm using the latest version from `master`. 
The reported version is still 0.5, I think you forgot to update the code (https://github.com/42wim/matterircd/blob/master/main.go#L18) :)

**Comment by 42wim** [comment]
Seems like you're right about the version number ;) 

About the team, you have to use the team name you see in the url, not the team description. Are you sure that's the case? 

Do you have multiple teams? 

Try running with -debug and paste the output, passwords shouldn't be visible, but check to be sure:)

**Comment by fcremo** [comment]
I'm already running with -debug (passwords are visible)
I have only one team, POuL (spelled that way). 
I tried to use both POuL and poul (lowercase as it's in the URL), both didn't work.

**Comment by fcremo** [comment]
```
2016-05-22 01:36:45.803 INFO enabling debug
2016-05-22 01:36:45.803 INFO Listening on 127.0.0.1:6668
2016-05-22 01:36:46.852 INFO New connection: 127.0.0.1:58177
2016-05-22 01:36:46.900 DEBUG <- CAP LS
2016-05-22 01:36:46.900 DEBUG <- NICK **REDACTED**
2016-05-22 01:36:46.900 DEBUG <- USER **REDACTED**
2016-05-22 01:36:46.900 DEBUG -> :matterircd 001 **REDACTED** :Welcome! **REDACTED**
2016-05-22 01:36:46.900 DEBUG -> :matterircd 002 **REDACTED** :Your host is matterircd, running version 0.5
2016-05-22 01:36:46.901 DEBUG -> :matterircd 003 **REDACTED** :This server was created Sun May 22 01:36:46 CEST 2016
2016-05-22 01:36:46.901 DEBUG -> :matterircd 004 **REDACTED** :matterircd 0.5 o o
2016-05-22 01:36:46.901 DEBUG -> :matterircd 251 **REDACTED** :There are 2 users and 0 services on 1 servers
2016-05-22 01:36:46.901 DEBUG -> :matterircd 375 **REDACTED** :- matterircd Message of the Day -
2016-05-22 01:36:46.901 DEBUG -> :matterircd 376 **REDACTED** :End of /MOTD command.
2016-05-22 01:36:46.905 DEBUG <- WHO **REDACTED**
2016-05-22 01:36:46.905 DEBUG -> :matterircd 315 **REDACTED** **REDACTED** :End of /WHO list.
2016-05-22 01:36:47.898 DEBUG <- PRIVMSG mattermost :LOGIN **REDACTED USERNAME** **REDACTED PASSWORD**
DEBU[2016-05-22T01:36:47+02:00] trying login POuL **REDACTED MAIL** **REDACTED HOST**:8065  module=matterclient
DEBU[2016-05-22T01:36:47+02:00]                                               module=matterclient
2016-05-22 01:36:47.932 DEBUG -> :mattermost!mattermost@service PRIVMSG **REDACTED** :We couldn't find an existing account matching your credentials. This team may require an invite from the team owner to join.
```

**Comment by 42wim** [comment]
Are you using ldap logins ?

**Comment by fcremo** [comment]
Nope

**Comment by dogboat** [comment]
@fcremo is your team configured to allow anyone to join it (under the Team Settings -> General Settings -> Allow anyone to join this team)? Our users couldn't connect via matterircd after the upgrade to 3.0, and digging through the code revealed that the vendor'd matterclient.go with matterircd uses an API call that only returns open teams. (I've modified our version to use the all team listing call, so users can log in; not sure if it's a bad idea or not.) Not sure if this is even related, but just a thought.

**Comment by 42wim** [comment]
@dogboat which call do you use?
If the user is joined to the team, it should be able to see the team ;-)

**Comment by dogboat** [comment]
@42wim at [matterclient.go#L116](https://github.com/42wim/matterircd/blob/master/vendor/github.com/42wim/matterbridge-plus/matterclient/matterclient.go#L116) I changed the call from `m.Client.GetAllTeamListings()` to `m.Client.GetAllTeams()`. `GetAllTeamListings()` traces to the SQL query in Mattermost's [SqlTeamStore#GetAllTeamListing()](https://github.com/mattermost/platform/blob/master/store/sql_team_store.go#L280), and `GetAllTeams()` eventually hits up [SqlTeamStore#GetAll()](https://github.com/mattermost/platform/blob/master/store/sql_team_store.go#L228), the same thing without the AllowOpenInvite check.

I'm not sure that this will solve the issue @fcremo is facing (I believe I got the "team not found" error message, not the one they're seeing), and I'm not sure whether it's even a good idea (security issues maybe?), but that's what I did; we were unable to connect prior to that change. Maybe you have a better fix? Thanks so much!

**Comment by fcremo** [comment]
Setting the team to be joinable by anyone didn't work.
I still get the error "We couldn't find an existing account matching your credentials.", trying both with the "real" team name and the lowercase version.

**Comment by 42wim** [comment]
Seems like I indeed didn't loaded the teams correctly, I'm now using GetInititalLoad(), same as the GUI.
Can you rebuild from master and let me know if anything changes ?

**Comment by fcremo** [comment]
Unfortunately, I get the same error as before.
I got the latest version with `cd $GOPATH; go get <url>` (in $GOPATH/bin), is that right? I even deleted all matterircd files from $GOPATH to be sure.

**Comment by dogboat** [comment]
This update keeps things working for my users, though it seems not to be the original issue this ticket was opened for. Sorry to have hijacked the issue. :-\

**Comment by 42wim** [comment]
@fcremo could you login with the browser,  and look for the MMAUTHTOKEN cookie and try to login with that? See https://github.com/42wim/matterircd/issues/29#issuecomment-221116675

**Comment by fcremo** [comment]
Manually setting MMAUTHTOKEN works

**Comment by 42wim** [comment]
Sorry no idea then. It's not that your password/login or team contains non-ascii stuff ? emoticons or utf-8 ?

**Comment by fcremo** [comment]
No, only ascii chars. It's long tough (20 chars), I'm gonna try a shortest password

**Comment by fcremo** [comment]
@42wim I've tried setting a shortest password and it works.
The old password was 3cwV!y$W3CYEmeeCAGyn, maybe the exclamation mark or the dollar symbol could have caused problems?
I bet it has something to do with the length, since all the other matterircd users couldn't login (I'm pretty sure they all use long, random passwords)

**Comment by 42wim** [comment]
Just changed the password on my account to exact the same as yours. 
It worked fine, i'm thinking that maybe it's your ircclient that must be interpreting it. (i'm using irssi)

But that should also mean that the password in the PRIVMSG in the debuglog should be different.

**Comment by fcremo** [comment]
The password in the debug log is correct..
I tried using hexchat and znc, both didn't work.

**Comment by 42wim** [comment]
Ok, installed hexchat, works fine. I'm running matterircd from master and mattermost version 3.0.2. What's your mattermost version ? If you set the long password again, it still stops working?

**Comment by fcremo** [comment]
Version 3.0.2
I changed the password back to the old one and it worked. What could be causing this? I'm gonna ask other users to test if this works also for them.

**Comment by 42wim** [comment]
No idea, and I can't reproduce it. Closing this for now because your issue is fixed :-)
