### ISSUE TITLE
Binaries missing for v0.6

### ISSUE THREAD

**Issue by yitzhaq** [42wim/matterircd#46]
There seem to be no binaries published for v0.6, as there have been for all previous releases.

No big issue, of course, since we could just build it ourselves. But we'd rather not set up a Go dev environment if we don't have to :)

**Comment by 42wim** [comment]
Ok, I thought most of the people were using docker ;-) I'll add the binaries later.

**Comment by 42wim** [comment]
Binaries added for v0.6.1
