### ISSUE TITLE
Problems in combination with matterbridge

### ISSUE THREAD

**Issue by stefanct** [42wim/matterircd#462]
We are using matterbridge (1.25.0) to relay between a mattermost and a pantalaimon (matrix) instance, respectively.
This works mostly fine but there are two issues I have recognized so far that I think are due to matterbridge's format of certain messages. They aren't a big issue within mattermost itself but become more annoying when further relayed to matterircd users. (We are using matterircd 0.24.2 2a879fb btw if that matters).

The first one is with embedded images. When posted by someone behind the matterbridge, they are displayed like this:

![image](https://user-images.githubusercontent.com/457881/164990564-b943636e-9e38-4a99-890f-8652b4e84aa7.png)

The problem here is that in IRC the user name and the image URL are separate messages because the nickname is similar to a message associated with the picture, which is also printed as its own message by matterircd:

![image](https://user-images.githubusercontent.com/457881/164990894-18138b77-2423-4e79-b253-58cdbbcf77e4.png)

It would be much better if the message and the download url would be printed together in one line. That way the IRC client could easily massage the message into something that looks more native (I am doing so in hexchat with [this plugin](https://github.com/Shlygly/External-Bridge-Adaptor) for normal text messages).

The second thing is replies with quotes.
Similarly to the image problem, when replying to a message, the nickname ends up on its own line in IRC. However, in that case it is even worse as the <nickname> line is posted *after* the actual message. This might be an additional bug though, I presume.

![image](https://user-images.githubusercontent.com/457881/164991848-ecffeca6-8ab7-40fc-abc6-6f071b53e95a.png)

![image](https://user-images.githubusercontent.com/457881/164991951-c494948f-7d2a-4b27-b090-14ebda73d93a.png)

This works fine if the reply does not come via the bridge but directly from MM. So maybe some of above could be considered matterbridge bugs instead of a matterircd problems but it might not be easily fixable there and the issues are way more apparent in IRC.

**Comment by hloeung** [comment]
> The first one is with embedded images. When posted by someone behind the matterbridge, they are displayed like this:
> 
> ![image](https://user-images.githubusercontent.com/457881/164990564-b943636e-9e38-4a99-890f-8652b4e84aa7.png)
> 
> The problem here is that in IRC the user name and the image URL are separate messages because the nickname is similar to a message associated with the picture, which is also printed as its own message by matterircd:
> 
> ![image](https://user-images.githubusercontent.com/457881/164990894-18138b77-2423-4e79-b253-58cdbbcf77e4.png)
> 
> It would be much better if the message and the download url would be printed together in one line. That way the IRC client could easily massage the message into something that looks more native (I am doing so in hexchat with [this plugin](https://github.com/Shlygly/External-Bridge-Adaptor) for normal text messages).

That would be this bit of code - https://github.com/42wim/matterircd/blob/master/mm-go-irckit/userbridge.go#L713 & https://github.com/42wim/matterircd/blob/master/mm-go-irckit/userbridge.go#L737

The thing is, a single post can have multiple files attached. The code displays the message associated with that post first then for each file attached, displays the link. So e.g of a post with two attachments.
```
|20:01 <hloeung> Testing [fqc8…]
|20:01 <hloeung> download file - https://chat..../api/v4/files/hrqbnm4ysi8xpqy78ns4imbuao [fqc8…]
|20:01 <hloeung> download file - https://chat..../api/v4/files/uk4dw8476jg7mmk8e14g4hkfja [fqc8…]
```
 
> The second thing is replies with quotes. Similarly to the image problem, when replying to a message, the nickname ends up on its own line in IRC. However, in that case it is even worse as the line is posted _after_ the actual message. This might be an additional bug though, I presume.
> 
> ![image](https://user-images.githubusercontent.com/457881/164991848-ecffeca6-8ab7-40fc-abc6-6f071b53e95a.png)
> 
> ![image](https://user-images.githubusercontent.com/457881/164991951-c494948f-7d2a-4b27-b090-14ebda73d93a.png)
> 
> This works fine if the reply does not come via the bridge but directly from MM. So maybe some of above could be considered matterbridge bugs instead of a matterircd problems but it might not be easily fixable there and the issues are way more apparent in IRC.

Is this still a problem with the latest `matterircd`? One with the changes that doesn't split the lines per this PR https://github.com/42wim/matterircd/pull/482 ?

**Comment by 42wim** [comment]
Closed as no response
