### ISSUE TITLE
Doesn't work anymore, with JSON error

### ISSUE THREAD

**Issue by trou** [42wim/matterircd#47]
When trying to login to a MM 2.2.0.6671, with both matterircd 0.6 and 0.5 I get :
```
DEBU[2016-05-24T14:21:07+02:00] invalid character '<' looking for beginning of value  module=matterclient
DEBU[2016-05-24T14:21:07+02:00] LOGIN: %s, reconnecting in %sAppErrorFromJson: model.utils.decode_json.app_error, invalid character '<' looking for beginning of value 1.290908556s  module=matterclient
```

**Comment by 42wim** [comment]
This is usually the case when the client is connecting to a port that isn't listening.
e.g if you're trying to connect to HTTP mattermost without specifying to -mminsecure flag or connecting to a HTTPS mattermost but having the -mminsecure flag specified.

**Comment by trou** [comment]
I try to connect to HTTPS, but without -mminsecure. `strace` show it connects to port 443. Maybe a certificate issue ?

**Comment by 42wim** [comment]
Yes, I think selfsigned certificates don't work.

**Comment by trou** [comment]
is there a way to actually determine if this is the issue ?

**Comment by 42wim** [comment]
seems like the '<' is that you're receiving a HTML tag instead of JSON data, are you sure you're using the matterircd v0.5 binary ?

Try curl https://yourserver/api/v3/users/login this should give a JSON error back.

**Comment by trou** [comment]
OK I get it.
I was running it with : `./mattermost -mmserver domain/team`  instead of `./mattermost -mmserver domain`
I was mislead by the usage string as I understood `server/instance` as `server/team`

Sorry for the noise and thanks a lot for the tool, it makes using MM bearable ;)
