### ISSUE TITLE
Could matterircd please respond to the "CAP LIST" request?

### ISSUE THREAD

**Issue by shindere** [42wim/matterircd#476]
By default, the `irssi` IRC client sends a `CAP LIST` message before sending
the `NICK` and `USER` messages.

Since `matterircd` does not respond to `CAP LIST` the user registration
cannot happen with `irssi` in its default mode.

`irssi` has the `-nocap` option to its `connect` command to ask it not to 
send the `CAP LIST` message but this option is currently not
documented in its interactive help system and, as far as I can tell,
there is no way to store it in `irssi`'s
configuration for a given chatnet,
making it impossible e.g. to autoconnect, because the connection
has to be run manually so that one can pass the `-nocap` option.

It would make things way simpler for end-users if `matterircd` could simply
honour the `CAP LIST` message.

**Comment by hloeung** [comment]
Can't you use `no_cap = "yes";` in ~/.irssi/config (or whatever path your irssi is configured to use)?

**Comment by shindere** [comment]
Haw Loeung (2022/10/03 23:50 -0700):
> Can't you use `no_cap = "yes";` in ~/.irssi/config (or whatever path
> your irssi is configured to use)?

I was not aware of the existence of this variable, thanks. Where should
I have foundit in the interactive help?

To give an example, `/help connect` does not, on my system, document the
`-nocap` flag.

**Comment by hloeung** [comment]
Probably missing upstream in the irssi project. I used adding / connecting via irssi then `/save` to see what configs would be written out to disk in `~/.irssi/config`.

**Comment by shindere** [comment]
Haw Loeung (2022/10/11 13:32 -0700):
> Probably missing upstream in the irssi project. I used adding /
> connecting via irssi then `/save` to see what configs would be written
> out to disk in `~/.irssi/config`.

Are you saying that if you connect with `-nocap` and then /save then the
fact that nocap was used to connect will be saved?

But frankly, in my opinion this does *not* address the issue. It took me
incredible time to find out that I had to use nocap. What would be wrong
in simply patching matterircd so that it can deal properly with hte CAP
request?

**Comment by hloeung** [comment]
> Are you saying that if you connect with `-nocap` and then /save then the fact that nocap was used to connect will be saved?

Yep. That's how I found it and that's what I'm using right now.


> But frankly, in my opinion this does *not* address the issue. It took me incredible time to find out that I had to use nocap. What would be wrong in simply patching matterircd so that it can deal properly with hte CAP request?

No objection from me. Didn't know it was part of the IRC standard until upgrading to the latest irssi broke for me.

**Comment by 42wim** [comment]
Thanks to @hloeung this is now in master

**Comment by shindere** [comment]
Thanks! Just for the record it's PR #478.
Looking forward to the next release!
