### ISSUE TITLE
Increasing file descriptor usage requires restart

### ISSUE THREAD

**Issue by dogboat** [42wim/matterircd#48]
Our setup: CentOS 7.2 running Mattermost behind nginx; matterircd on the same box. 16 users total, 4 connected through matterircd.

After some period of time (dependent on amount of chatting that occurs), matterircd will refuse to accept any further connections. Following the logs and watching the /proc/<matterircd_pid>/fd directory, it appears that some file descriptors are created with each message sent, but they don't always go away; used descriptor count increases until 1024 (the soft limit for the process), at which point the "connection refused" messages start to appear and the process must be restarted.

Inspection of the output of `lsof -p <matterircd_pid>` reveals many TYPE: sock and NAME: TCP sockets open (not in a connected state or listing connection source/destination); `ls -al /proc/<matterircd_pid>/` lists up to 1024 descriptors before the process must be restarted.

Not sure if this is actually an issue with matterircd or one of the libraries it uses.

Thanks!

**Comment by 42wim** [comment]
Interesting.. I've traced it back to mattermost API not closing the http body correctly.
Are you willing to run a test version ? If so can you build it yourself, or do you need a binary ?

**Comment by dogboat** [comment]
Absolutely! I can build it myself, whatever's easiest for you! Thanks so much!

**Comment by 42wim** [comment]
Ok, I've pushed the fix into master (hopefully this will get into mattermost too, if it works for you :)
It now has (in my case) maximum 2 FD's per client open to mattermost server.

**Comment by dogboat** [comment]
Seems to be working for us! Awesome, thanks so much!

**Comment by 42wim** [comment]
Ok, great to hear, hopefully upstream adds the fixes.
