### ISSUE TITLE
Unable to reply to a multi-line message using any line's short thread ID

### ISSUE THREAD

**Issue by kot0dama** [42wim/matterircd#480]
When using short thread IDs, if someone sends a multi-line message, matterircd sends the messages to the client with auto-incremented short IDs for each line of the message.

Then when an IRC user wants to reply to the thread, it seems they need to use the last short thread-ID only, else matterircd will fail to detect which thread it belongs to, and will send @@xxx prefix in the message, without a warning it could not find the thread ID.

Also, there is absolutely no indication that a received line is part of a multi-line message, or that every line of these message belong to a specific thread ID, hence there is no way for a user to know they should reply using the last message's thread ID.

Example from IRC client side:
![matterircd_threadid_issues_hexchat_side](https://user-images.githubusercontent.com/89980752/195733103-a5f7ed18-7ac4-43fb-9cc1-85942501c8db.png)

From Mattermost side:
![matterircd_threadid_issues_mm_side](https://user-images.githubusercontent.com/89980752/195733063-af69dbfc-49cd-429e-8011-098ab622ab66.png)

Thank you

**Comment by 42wim** [comment]
Try PR #482 this should fix the issue

**Comment by kot0dama** [comment]
Thanks for this, now we can clearly identify multi line messages.

Although, if I might nitpick, this change breaks 2 things:
 * message highlighting by IRC clients as only the last line gets the `mention` bit. 
 * plugins coloring thread IDs by their number to help the user identify threads messages as the thread ID is not prefixed to every line

Maybe we need to also prefix current thread ID and suffix `re:` / `mention` items when breaking the line before sending to IRC ?

**Comment by kot0dama** [comment]
Nice, thanks!
I think having mentions on only one line is OK, it's just that we had them on every line of a multi-line message before the change.
