### ISSUE TITLE
matterircd dies when pm'ed

### ISSUE THREAD

**Issue by popey** [42wim/matterircd#49]
The matterircd seems to die pretty regularly for me. I note in the log this time that it died immediately after someone pm'ed the mattermost user.

2016-05-30 02:51:09.987 DEBUG -> :matterircd PONG matterircd
2016-05-30 02:51:22.903 DEBUG <- PRIVMSG mattermost ty
panic: runtime error: index out of range

goroutine 85 [running]:
panic(0x92c9e0, 0xc8200100a0)
        /nasfs/users/u0022146/.gvm/gos/go1.6.2/src/runtime/panic.go:481 +0x3e6
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).handleMMServiceBot(0xc8200e4000, 0xc8200e40e0, 0x0, 0x0)
        /tmp/go7/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:398 +0x1e11
created by github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*server).handle
        /tmp/go7/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/server.go:797 +0x54f1

**Comment by 42wim** [comment]
Seems like an irc client that doesn't follow RFC, should normally be ```PRIVMSG mattermost :ty``` instead of ```PRIVMSG mattermost ty```

What irc client is this?

**Comment by 42wim** [comment]
Ok, fixed in master and I'll release a new version later.
