### ISSUE TITLE
Crashes on joining channel that doesn't exist

### ISSUE THREAD

**Issue by lindskogen** [42wim/matterircd#51]
Joining the `#tjenna` channel (which doesn't exist) crashes the server 

Logs from two runs:
- http://pastebin.com/dwmU6KA4
- http://pastebin.com/nb00HHH2

**Comment by 42wim** [comment]
Hi, thanks for reporting. Fixed in master now

**Comment by lindskogen** [comment]
That's some quick work! Thanks!
