### ISSUE TITLE
Protocol error, PRIVMSG missing semicolon for empty lines

### ISSUE THREAD

**Issue by kot0dama** [42wim/matterircd#516]
Using current master branch code, bip sometimes closes the connection to matterircd with:
` ERROR: [mattermost] Error in protocol, closing...`

Debug shows PRIVMSG lines without semicolon, which does not seem to be valid per the RFC:
`matterircd[950399]: time="2022-11-30T07:17:51+01:00" level=debug msg="-> :stg-is-review-bot!stg-is-review-bot@stg-is-review-bot PRIVMSG #is-private-reviews" module=matterircd`

This one is a bot we've started using recently for showing diffs.
I think this is happening when a client is sending empty lines.

I was able to test having that bot send empty lines with a previous version of matterircd (master branch from 2022-11-02), which sends:
`matterircd[952368]: time="2022-11-30T07:54:30+01:00" level=debug msg="-> :stg-is-review-bot!stg-is-review-bot@stg-is-review-bot PRIVMSG #is-private-reviews :\n" module=matterircd`

I think this could be fallout from the work on multiline messages.

**Comment by hloeung** [comment]
This is fallout from commit https://github.com/42wim/matterircd/commit/2ddb0d44007efa229ae968b434ebe096a0d2340c. If the protocol/spec requires colon, I'm not sure why this is optional in the https://github.com/sorcix/irc package.

Anyways, https://github.com/42wim/matterircd/pull/517 fixes this.
