### ISSUE TITLE
Too many established connections

### ISSUE THREAD

**Issue by allesan** [42wim/matterircd#52]
I'm using 0.6.1 version and after a very short time I get several hundred ESTABLISHED connections on my server between mattermost service nad matterircd, which causes my mattermost service to hang because of too many connections.
Has anyone seen this behaviour?

**Comment by 42wim** [comment]
Probably related to https://github.com/42wim/matterircd/issues/48? 
Fixed in 0.7

**Comment by allesan** [comment]
It looks so!
Thanks
