### ISSUE TITLE
MatterIRD and Tailscale issues

### ISSUE THREAD

**Issue by packetgeek** [42wim/matterircd#536]
In building a college cyber club network with Tailscale, ran across an issue where MatterIRCd does not want to connect to Mattermost via a tailnet (100.0.64.x IP space).  It returns a "version not supported" error.  

The work-around is to set the Server address in matterircd.toml to Mattermost's "real" IP address (implying that MatterIRCd and Mattermost are hosted in the same 192.168.x.x network segment) and then I can connect (via the tailnet) to either: Mattermost via a browser or MatterIRCd via a IRC client.  Just can't get MatterIRCd to talk to Mattermost via the tailnet.

This is probably low priority as the work-around is functional.  Just thought y'all would be interested.

**Comment by hloeung** [comment]
Can you include the Matterircd version used? Also, enable DEBUG and TRACE logging and include these logs?

I'm guessing it may be some TLS/SSL exchange failing over the Tailscale network.

**Comment by packetgeek** [comment]
Figured it out.  Issue was PEBCAK.  Had to set DefaultServer to "127.0.0.1:8065" in the Mattermost section of MatterIRCd's toml file.  Please close this.
