### ISSUE TITLE
Support for Mattermost 8

### ISSUE THREAD

**Issue by crhalpin** [42wim/matterircd#537]
When attempting to connect to an MM8 instance with matterircd built from the latest master: `mattermost version 8.0.0.8.0.0.410fdea84fd52914649fe21d1dee1484.false not supported`

**Comment by CountMurphy** [comment]
Getting the same error message

**Comment by hloeung** [comment]
Think it works with 26 is because strict version support checking was added in https://github.com/42wim/matterircd/commit/da742e9031eb10125da2c45b42ce6acc1f7122bf

I think perhaps an option to ignore versions (use at your own risk) could be implemented in addition to support for Mattermost 8.

**Comment by 42wim** [comment]
Fixed in 0.27.1 just released
