### ISSUE TITLE
MatterIRCD v0.8 Crashes on quit

### ISSUE THREAD

**Issue by dwest-galois** [42wim/matterircd#54]
I have run into an issue where MatterIRCD v0.8 seems to crash whenever someone disconnects their IRC client from the service.  I have tested this with both "irssi" as well as "weechat".  In "irssi", I get the following error message after using either "/quit" or "/disconnect".

```GLib warning: SSL read error: server closed connection unexpectedly```

In "weechat", I do not get that error message, but the daemon still crashes all the same.  I also tested this without using SSL and the daemon still crashes, just without the "SSL read error".   I have debugging turned on and was able to capture the the following errors from it:

```
Jun 29 08:07:08 white matterircd: time="2016-06-29T08:07:08-07:00" level=error msg="error:read tcp [redacted IPv6 Address]:45430->[redacted IPv6 Address]:443: use of closed network connection" module=matterclient
Jun 29 08:07:08 white systemd: matterircd.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 29 08:07:08 white systemd: Unit matterircd.service entered failed state.
Jun 29 08:07:08 white systemd: matterircd.service failed.
Jun 29 08:07:08 white matterircd: panic: runtime error: invalid memory address or nil pointer dereference
Jun 29 08:07:08 white matterircd: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x5fb347]
Jun 29 08:07:08 white matterircd: goroutine 27 [running]:
Jun 29 08:07:08 white matterircd: panic(0x7d6040, 0xc420010060)
Jun 29 08:07:08 white matterircd: /usr/local/go/src/runtime/panic.go:500 +0x1a1
Jun 29 08:07:08 white matterircd: github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge-plus/matterclient.(*MMClient).GetChannelName(0x0, 0xc4203a63e0, 0x1a, 0xc42001aee8, 0x1)
Jun 29 08:07:08 white matterircd: /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge-plus/matterclient/matterclient.go:252 +0x37
Jun 29 08:07:08 white matterircd: github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).checkWsActionMessage(0xc4200d21e0, 0xc42041dae0)
Jun 29 08:07:08 white matterircd: /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:279 +0xb6
Jun 29 08:07:08 white matterircd: github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).handleWsMessage(0xc4200d21e0)
Jun 29 08:07:08 white matterircd: /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:172 +0x1b4
Jun 29 08:07:08 white matterircd: created by github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).loginToMattermost
Jun 29 08:07:08 white matterircd: /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:73 +0x429
```

The service does not crash when I use MatterIRCd v0.7, so it looks like the problem was introduced in the v0.8 release.

**Comment by 42wim** [comment]
I can't reproduce it, seems like a race condition. Does it happen every time? or just random ?
I released a test version, could you see if this fixes it for you?

https://github.com/42wim/matterircd/releases/tag/v0.8.1test

**Comment by dwest-galois** [comment]
I was able to consistently reproduce it on two different systems and it happened every time I disconnected my client.  I tested this in both v0.8.1test and 0.9-dev and this issue seems to be resolved with them.  Thank you very much.
