### ISSUE TITLE
Need new release with Mattermost 9 support

### ISSUE THREAD

**Issue by kkofler** [42wim/matterircd#556]
Mattermost 9 has now been out for more than a month (released 2023-09-15). It is also included with the latest release of GitLab, GitLab 16.5 released 2023-10-22. But the latest matterircd release, matterircd 0.27.1, does not accept Mattermost 9 as a valid version, and also does not include the option to skip the version check (which was added a day after the release). So we need updated binaries ASAP.

**Comment by 42wim** [comment]
@kkofler I'll do a release tomorrow

**Comment by kkofler** [comment]
> @kkofler I'll do a release tomorrow

Ping?

**Comment by kkofler** [comment]
Works great, thanks!
