### ISSUE TITLE
No communication on channels

### ISSUE THREAD

**Issue by aedrax** [42wim/matterircd#56]
mattermost: 3.1.0
matterircd: 0.8.1

After logging in, there isn't an auto-login to any channel, and manually going to a channel opens on the IRC client, but doesn't show any messages in mattermost and vice versa.

**Comment by 42wim** [comment]
Can you run matterircd with -debug and paste the output here (filter privacy related stuff first if needed)

**Comment by aedrax** [comment]
My mistake, I did not realize it was trying to connect with HTTPS until I ran with the debug option, that is when I noticed the -mminsecure option. Upon running it with -mminsecure everything worked as expected. I am sorry about that!
