### ISSUE TITLE
Receiving files on DM creates a channel

### ISSUE THREAD

**Issue by dodys** [42wim/matterircd#571]
I'm using the latest docker image of matterircd. In my case I'm using matterircd together with ZNC.

Whenever someone sends me a file in a DM, I receive normally the link to the file in the DM, but I see that a channel is created with that person and the channel names is our ids. For example (ids ommited):
[02/07/2024 09:54:50] * Now talking on <uid1>__<uid2>

Is this an issue on matterircd? 

I believe my config doesn't have any debug on currently, let me know what you need in terms of logs, I can reproduce it easily.

**Comment by hloeung** [comment]
I think this is fallout from https://github.com/42wim/matterircd/commit/b762e5eb9dcb25225fb5493e4e7340176fd583a8

**Comment by hloeung** [comment]
Still an issue.

**Comment by hloeung** [comment]
Oops, it's not. I was using a branch that did not include this fix.
