### ISSUE TITLE
DM messages from Web client show up as DMs from myself or not showing at all.

### ISSUE THREAD

**Issue by dodys** [42wim/matterircd#572]
This issue has been happening for a long time, way before I moved to the docker image of matterircd.

Whenever I have my IRC client connected to matterircd via znc and for some reason I try to reply to a DM in Mattermost Web client, instead through the bridge, I receive my message as coming from myself instead of appearing in the open DM with such person.
Also if the IRC client is closed and I'm only using the Mattermost Web client to exchange DMs, whenever I start the IRC client again I see all the DMs I received, but not my own sent messages in such DM.

This only happens in DMs, not an issue with channels.

Let me know about configuring debugging so I can upload logs

**Comment by hloeung** [comment]
Are you able to try this with the IRC client directly connected to matterircd? This is to take znc out of the loop.

**Comment by hloeung** [comment]
Searching through various matterircd bugs for ZNC, I found this one which might be the same thing you're running into? https://github.com/42wim/matterircd/issues/296

Also, it references the upstream bug against ZNC https://github.com/znc/znc/issues/1638

**Comment by dodys** [comment]
> Are you able to try this with the IRC client directly connected to matterircd? This is to take znc out of the loop.

yes, same happen if connected directly to matterircd.

**Comment by dodys** [comment]
btw, I forgot to mention but the irc client currently being used is hexchat.

**Comment by hloeung** [comment]
> 1. if the irc client is disconnected from matterircd (with or without znc) any DM sent via the Web client does not appear after connecting to matterircd.

I think I know why this is happening.

When you use the web client, it updates the server on the last seen, so on reconnecting, the reply works this out and uses the server's known rather than what's stored to show list of messages missed. This is in the lines of code below:

https://github.com/42wim/matterircd/blob/master/mm-go-irckit/userbridge.go#L683


> 2. if the irc client is connected to matterircd (with or without znc) and DM sent via the Web client shows up as a DM from myself.

Interesting. Any chance you could provide DEBUG/TRACE logging output?

**Comment by dodys** [comment]
I've talked to @hloeung and we got to the conclusion that this could be an issue with hexchat.
Since hexchat is now dead, I've tried to reproduce this issue with quassel and I can confirm this is not the case anymore. Therefore I'm closing this as not planned.
