### ISSUE TITLE
Mattermost command examples

### ISSUE THREAD

**Issue by caywin25** [42wim/matterircd#577]
Hello thanks for your work
matterircd is wonderful.

I configured it to mattermost.
Could you tell me what are the commands to reply to a person in a thread please?

How to add a reaction or how to edit a word or delete it please?
Is it possible to upload files ?

I use weechat.
Thanks

**Comment by caywin25** [comment]
nobody ? :(

**Comment by hloeung** [comment]
Have you seen https://github.com/42wim/matterircd/blob/master/prefixcontext.md ?

That outlines and has examples on how to reply to posts in threads, how to add reactions, and how to modify a post to edit or delete.

As for uploading files, there isn't any options to do so at present.

**Comment by caywin25** [comment]
Ow !! Perfect thank you :)
