### ISSUE TITLE
SSL auth

### ISSUE THREAD

**Issue by sheepherd** [42wim/matterircd#58]
Is it possible to implement SSL auth as described here? https://www.oftc.net/NickServ/CertFP/#AddCertFPtoNS

That way you don't have to login by plaintext.

**Comment by 42wim** [comment]
Looks interesting. 
But maybe it's something that can be better done by an API at Mattermost side (accepting client certificates for authentication).

**Comment by sheepherd** [comment]
Alright, I will forward this question to the Mattermost team. Thank you.
