### ISSUE TITLE
Broken on Mattermost 10?

### ISSUE THREAD

**Issue by dfskoll** [42wim/matterircd#584]
Hi,

I recently upgraded to Mattermost 10 and matterircd no longer seems to work.  My irc bot can no longer connect.  I don't have any other useful info, unfortunately, but I can try to debug if someone gives me pointers.

Regards,

Dianne.

**Comment by hloeung** [comment]
Yep, that fix in the PR or `ignoreserverversion = true` per https://github.com/42wim/matterircd/pull/541

I've approved and landed your PR. Thanks!
