### ISSUE TITLE
Handle IRC and Mattermost mention differences

### ISSUE THREAD

**Issue by paddatrapper** [42wim/matterircd#60]
It would be nice if matterircd could automatically strip and add the "@" in front of nicks - strip them for displaying in IRC and add them when replying from IRC where @<nick> is not often able to be autocompleted (for example Weechat does not have @\<partial-nick\>\<TAB\> complete to @<nick>, nor does @\<nick\> highlight in IRC has it doesn't match my nick).

**Comment by 42wim** [comment]
I don't know if you really want to use ```@``` everytime on mattermost. Because this actually sends a notification too the user. You wouldn't want to do this for every message, this gets annoying quickly :)

**Comment by paddatrapper** [comment]
I didn't realise not doing so highlighted the user... TIL thanks!
