### ISSUE TITLE
Doesn't seem to work with latest 3.3.0 mattermost instance

### ISSUE THREAD

**Issue by patoupatou** [42wim/matterircd#61]
I just updated to [this](https://docs.mattermost.com/administration/changelog.html#release-v3-3-0) version and the matterircd docker image doesn't seem to work anymore. I tried both latest and 0.9 tags.

Here's the error I get whenever I send a message in the client (I do manage to connect to matterircd and send commands to the mattermost user). After the login, I do connect to all the channels I'm part of, but I don't see any messages nor can I send any of them.

```
You are trying to use a route that requires a team_id, 
        	but you have not called SetTeamId() in client.go
time="2016-08-15T20:34:06Z" level=debug msg="-> :mattermost!mattermost@mattermost PRIVMSG epatpol :msg: test \u200b could not be send: AppErrorFromJson: model.utils.decode_json.app_error, EOF" module=matterircd 
```

Thanks!

**Comment by 42wim** [comment]
Yes, mattermost 3.3.0 broke their API again.  (btw this info is in the README.md ;-)
The current master works with 3.3.0 and the dockerhub image is rebuilding as I type. The latest tag should work now with 3.3.0

If you need it outside of docker image you'll have to build the binaries yourself for now.

**Comment by patoupatou** [comment]
My bad for not reading the README.md, thanks for the heads up @42wim!
