### ISSUE TITLE
Mode command without enough arguments crashes the server

### ISSUE THREAD

**Issue by adam-gambitresearch** [42wim/matterircd#62]
INFO[2016-08-18T15:25:52+01:00] login succeeded                               module=matterircd
panic: runtime error: index out of range

goroutine 21 [running]:
panic(0x938900, 0xc82000e0e0)
	/usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.CmdMode(0x7fa5426a1090, 0xc82016a000, 0xc820174000, 0xc820426000, 0x0, 0x0)
	.../src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/server_commands.go:129 +0x6b3
_github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.commands.Run(0xc820152060,_ 0x7fa5426a1090, 0xc82016a000, 0xc820174000, 0xc820426000, 0x0, 0x0)
	.../src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/commands.go:54 +0x35b
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*commands).Run(0xc820154008, 0x7fa5426a1090, 0xc82016a000, 0xc820174000, 0xc820426000, 0x0, 0x0)
	<autogenerated>:45 +0xc3
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*server).handle(0xc82016a000, 0xc820174000)
	.../src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/server.go:349 +0x326
created by github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*server).Connect
	.../src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/server.go:254 +0xa3

Crash happens here:

127: func CmdMode(s Server, u *User, msg *irc.Message) error {
128: 	modetype := ""
129: 	channel := msg.Params[0]

Client sent:

MODE :&users\r

**Comment by 42wim** [comment]
Thanks, fixed in v0.9.1 release. 
What client does this ? or was this done manually?

**Comment by adam-gambitresearch** [comment]
The client was supybot. I encountered the crash while writing a plugin to get it to send the login command to matterircd.

I think the MODE command takes 0 or more parameters, so this is a valid command.

**Comment by dm8tbr** [comment]
Sorry for the noise, but this is literally the single search engine result for "supybot matterircd".

@adam-gambitresearch would it be possible to share that supybot plugin? If you got that to work, that is. I'm in that situation and looking at having supybot talk to mattermost/matterircd.

**Comment by adam-gambitresearch** [comment]
Sure. I've just split it out into its own repo here:

https://github.com/adam-gambitresearch/supybot-matterircd

I only did the bare minimum to get this to work (in particular, I haven't made it read the username and password from the config, I just add them to plugin.py. :()

**Comment by dm8tbr** [comment]
Awesomesauce! Thanks! If I get around to improving it I'll send PRs.
