### ISSUE TITLE
Config by file or with ENV variables

### ISSUE THREAD

**Issue by nicolas-brousse** [42wim/matterircd#63]
It could be nice to have a `--config` options to precise a file with a configuration inside.  
And/Or have the possibility to set options by ENV variables like `export MI_BIND = "0.0.0.0:6667"`.

I think of this mainly about Docker usage. To have an easy way to update the container without loosing the options.
In my case I use my Synology to run `matterircd` with Docker and I do it with a UI. Each time a want to update or change the configuration I have to delete then create a new container.

But I think it could be useful in other cases.

What do you think about it?

**Comment by 42wim** [comment]
Sure, ENV or a config-file would be nice to have. 

But I don't understand your problem:

> In my case I use my Synology to run matterircd with Docker and I do it with a UI. Each time a want to update or change the configuration I have to delete then create a new container.

I don't see why you can't start the container with the options you need without deleting the container?

**Comment by nicolas-brousse** [comment]
May be it was not clear. I can start the container without problems. It's just that if I want to change the the options, I have to create a new container with the new command to run.

Also it's annoying for me now because I'm doing tests, so I recreate the container often.
Well I don't know why I didn't tried on my laptop first ...

Any cases I think config-file and ENV could be nice yes :)
So if you too that's cool!

**Comment by 42wim** [comment]
I don't really see the issue with destroying / starting a container again :-)
But if you really want to reuse the container you can do for example this:

On the docker-host, create a file containing your options, for example in /tmp 

```
cat /tmp/matterircd.ash
```
```
#!/bin/ash
/bin/matterircd -option1 -option2
```
```
chmod 755 /tmp/matterircd.ash
```

Run the container with the script as entrypoint
```
docker run --name matterircd -v /tmp/matterircd.ash:/matterircd.ash --entrypoint=/matterircd.ash 42wim/matterircd:latest
```

Now when you edit the /tmp/matterircd.ash script and restart the container it'll use the new script (and new options)

**Comment by nicolas-brousse** [comment]
It's is a bit long to create a container with the Synology UI. More than executing a simple docker run command :)

But you write for the shell file. I don't know why I didn't think about it.
Thanks!

**Comment by slowbro** [comment]
I've been thinking about picking this one up, too. What's a preferred syntax/'language' for config files? I'm partial to YAML, but I'm not sure if it's the "Go Way" :)

**Comment by 42wim** [comment]
@slowbro That would be nice :) 

I prefer to use toml for config files (I also use it in https://github.com/42wim/matterbridge). It's easier (less mistakes) for endusers than yaml. 

You can get some inspiration from 
https://github.com/42wim/matterbridge/blob/master/bridge/config/config.go#L142 for config file
and
https://github.com/42wim/matterbridge/blob/master/bridge/config/config.go#L172 for environment overrides

**Comment by slowbro** [comment]
Great, thanks! I'll see what I can get done :)

**Comment by slowbro** [comment]
Hey there, I put in a PR for my change. Let me know what you think.

**Comment by 42wim** [comment]
Thanks to @slowbro this is now working
See https://github.com/42wim/matterircd/blob/master/matterircd.toml.example for a sample config
For now still in master, but a 0.16.0 version will be out soon
