### ISSUE TITLE
Mattermost slash commands support

### ISSUE THREAD

**Issue by nicolas-brousse** [42wim/matterircd#64]
Does matterircd supports the Mattermost slash commands?

**Comment by 42wim** [comment]
No, irc clients also don't support misc slash commands. You'll have to use /quote or /raw for this to work.

**Comment by nicolas-brousse** [comment]
Ah ok I didn't know this. Thanks for the tip about `/quote` and `row` command :)

**Comment by nicolas-brousse** [comment]
Looks like matterircd don't support `/quote` and `raw` comands.
