### ISSUE TITLE
Joining channels

### ISSUE THREAD

**Issue by 2-B** [42wim/matterircd#65]
matterircd Version: 0.10.0
mattermost Version 3.3.0

When I connect, I get automaticaly joined the channel #town-square. When I write the command <code>/join #test</code> I get joined the channel <code>test</code> and not <code>#test</code>.
If now somebody writes me a message (via webfrontend in the channel #test, with @user), I'll receive this message as a private message from the user and not in the channel. Sometimes also I get automatically joined to the channel #test. I don't understand the exact behaviour.

**Comment by 42wim** [comment]
I can not reproduce this, you get automatically joined to all the channels you're a member from.
It's not possible to join another channel (you'll get a invite only error message)
(eg ``` -> :matterircd 473 wim #test :Cannot join channel (+i)  module=matterircd```)

Could you run matterircd with -debug and paste the output (filter personal info if you need)

**Comment by 2-B** [comment]
I have the right to join channel #testing, so I do <code>/join #testing</code> and after I get joined to channel testing and not #testing.
```
Aug 31 08:07:13 dagaz matterircd-linux64[5347]: time="2016-08-31T08:07:13+02:00" level=debug msg="WsReceiver: model.WebSocketEvent{TeamId:\"\", ChannelId:\"\", UserId:\"5whsec99ntbq7pcjgepodcbzbr\", Event:\"status_change\", Data:map[string]interface {}{\"status\":\"online\"}}" module=matterclient
Aug 31 08:07:13 dagaz matterircd-linux64[5347]: time="2016-08-31T08:07:13+02:00" level=debug msg="WsReceiver: &model.WebSocketEvent{TeamId:\"\", ChannelId:\"\", UserId:\"5whsec99ntbq7pcjgepodcbzbr\", Event:\"status_change\", Data:map[string]interface {}{\"status\":\"online\"}}" module=matterircd
Aug 31 08:07:13 dagaz matterircd-linux64[5347]: time="2016-08-31T08:07:13+02:00" level=debug msg="in handleWsMessage" module=matterircd
Aug 31 08:07:17 dagaz matterircd-linux64[5347]: time="2016-08-31T08:07:17+02:00" level=debug msg="<- JOIN #testing" module=matterircd
Aug 31 08:07:17 dagaz matterircd-linux64[5347]: time="2016-08-31T08:07:17+02:00" level=debug msg="Joining w65mwyxxajd8uf9zgcg7k38yzw" module=matterclient
Aug 31 08:07:17 dagaz matterircd-linux64[5347]: time="2016-08-31T08:07:17+02:00" level=debug msg="-> :tobiasr!tobiasr@localhost JOIN testing" module=matterircd
Aug 31 08:07:17 dagaz matterircd-linux64[5347]: time="2016-08-31T08:07:17+02:00" level=debug msg="-> :matterircd 353 tobiasr = testing :tobiasr " module=matterircd
Aug 31 08:07:17 dagaz matterircd-linux64[5347]: time="2016-08-31T08:07:17+02:00" level=debug msg="-> :matterircd 366 tobiasr testing :End of /NAMES list." module=matterircd
```

**Comment by 42wim** [comment]
Ok, bug found. But I can only reproduce it be first leaving the #testing channel and then joining it again.

**Comment by 42wim** [comment]
Could you try https://github.com/42wim/matterircd/releases/download/v0.10.0/matterircd-linux64-test and see if it's fixed for you ?

**Comment by 2-B** [comment]
Looks like it's fixed. Thanks.
