### ISSUE TITLE
Add NickServ-alias or rename mattermost account

### ISSUE THREAD

**Issue by merlinschumacher** [42wim/matterircd#72]
When you use a client where you can't specify the account to which you send your credentials for the login (like Pidgin), it won't auto-login because there is no NickServ user.

**Comment by 42wim** [comment]
Sorry, not going to fix this. This should be a client-side option.

**Comment by merlinschumacher** [comment]
It should be, yes. But it isn't in some popular clients. And the NickServ-User is the best practice in IRC environments.
