### ISSUE TITLE
Multi team better support

### ISSUE THREAD

**Issue by Celedhrim** [42wim/matterircd#74]
I am on 3 team , and add in my irc client , 1 account per team 

But there is 2 issue : 

Private message are send to all team : 
1 mattermost private message = 3 query on irc 

Channel sometime pop in another account 
in team1 irc server I have #team2/channel
and in team2 I have channel , they all says same thing

Could it be possible to bloque external team event ?

**Comment by 42wim** [comment]
This should be fixed now.
