### ISSUE TITLE
Messages coming from matterircd has a trailing whitespace at the end

### ISSUE THREAD

**Issue by patoupatou** [42wim/matterircd#75]
I was trying to use a bot on mattermost, which parses the messages like this:

@bot weather
@bot weather <city>

The second one was working fine but the first call never worked. The bot was trying to find a city named " " instead of using the default one. I then noticed that this was working currently when using the web client. That is because all the messages sent using matterircd have that trailing whitespace. I don't know if it's there by design, but I think if not it should be removed and fixed if possible.

Thank you!

**Comment by 42wim** [comment]
See https://github.com/42wim/matterircd/pull/50
Seems I removed it in the README, will add it again.
