### ISSUE TITLE
ISON command not working

### ISSUE THREAD

**Issue by der-tale** [42wim/matterircd#78]
Any ISON command sent to matterircd results in "461 ISON", my client says:

> 11:01:10    most =!= | irc: too few arguments received from IRC server for command "461" (received: 3 arguments, expected: at least 4)
> 11:01:10    most =!= | irc: failed to parse command "461" (please report to developers):
> 11:01:10    most =!= | :matterircd 461 ISON

The debug log of Matterircd just reads:

> Jan 09 11:00:57 effit matterircd-linux64[29501]: time="2017-01-09T11:00:57+01:00" level=debug msg="<- ISON :mzamora" module=matterircd
> Jan 09 11:00:57 effit matterircd-linux64[29501]: time="2017-01-09T11:00:57+01:00" level=debug msg="-> :matterircd 461 ISON" module=matterircd

Authorization is done via MMAUTHTOKEN (Gitlab).

**Comment by 42wim** [comment]
Seems like some clients misbehave. Just fixed it in master.
