### ISSUE TITLE
ISON reports all users as online

### ISSUE THREAD

**Issue by der-tale** [42wim/matterircd#79]
After fixing #78 ISON works now, but reports every user as online, even if WHOIS seems to report the away status correctly:

`/WHOIS julien`
> 10:55:53    most  -- | [julien] (eo54h7tonfnx7yr1ip8wqb4jdr@http://localhost:8065): Julien
> 10:55:53    most  -- | [julien] #mattermost-support #off-topic #town-square #twitter-to-keyword &users #Off-Topic
> 10:55:53    most  -- | [julien] is away: offline
> 10:55:53    most  -- | [julien] End of /WHOIS list.

`/ISON julien`
> 10:56:01    most  -- | Users online: julien

**Comment by 42wim** [comment]
Well I'm not sure what to do there, technically the user is online on the irc server.
If you're away on irc ison also reports the user online.

**Comment by der-tale** [comment]
I am both using Slack's IRC bridge and matterircd with Mattermost. Using Slack's bridge my IRC clients display users as away when they are offline, while using matterircd all users are marked as online all the time.

I am not sure if the clients use ISON or WHOIS as a basis for this display, but Slack's interpretation / use of IRC features makes in my opinion more sense in the context of a closed user group.

**Comment by 42wim** [comment]
Could you show me the output of /WHOIS and /ISON of a user that's offline on the slack irc bridge ?

**Comment by der-tale** [comment]
Okay, i have got it figured out. The IRC clients seem to use the output of /WHO as a presence indicator, not the output of /WHOIS or /ISON. To answer your question, Slack's irc bridge is not giving any presence information in its WHOIS output. 

I am closing this ticket because matterircd's implementation of WHOIS or ISON is perfectly fine not the reason for my problems.
