### ISSUE TITLE
Private messages between IRC and Mattermost users must be started by IRC user

### ISSUE THREAD

**Issue by yuvipanda** [42wim/matterircd#8]
If I send a 'Direct Message' (via the mattermost web interface) to a user who is using the IRC bridge, the messages are lost. However, if it is started by the IRC user sending a /msg or /query to the user on the web interface user, everything works fine.

As an example, in the following conversations, `yuvipanda` is on the web interface and `halfak` is on the irc bridge:

    yuvipanda
    hey
    yuvipanda
    are you seeing this?
    
    halfak
    TEst
    
    yuvipanda
    hi
    yuvipanda
    yes
    
    halfak
    Hey 
    
In this case, `halfak` user only saw messages sent by yuvipanda user *after* halfak also first said `TEst`. The first two messages from yuvipanda (hey and are you seeing this?) were totally lost.

**Comment by 42wim** [comment]
Cannot reproduce this. 
Could you run matterircd with debug, try to trigger it and post the WsReceiver lines before  "DEBUG direct message" ?

**Comment by yuvipanda** [comment]
Super verbose logs at https://gist.github.com/yuvipanda/9d87ab43f1a58dd2d38d

User on mattermost web UI is: yuvipanda. User on the IRC bridge is halfak_test. yuvipanda first sends numbers 1 to 10 on the direct message, which aren't received by IRC user. then IRC user sends something, and that's received by the mattermost web user and then the two can communicate normally.
