### ISSUE TITLE
WHO command marks all users as H(ere)

### ISSUE THREAD

**Issue by der-tale** [42wim/matterircd#81]
Matterircd's implementation of the WHO command marks all users as H (here), even if they are marked away (user and channel names omitted):

/WHO #channel
> ...
> 15:07:22       most  -- | [#...] ... o4jbpg71ridp8p186tjyai5d5r@http://localhost:8065 H 0 (...)
> ...

/WHOIS ... 
> 15:10:51       most  -- | [...] (o4jbpg71ridp8p186tjyai5d5r@http://localhost:8065): ...
> 15:10:51       most  -- | [...] &users #... #... #off-topic #town-square
> 15:10:51       most  -- | [...] is away: offline
> 15:10:51       most  -- | [...] End of /WHOIS list.

Slack's irc bridge is marking users as G (gone) if they are offline in slack.

**Comment by 42wim** [comment]
Thanks for the report, this is fixed now in master.
