### ISSUE TITLE
Pasted images

### ISSUE THREAD

**Issue by furai** [42wim/matterircd#82]
Hey,

It seems that any pasted/uploaded images don't appear for me in IRC. Is this expected behaviour? Or am I missing some configuration?

Cheers,
Furai

**Comment by maxandersen** [comment]
I see the same issue and would like to try do a fix for this but not sure where to start. Any pointers to protocol for the images or where in the implementation one would start would be great.

**Comment by 42wim** [comment]
Seems like this behaviour changed since mattermost 3.5.0 when they changed from Filenames to FileIds.
I've fixed this so matterircd behaves the same again for public links (public links have to be enabled on mattermost instance).

This will not work for private links.

@maxandersen are you willing to look into this to get it to work for private links ?

**Comment by maxandersen** [comment]
by private links you mean files shared in private groups / direct messages ?

**Comment by 42wim** [comment]
In your PR #89 for this issue you said:

> doing the same as was done for filenames, but fileid instead and using direct links rather than public ones.

I thought you meant using private links (when the public links option hasn't been enabled in the mattermost console). 

I haven't tested anything yet with public links option disabled

**Comment by maxandersen** [comment]
ah - I haven't tried fiddling with the console, just using the instance we got at work for which public links didn't work so I had to print out the private links. I guess I should just check if get public info works, if yes - print that, if not - print the private ones.

**Comment by 42wim** [comment]
I'm going to close this for now, if you're going to look further into public links, feel free to open a PR
