### ISSUE TITLE
How do I connect to localhost?

### ISSUE THREAD

**Issue by sokoow** [42wim/matterircd#87]
I got a mattermost server on same host as matterircd, and I'm launching it with: 

```
matterircd --bind 0.0.0.0:6667 -mmserver localhost -mmteam public
```
As soon as i invoke login <user> <password>, I get model.client.connecting.app_error. 

Any idea how to debug this ?

**Comment by 42wim** [comment]
I guess you're not running https ? try adding ```-mminsecure```

**Comment by sokoow** [comment]
now I'm getting:

```
model.utils.decode_json.app_error
```

when trying to invoke ``` login localhost team user password ```

**Comment by 42wim** [comment]
are you sure mattermost is listening on port 80 and not port 8065 ? otherwise you'll have to specify localhost:8065 or 127.0.0.1:8065

**Comment by sokoow** [comment]
ok, works now, thanks :)
