### ISSUE TITLE
Can't connect to mattermost

### ISSUE THREAD

**Issue by seanirby** [42wim/matterircd#90]
My work team uses mattermost and I would love to get this setup but I'm having some issues.

Starting matterircd with:

`matterircd -debug -mminsecure -mmserver redacted -mmteam redacted`

Then through CIRC:

`/server 127.0.0.1`

Here I see the MOTD and verify that I'm connected to the IRC server.  Next I run:

`/msg mattermost login redacted redacted`

I get the following error in the irc client:
`mattermost  There doesn't appear to be an api call for the url='/api/v3/users/0/50000'.  Typo? are you missing a team_id or user_id as part of the url?`

Following this advice I try starting matterircd with the url with my team id appended.  It's the same URL i would use if I wanted to join my team chat through the browser.  When I try logging in here I get the error: `mattermost  model.client.connecting.app_error` /

Any ideas?

**Comment by 42wim** [comment]
What is your matterircd version ?
What is your mattermost version ?

**Comment by seanirby** [comment]
OK I missed a detail in the README.  Almost working, I connect to the server and auto join all the channels, but I don't receive any channel communication, can only transmit messages.  Will create a new issue with the version info.
