### ISSUE TITLE
IRC messages sent to other IRC users have extra characters

### ISSUE THREAD

**Issue by pushplay** [42wim/matterircd#94]
I connected an IRC bot written in Java to Matterircd and I'm having a problem with text coming from IRC users.  Here's the string `quote` sent from the web interface (Java represents characters as UTF-16 remember):

`0x0071 0x0075 0x006f 0x0074 0x0065`

And here's the string `quote` sent from irssi connected to Matterircd:

`0x0071 0x0075 0x006f 0x0074 0x0065 0x0020 0x200b`

There's an extra space and a zero width space at the end.  Inspecting the web DOM it looks like the extra characters are also delivered to the web interface.

We're using Matterircd v0.11.3, Mattermost 3.7.3.

**Comment by 42wim** [comment]
This is by "design", it's a marker to see if matterircd sent the message.
Otherwise all your messages will be echoed on IRC, because there is no way to know if the message you send came from IRC or came from the web browser (or from any other client).

See https://github.com/42wim/matterircd/pull/50 for more information

I should add it back to the README though :)

**Comment by pushplay** [comment]
Ok I think I understand the issue.  Mattermost is shipping your messages back to you and you don't know if they should be relayed to the irc client or not without the hacky tag-like characters.

The extra spaces isn't great for existing irc bots which may be programmed with functionality that work on exact characters.  At a minimum stripping the sentinel values before relaying them to the irc clients minimizes the impact.  Although it still affects Slack-style bots.

I would hope for a place in the Mattermost protocol to attach meta data.  Just reading through the docs it looks like `post` is the chat line we're talking about.  What about `"props": { }` on there?  I don't see any documentation on the semantics of that but it may be what I'm talking about.

**Comment by 42wim** [comment]
Thanks, that could be a good idea, I'll look into this.

**Comment by 42wim** [comment]
Implemented in master and building in docker. Thanks for this idea!

**Comment by pushplay** [comment]
Sweet.  Glad that worked out.
