### ISSUE TITLE
Fails to login on v3.8.2

### ISSUE THREAD

**Issue by JonLundy** [42wim/matterircd#96]
When i try to login i get the following error:
`<mattermost> There doesn't appear to be an api call for the url='/api/v3/teams/1cm3b7b91fddbqye4hm1ckw1hc/channels/more'.  Typo? are you missing a team_id or user_id as part of the url?`

it seems that api doesn't exsist anymore?

**Comment by 42wim** [comment]
Are you sure you're using matterircd 0.11.3 ?
