### ISSUE TITLE
Sign Into irc With gitlab

### ISSUE THREAD

**Issue by UnRealDinnerbone** [42wim/matterircd#98]
The Server im on needs me to log on with GitLab? is there a way i can do that on irc

**Comment by paretje** [comment]
You can use the authtoken in the cookie when you login using GitLab. There is https://github.com/recht/mattermost-auth to do this. I updated the code to work with the current cefpython3 version (https://github.com/paretje/mattermost-auth), but it didn't work reliably, and often "missed" the cookie, and kept on waiting.

Two weeks ago, I wrote [this](https://github.com/paretje/dotfiles/blob/master/bin/mattermost-auth) script, which does the authentication automatically (see  https://github.com/paretje/dotfiles/blob/master/.weechat/irc.conf#L298).

**Comment by 42wim** [comment]
Closing this, added to the FAQ in the readme
